-- Insert all 1,533 business niches from the PDF
-- Organized by industry category

-- Arts & Entertainment (92 niches)
INSERT INTO niches (niche_name, industry_id) 
SELECT niche_name, (SELECT id FROM industries WHERE name = 'Arts & Entertainment')
FROM (VALUES
  ('Acting Schools'),
  ('Aerial Photography'),
  ('Amusement Parks'),
  ('Art Galleries'),
  ('Art Institute'),
  ('Art Posters'),
  ('Art Schools'),
  ('Art Supplies'),
  ('Artists'),
  ('Bars'),
  ('Beads Wholesale'),
  ('CD Duplicators'),
  ('Cad Drafter'),
  ('Catering'),
  ('Clowns'),
  ('Comedy Clubs'),
  ('Commercial Photography'),
  ('Concert Tickets'),
  ('Craft Supplies'),
  ('Dance Classes'),
  ('Dance Clubs'),
  ('Dance Lessons'),
  ('Digital Cameras'),
  ('Drafting Supplies'),
  ('Embroidery'),
  ('Embroidery Services'),
  ('Entertainers'),
  ('Event Planning'),
  ('Family Entertainment'),
  ('Fashion Photography'),
  ('Festivals'),
  ('Film Production'),
  ('Graphic Arts'),
  ('Graphic Design'),
  ('Graphic Designers'),
  ('Guitars'),
  ('Headshots'),
  ('Home Theater Projectors'),
  ('Libraries'),
  ('Logos'),
  ('Magicians'),
  ('Maternity Photography'),
  ('Modeling Agencies'),
  ('Modern Art'),
  ('Movie Production'),
  ('Movie Theaters'),
  ('Museums'),
  ('Music'),
  ('Music Downloads'),
  ('Music Education'),
  ('Music Lessons'),
  ('Music Stores'),
  ('Music Venues'),
  ('Musical Instruments'),
  ('Musicals'),
  ('Night Clubs'),
  ('Party Planning'),
  ('Passport Pictures'),
  ('Performing Arts'),
  ('Performing Arts Schools'),
  ('Photo Developing'),
  ('Photo Printing'),
  ('Photography'),
  ('Photography Equipment'),
  ('Photography Schools'),
  ('Photography Studios'),
  ('Piano Lessons'),
  ('Piano Tuning'),
  ('Pianos'),
  ('Portrait Photography'),
  ('Portrait Studios'),
  ('Professional Photography'),
  ('Public Libraries'),
  ('Recording Studios'),
  ('Scrapbooking Supplies'),
  ('Senior Portraits'),
  ('Special Events'),
  ('Sports Tickets'),
  ('Stage Construction'),
  ('Talent Agencies'),
  ('Theater Tickets'),
  ('Used Pianos'),
  ('VHS To DVD'),
  ('Video Production Services'),
  ('Video Rentals'),
  ('Videography'),
  ('Violins'),
  ('Voice Lessons'),
  ('Wedding Photography'),
  ('Yarn'),
  ('Zoos')
) AS t(niche_name);

-- Automotive (70 niches)
INSERT INTO niches (niche_name, industry_id) 
SELECT niche_name, (SELECT id FROM industries WHERE name = 'Automotive')
FROM (VALUES
  ('Airport Parking'),
  ('Auto AC Repair'),
  ('Auto Alignment'),
  ('Auto Body Shops'),
  ('Auto Detailing'),
  ('Auto Electrical Repair'),
  ('Auto Glass Retail'),
  ('Auto Leasing'),
  ('Auto Loans'),
  ('Auto Parts'),
  ('Auto Recycling'),
  ('Auto Repair Shops'),
  ('Auto Restoration'),
  ('Auto Upholstery'),
  ('Auto Wrecker'),
  ('Brake Repair'),
  ('Car Auctions'),
  ('Car Buyers'),
  ('Car Dealers'),
  ('Car Financing'),
  ('Car Inspection'),
  ('Car Locksmith'),
  ('Car Parts'),
  ('Car Racing (Event-Related)'),
  ('Car Repair'),
  ('Car Stereo Installation'),
  ('Car Storage'),
  ('Car Title Registration'),
  ('Car Transports'),
  ('Car Washes'),
  ('Classic Cars (Sales/Restoration)'),
  ('Commercial Car Rental'),
  ('Driving Schools'),
  ('Emissions Testing'),
  ('Fleet Services'),
  ('Gas Stations (Membership Programs)'),
  ('Junk Car Removal'),
  ('Limousine Service'),
  ('Luxury Car Rental'),
  ('Motorcycle Dealers'),
  ('Motorcycle Insurance'),
  ('Motorcycle Parts'),
  ('Motorcycle Repair'),
  ('Parking Garages'),
  ('Rental Cars'),
  ('Roadside Assistance'),
  ('Tire Dealers'),
  ('Towing Service'),
  ('Trailer Rental'),
  ('Trailer Sales'),
  ('Transmission Shops'),
  ('Truck Accessories'),
  ('Truck Driving Schools'),
  ('Truck Insurance'),
  ('Truck Rental'),
  ('Truck Repair'),
  ('Trucks For Sale'),
  ('Used Auto Parts'),
  ('Used Car Dealers'),
  ('Used Cars'),
  ('Used Motorcycles'),
  ('Used RVs'),
  ('Used Tires'),
  ('Used Trucks'),
  ('Valet Parking'),
  ('Van Rental'),
  ('Wheel Alignment'),
  ('Window Tinting'),
  ('Windshield Replacement')
) AS t(niche_name);

-- Business Services (109 niches)
INSERT INTO niches (niche_name, industry_id) 
SELECT niche_name, (SELECT id FROM industries WHERE name = 'Business Services')
FROM (VALUES
  ('Access Control Systems'),
  ('Ad Agencies'),
  ('Advertising'),
  ('Advertising Agencies'),
  ('Air Duct Cleaning'),
  ('Alarm Systems'),
  ('Auction Houses'),
  ('Auctions'),
  ('Background Checks'),
  ('Business Brokers'),
  ('Business Card Printing'),
  ('Business Cards'),
  ('Business Consultants'),
  ('Business Directory'),
  ('Business Marketing'),
  ('Call Centers'),
  ('Chamber Of Commerce'),
  ('Classified Ads'),
  ('Commercial Printer'),
  ('Conference Centers'),
  ('Conference Management'),
  ('Convention Centers'),
  ('Copier Repair'),
  ('Copier Service'),
  ('Copywriters'),
  ('Custom Signs'),
  ('Design Agency'),
  ('Direct Mail Advertising'),
  ('Direct Marketing'),
  ('Document Destruction'),
  ('Dryer Vent Cleaning'),
  ('Dumpster Rental'),
  ('Ecommerce'),
  ('Email Marketing'),
  ('Employment Agencies'),
  ('Employment Screening'),
  ('Environmental Services'),
  ('Event Planning'),
  ('Franchise Opportunities'),
  ('GPS Systems'),
  ('GPS Tracking'),
  ('Home Alarm Systems'),
  ('Home Security Systems'),
  ('House Cleaning Services'),
  ('Human Resources Jobs'),
  ('Incorporation Services'),
  ('Investigation Services'),
  ('Janitorial Services'),
  ('Job Listing Services'),
  ('Junk Removal'),
  ('LED Signs'),
  ('Locksmiths'),
  ('Mailing Lists'),
  ('Mailing Services'),
  ('Management Consulting'),
  ('Market Research'),
  ('Marketing Consultants'),
  ('Mold Removal'),
  ('Moving Companies'),
  ('Name Badges'),
  ('Neon Signs'),
  ('Newspapers'),
  ('Office Cleaning'),
  ('Office Records Storage'),
  ('Paper Shredding'),
  ('Pest Control Services'),
  ('Printers'),
  ('Printing'),
  ('Private Detectives'),
  ('Private Investigators'),
  ('Professional Services'),
  ('Promotional Items'),
  ('Promotional Products'),
  ('Public Relations Firms'),
  ('Publishing Companies'),
  ('Recycling'),
  ('Recruiters'),
  ('Resume Writers'),
  ('Screen Printing'),
  ('Security Cameras'),
  ('Security Guards'),
  ('Solar Energy'),
  ('Solar Panel Installation'),
  ('Staffing Agencies'),
  ('Temp Agencies'),
  ('Transcription Services'),
  ('Translation Services'),
  ('Tree Services'),
  ('Video Conferencing'),
  ('Virtual Office Assistants'),
  ('Window Cleaning'),
  ('Yellow Pages Advertising'),
  ('Security Jobs'),
  ('Sprinkler Systems'),
  ('Stationery'),
  ('Structural Engineers'),
  ('Surveillance Cameras'),
  ('Surveyors'),
  ('Time Clocks'),
  ('Toner Cartridges'),
  ('Used Office Furniture'),
  ('Utilities'),
  ('Venetian Blinds'),
  ('Vent A Hood'),
  ('Voice Recorder'),
  ('Waste Disposal Management'),
  ('Water')
) AS t(niche_name);

-- Due to message length limits, I'll continue in the next message...
