-- Insert Industries and Niches - Part 1
-- Agriculture & Mining (81 niches) + Arts & Entertainment (92 niches)

-- Insert Agriculture & Mining Industry
INSERT INTO industries (name, description, sort_order)
VALUES ('Agriculture & Mining', 'Farming, agricultural services, and mining operations', 1)
ON CONFLICT (name) DO NOTHING;

-- Insert Agriculture & Mining Niches (81 niches)
INSERT INTO niches (industry_id, name, scale, estimated_database_size) VALUES
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Christmas Tree Farms', 'Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Organic Food and Farming', 'National/Local', 50000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Vineyards', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Fruit and Tree Nut Farming', 'National/Local', 30000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Greenhouse and Nursery', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Vegetable and Melon Farming', 'National/Local', 35000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Dairy Cattle and Milk Production', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Beef Cattle Ranching and Farming', 'National/Local', 40000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Hog and Pig Farming', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Poultry and Egg Production', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Sheep and Goat Farming', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Aquaculture', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Timber Tract Operations', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Forest Nurseries and Gathering of Forest Products', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Logging', 'National/Local', 18000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Fishing', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Hunting and Trapping', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Oil and Gas Extraction', 'National', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Coal Mining', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Metal Ore Mining', 'National', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Nonmetallic Mineral Mining and Quarrying', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Support Activities for Agriculture', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Support Activities for Forestry', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Support Activities for Oil and Gas Operations', 'National', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Support Activities for Mining', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Crop Harvesting', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Cotton Farming', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Tobacco Farming', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Sugarcane Farming', 'Local', 1500),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Hay Farming', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Oilseed and Grain Farming', 'National/Local', 35000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Wheat Farming', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Corn Farming', 'National/Local', 30000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Rice Farming', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Soybean Farming', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Peanut Farming', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Other Grain Farming', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Berry Farming', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Grape Vineyards', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Tree Nut Farming', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Citrus Groves', 'Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Apple Orchards', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Stone Fruit Farming', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Potato Farming', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Tomato Farming', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Mushroom Production', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Floriculture Production', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Food Crops Grown Under Cover', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Nursery and Tree Production', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Horse and Other Equine Production', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Chicken Egg Production', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Broilers and Other Meat Type Chicken Production', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Turkey Production', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Poultry Hatcheries', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Dairy Farms', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Dual-Purpose Cattle Ranching and Farming', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Feedlots', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Animal Aquaculture', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Finfish Farming and Fish Hatcheries', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Shellfish Farming', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Apiculture', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Fur-Bearing Animal and Rabbit Production', 'Local', 1000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'All Other Animal Production', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Soil Preparation, Planting and Cultivating', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Postharvest Crop Activities', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Farm Management Services', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Farm Labor Contractors and Crew Leaders', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Cotton Ginning', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Bituminous Coal and Lignite Surface Mining', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Bituminous Coal Underground Mining', 'National/Local', 1000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Anthracite Mining', 'Local', 500),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Iron Ore Mining', 'National', 500),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Gold Ore and Silver Ore Mining', 'National', 800),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Copper, Nickel, Lead and Zinc Mining', 'National', 600),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Other Metal Ore Mining', 'National', 400),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Dimension Stone Mining and Quarrying', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Crushed and Broken Limestone Mining and Quarrying', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Construction Sand and Gravel Mining', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Agriculture & Mining'), 'Other Crushed and Broken Stone Mining and Quarrying', 'National/Local', 3000);

-- Insert Arts & Entertainment Industry
INSERT INTO industries (name, description, sort_order)
VALUES ('Arts & Entertainment', 'Entertainment, media production, and recreational services', 2)
ON CONFLICT (name) DO NOTHING;

-- Insert Arts & Entertainment Niches (92 niches)
INSERT INTO niches (industry_id, name, scale, estimated_database_size) VALUES
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Movie Theaters', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Live Theater and Performing Arts', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Sports Teams and Clubs', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Racetracks', 'National/Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Independent Artists and Performers', 'National/Local', 50000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Museums and Art Galleries', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Amusement Parks and Arcades', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Bowling Centers', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Gambling Industries', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Golf Courses and Country Clubs', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Skiing Facilities', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Marinas', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Fitness and Recreational Sports Centers', 'National/Local', 40000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Motion Picture and Video Production', 'National', 25000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Motion Picture and Video Distribution', 'National', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Sound Recording Studios', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Radio and Television Broadcasting', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Cable and Other Subscription Programming', 'National', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Wired and Wireless Telecommunications Carriers', 'National', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Theater Companies and Dinner Theaters', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Dance Companies', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Musical Groups and Artists', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Other Performing Arts Companies', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Spectator Sports', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Promoters of Performing Arts and Sports', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Agents and Managers for Artists and Entertainers', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Independent Writers', 'National/Local', 40000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Historical Sites', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Zoos and Botanical Gardens', 'National/Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Nature Parks and Other Similar Institutions', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Amusement and Theme Parks', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Amusement Arcades', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Casinos', 'National/Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Other Gambling Industries', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'All Other Amusement and Recreation Industries', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Movie and Video Production', 'National', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Postproduction Services and Other Motion Picture Industries', 'National', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Integrated Record Production/Distribution', 'National', 1000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Music Publishers', 'National', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Sound Recording Industries', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Radio Broadcasting Stations', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Television Broadcasting Stations', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Cable Networks', 'National', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Other Telecommunications', 'National', 10000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Data Processing and Hosting Services', 'National', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Web Hosting Services', 'National', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Other Information Services', 'National', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'News Syndicates', 'National', 1000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Libraries and Archives', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Internet Publishing and Broadcasting', 'National', 20000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'All Other Publishers', 'National', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Software Publishers', 'National', 25000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Sports and Recreation Instruction', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'All Other Schools and Instruction', 'National/Local', 30000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Photography Studios and Portrait', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Commercial Photography', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Roller Skating Rinks', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Ice Skating Rinks', 'Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Go-Kart Tracks', 'Local', 1000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Miniature Golf Courses', 'Local', 2500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Billiard and Pool Halls', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Adventure Tourism', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Video Game Arcades', 'Local', 4000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Escape Room Facilities', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Trampoline Parks', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Virtual Reality Arcades', 'Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Laser Tag Centers', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Paint and Sip Studios', 'Local', 4000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Art Studios and Classes', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Pottery and Ceramics Studios', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Music Instruction', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Dance Instruction', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Martial Arts Instruction', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Yoga and Pilates Studios', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Swimming Instruction', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Tennis Instruction', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Diving Instruction', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Surfing Instruction', 'Local', 1500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Rock Climbing Gyms', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Batting Cages', 'Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Driving Ranges', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Shooting Ranges', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Paintball Facilities', 'Local', 2500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Comedy Clubs', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Concert Halls', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Opera Companies', 'National/Local', 500),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Ballet Companies', 'National/Local', 800),
((SELECT id FROM industries WHERE name = 'Arts & Entertainment'), 'Circuses', 'National', 200);
