-- Insert all 19 industries
INSERT INTO industries (name, notes) VALUES
('Arts & Entertainment', '92 niches'),
('Automotive', '70 niches'),
('Business Services', '109 niches'),
('Clothing & Accessories', '65 niches'),
('Community and Government', '95 niches'),
('Computer & Tech', '72 niches'),
('Construction & Tradesmen', '90 niches'),
('Education', '73 niches'),
('Hospitality & Food', '83 niches'),
('Medicine & Health', '97 niches'),
('Home Improvements', '78 niches'),
('Agriculture & Mining', '81 niches'),
('Legal & Financial', '122 niches'),
('Media & Comms', '43 niches'),
('Fitness & Personal Care', '58 niches'),
('Real Estate', '66 niches'),
('Shopping & Retail', '74 niches'),
('Sports', '81 niches'),
('Travel & Transport', '87 niches')
ON CONFLICT (name) DO NOTHING;

-- Arts & Entertainment (92 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Acting Schools', 'Local', 'Small'),
  ('Aerial Photography', 'Local', 'Small'),
  ('Amusement Parks', 'National/Local', 'Big'),
  ('Art Galleries', 'Local', 'Small'),
  ('Art Institute', 'National', 'Big'),
  ('Art Posters', 'National', 'Big'),
  ('Art Schools', 'Local', 'Small'),
  ('Art Supplies', 'National/Local', 'Big'),
  ('Artists', 'Local', 'Small'),
  ('Bars', 'Local', 'Small'),
  ('Beads Wholesale', 'National/Local', 'Big'),
  ('CD Duplicators', 'Local', 'Small'),
  ('Cad Drafter', 'Local', 'Small'),
  ('Catering', 'Local', 'Small'),
  ('Clowns', 'Local', 'Small'),
  ('Comedy Clubs', 'Local', 'Small'),
  ('Commercial Photography', 'Local', 'Small'),
  ('Concert Tickets', 'National', 'Big'),
  ('Craft Supplies', 'National/Local', 'Big'),
  ('Dance Classes', 'Local', 'Small'),
  ('Dance Clubs', 'Local', 'Small'),
  ('Dance Lessons', 'Local', 'Small'),
  ('Digital Cameras', 'National', 'Big'),
  ('Drafting Supplies', 'National/Local', 'Big'),
  ('Embroidery', 'Local', 'Small'),
  ('Embroidery Services', 'Local', 'Small'),
  ('Entertainers', 'Local', 'Small'),
  ('Event Planning', 'Local', 'Small'),
  ('Family Entertainment', 'Local', 'Small'),
  ('Fashion Photography', 'Local', 'Small'),
  ('Festivals', 'Local', 'Small'),
  ('Film Production', 'National/Local', 'Big'),
  ('Graphic Arts', 'Local', 'Small'),
  ('Graphic Design', 'Local', 'Small'),
  ('Graphic Designers', 'Local', 'Small'),
  ('Guitars', 'National/Local', 'Big'),
  ('Headshots', 'Local', 'Small'),
  ('Home Theater Projectors', 'National', 'Big'),
  ('Libraries', 'Local', 'Small'),
  ('Logos', 'Local', 'Small'),
  ('Magicians', 'Local', 'Small'),
  ('Maternity Photography', 'Local', 'Small'),
  ('Modeling Agencies', 'National/Local', 'Big'),
  ('Modern Art', 'Local', 'Small'),
  ('Movie Production', 'National/Local', 'Big'),
  ('Movie Theaters', 'National/Local', 'Big'),
  ('Museums', 'Local', 'Small'),
  ('Music', 'National', 'Big'),
  ('Music Downloads', 'National', 'Big'),
  ('Music Education', 'Local', 'Small'),
  ('Music Lessons', 'Local', 'Small'),
  ('Music Stores', 'National/Local', 'Big'),
  ('Music Venues', 'Local', 'Small'),
  ('Musical Instruments', 'National', 'Big'),
  ('Musicals', 'Local', 'Small'),
  ('Night Clubs', 'Local', 'Small'),
  ('Party Planning', 'Local', 'Small'),
  ('Passport Pictures', 'Local', 'Small'),
  ('Performing Arts', 'Local', 'Small'),
  ('Performing Arts Schools', 'Local', 'Small'),
  ('Photo Developing', 'Local', 'Small'),
  ('Photo Printing', 'National/Local', 'Big'),
  ('Photography', 'Local', 'Small'),
  ('Photography Equipment', 'National', 'Big'),
  ('Photography Schools', 'Local', 'Small'),
  ('Photography Studios', 'Local', 'Small'),
  ('Piano Lessons', 'Local', 'Small'),
  ('Piano Tuning', 'Local', 'Small'),
  ('Pianos', 'National/Local', 'Big'),
  ('Portrait Photography', 'Local', 'Small'),
  ('Portrait Studios', 'Local', 'Small'),
  ('Professional Photography', 'Local', 'Small'),
  ('Public Libraries', 'Local', 'Small'),
  ('Recording Studios', 'Local', 'Small'),
  ('Scrapbooking Supplies', 'National/Local', 'Big'),
  ('Senior Portraits', 'Local', 'Small'),
  ('Special Events', 'Local', 'Small'),
  ('Sports Tickets', 'National', 'Big'),
  ('Stage Construction', 'Local', 'Small'),
  ('Talent Agencies', 'National/Local', 'Big'),
  ('Theater Tickets', 'National', 'Big'),
  ('Used Pianos', 'Local', 'Small'),
  ('VHS To DVD', 'Local', 'Small'),
  ('Video Production Service', 'Local', 'Small'),
  ('Video Rentals', 'Local', 'Small'),
  ('Videography', 'Local', 'Small'),
  ('Violins', 'National/Local', 'Big'),
  ('Voice Lessons', 'Local', 'Small'),
  ('Wedding Photography', 'Local', 'Small'),
  ('Yarn', 'National/Local', 'Big'),
  ('Zoos', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Arts & Entertainment'
ON CONFLICT DO NOTHING;

-- Automotive (70 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Airport Parking', 'Local', 'Small'),
  ('Auto AC Repair', 'Local', 'Small'),
  ('Auto Alignment', 'Local', 'Small'),
  ('Auto Body Shops', 'Local', 'Small'),
  ('Auto Detailing', 'Local', 'Small'),
  ('Auto Electrical Repair', 'Local', 'Small'),
  ('Auto Glass Retail', 'Local', 'Small'),
  ('Auto Leasing', 'National', 'Big'),
  ('Auto Loans', 'National', 'Big'),
  ('Auto Parts', 'National', 'Big'),
  ('Auto Recycling', 'Local', 'Small'),
  ('Auto Repair Shops', 'Local', 'Small'),
  ('Auto Restoration', 'Local', 'Small'),
  ('Auto Upholstery', 'Local', 'Small'),
  ('Auto Wrecker', 'Local', 'Small'),
  ('Brake Repair', 'Local', 'Small'),
  ('Car Auctions', 'National/Local', 'Big'),
  ('Car Buyers', 'National', 'Big'),
  ('Car Dealers', 'National/Local', 'Big'),
  ('Car Financing', 'National', 'Big'),
  ('Car Inspection', 'Local', 'Small'),
  ('Car Locksmith', 'Local', 'Small'),
  ('Car Parts', 'National', 'Big'),
  ('Car Racing', 'National/Local', 'Big'),
  ('Car Repair', 'Local', 'Small'),
  ('Car Stereo Installation', 'Local', 'Small'),
  ('Car Storage', 'Local', 'Small'),
  ('Car Title Registration', 'National/Local', 'Small'),
  ('Car Transports', 'National/Local', 'Big'),
  ('Car Washes', 'Local', 'Small'),
  ('Classic Cars', 'National/Local', 'Big'),
  ('Commercial Car Rental', 'National', 'Big'),
  ('Driving Schools', 'Local', 'Small'),
  ('Emissions Testing', 'Local', 'Small'),
  ('Fleet Services', 'National', 'Big'),
  ('Gas Stations', 'National', 'Big'),
  ('Junk Car Removal', 'Local', 'Small'),
  ('Limousine Service', 'National/Local', 'Big'),
  ('Luxury Car Rental', 'National', 'Big'),
  ('Motorcycle Dealers', 'National/Local', 'Big'),
  ('Motorcycle Insurance', 'National', 'Big'),
  ('Motorcycle Parts', 'National', 'Big'),
  ('Motorcycle Repair', 'Local', 'Small'),
  ('Parking Garages', 'Local', 'Small'),
  ('Rental Cars', 'National', 'Big'),
  ('Roadside Assistance', 'National', 'Big'),
  ('Tire Dealers', 'National/Local', 'Big'),
  ('Towing Service', 'Local', 'Small'),
  ('Trailer Rental', 'Local', 'Small'),
  ('Trailer Sales', 'National/Local', 'Small'),
  ('Transmission Shops', 'Local', 'Small'),
  ('Truck Accessories', 'National', 'Big'),
  ('Truck Driving Schools', 'Local', 'Small'),
  ('Truck Insurance', 'National', 'Big'),
  ('Truck Rental', 'National', 'Big'),
  ('Truck Repair', 'Local', 'Small'),
  ('Trucks For Sale', 'National/Local', 'Big'),
  ('Used Auto Parts', 'Local', 'Small'),
  ('Used Car Dealers', 'Local', 'Small'),
  ('Used Cars', 'National/Local', 'Big'),
  ('Used Motorcycles', 'Local', 'Small'),
  ('Used RVs', 'Local', 'Small'),
  ('Used Tires', 'Local', 'Small'),
  ('Used Trucks', 'National/Local', 'Big'),
  ('Valet Parking', 'Local', 'Small'),
  ('Van Rental', 'National', 'Big'),
  ('Wheel Alignment', 'Local', 'Small'),
  ('Window Tinting', 'Local', 'Small'),
  ('Windshield Replacement', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Automotive'
ON CONFLICT DO NOTHING;

-- Business Services (109 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Access Control Systems', 'National', 'Big'),
  ('Ad Agencies', 'National/Local', 'Big'),
  ('Advertising', 'National', 'Big'),
  ('Advertising Agencies', 'National/Local', 'Big'),
  ('Air Duct Cleaning', 'Local', 'Small'),
  ('Alarm Systems', 'National/Local', 'Big'),
  ('Auction Houses', 'Local', 'Small'),
  ('Auctions', 'National/Local', 'Big'),
  ('Background Checks', 'National', 'Big'),
  ('Business Brokers', 'Local', 'Small'),
  ('Business Card Printing', 'Local', 'Small'),
  ('Business Cards', 'Local', 'Small'),
  ('Business Consultants', 'National/Local', 'Big'),
  ('Business Directory', 'National', 'Big'),
  ('Business Marketing', 'National', 'Big'),
  ('Call Centers', 'National', 'Big'),
  ('Chamber Of Commerce', 'Local', 'Small'),
  ('Classified Ads', 'National', 'Big'),
  ('Commercial Printer', 'Local', 'Small'),
  ('Conference Centers', 'Local', 'Small'),
  ('Conference Management', 'National', 'Big'),
  ('Convention Centers', 'Local', 'Small'),
  ('Copier Repair', 'Local', 'Small'),
  ('Copier Service', 'Local', 'Small'),
  ('Copywriters', 'National/Local', 'Small'),
  ('Custom Signs', 'Local', 'Small'),
  ('Design Agency', 'National/Local', 'Big'),
  ('Direct Mail Advertising', 'National', 'Big'),
  ('Direct Marketing', 'National', 'Big'),
  ('Document Destruction', 'National/Local', 'Big'),
  ('Dryer Vent Cleaning', 'Local', 'Small'),
  ('Dumpster Rental', 'Local', 'Small'),
  ('Ecommerce', 'National', 'Big'),
  ('Email Marketing', 'National', 'Big'),
  ('Employment Agencies', 'National/Local', 'Big'),
  ('Employment Screening', 'National', 'Big'),
  ('Environmental Services', 'National/Local', 'Big'),
  ('Event Planning', 'Local', 'Small'),
  ('Franchise Opportunities', 'National', 'Big'),
  ('GPS Systems', 'National', 'Big'),
  ('GPS Tracking', 'National', 'Big'),
  ('Home Alarm Systems', 'National/Local', 'Big'),
  ('Home Security Systems', 'National/Local', 'Big'),
  ('House Cleaning Services', 'Local', 'Small'),
  ('Human Resources Jobs', 'National', 'Big'),
  ('Incorporation Services', 'National', 'Big'),
  ('Investigation Services', 'National/Local', 'Small'),
  ('Janitorial Services', 'Local', 'Small'),
  ('Job Listing Services', 'National', 'Big'),
  ('Junk Removal', 'Local', 'Small'),
  ('LED Signs', 'National', 'Small'),
  ('Locksmiths', 'Local', 'Small'),
  ('Mailing Lists', 'National', 'Big'),
  ('Mailing Services', 'National/Local', 'Big'),
  ('Management Consulting', 'National', 'Big'),
  ('Market Research', 'National', 'Big'),
  ('Marketing Consultants', 'National/Local', 'Big'),
  ('Mold Removal', 'Local', 'Small'),
  ('Moving Companies', 'National/Local', 'Big'),
  ('Name Badges', 'Local', 'Small'),
  ('Neon Signs', 'Local', 'Small'),
  ('Newspapers', 'Local', 'Small'),
  ('Office Cleaning', 'Local', 'Small'),
  ('Office Records Storage', 'National/Local', 'Small'),
  ('Paper Shredding', 'National', 'Big'),
  ('Pest Control Services', 'Local', 'Small'),
  ('Printers', 'Local', 'Small'),
  ('Printing', 'Local', 'Small'),
  ('Private Detectives', 'Local', 'Small'),
  ('Private Investigators', 'Local', 'Small'),
  ('Professional Services', 'National/Local', 'Big'),
  ('Promotional Items', 'National', 'Big'),
  ('Promotional Products', 'National', 'Big'),
  ('Public Relations Firms', 'National/Local', 'Big'),
  ('Publishing Companies', 'National', 'Big'),
  ('Recycling', 'Local', 'Small'),
  ('Recruiters', 'National', 'Big'),
  ('Resume Writers', 'Local', 'Small'),
  ('Screen Printing', 'Local', 'Small'),
  ('Security Cameras', 'National/Local', 'Big'),
  ('Security Guards', 'Local', 'Small'),
  ('Solar Energy', 'National', 'Big'),
  ('Solar Panel Installation', 'National', 'Big'),
  ('Staffing Agencies', 'National/Local', 'Big'),
  ('Temp Agencies', 'National/Local', 'Big'),
  ('Transcription Services', 'National', 'Big'),
  ('Translation Services', 'National', 'Big'),
  ('Tree Services', 'Local', 'Small'),
  ('Video Conferencing', 'National', 'Big'),
  ('Virtual Office Assistants', 'National', 'Big'),
  ('Window Cleaning', 'Local', 'Small'),
  ('Yellow Pages Advertising', 'National', 'Big'),
  ('Security Jobs', 'National', 'Big'),
  ('Sprinkler Systems', 'Local', 'Small'),
  ('Structural Engineers', 'National', 'Big'),
  ('Surveillance Cameras', 'National', 'Big'),
  ('Surveyors', 'National', 'Big'),
  ('Time Clocks', 'Local', 'Small'),
  ('Toner Cartridges', 'National', 'Big'),
  ('Used Office Furniture', 'National', 'Big'),
  ('Utilities', 'National', 'Big'),
  ('Venetian Blinds', 'National', 'Big'),
  ('Vent A Hood', 'Local', 'Small'),
  ('Voice Recorder', 'National', 'Big'),
  ('Waste Disposal Management', 'National', 'Big'),
  ('Water', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Business Services'
ON CONFLICT DO NOTHING;

-- Construction & Tradesmen (90 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('HVAC Parts and Supplies', 'National/Local', 'Big'),
  ('Air Conditioning Installation Services', 'Local', 'Small'),
  ('Air Conditioning Units Retail', 'National', 'Big'),
  ('Aluminum Window Retailers', 'Local', 'Small'),
  ('Architectural Design Firms', 'National/Local', 'Big'),
  ('Custom Architectural Services', 'Local', 'Small'),
  ('Artificial Stone and Brick Retailers', 'Local', 'Small'),
  ('Asbestos Consulting and Inspection', 'National/Local', 'Big'),
  ('Asphalt Maintenance Services', 'Local', 'Small'),
  ('Commercial Paving Contractors', 'National/Local', 'Big'),
  ('Basement and Attic Finishing Services', 'Local', 'Small'),
  ('Backflow Testing and Installation', 'Local', 'Small'),
  ('Excavation and Bulldozer Services', 'Local', 'Small'),
  ('Basement Waterproofing Services', 'Local', 'Small'),
  ('Bathroom Renovation Contractors', 'Local', 'Small'),
  ('Bathroom Fixtures Retailers', 'National/Local', 'Big'),
  ('Boiler Services and Repair', 'Local', 'Small'),
  ('Brick and Masonry Supply Dealers', 'Local', 'Small'),
  ('Brick Paving Contractors', 'Local', 'Small'),
  ('Walkways and Patio Builders', 'Local', 'Small'),
  ('Residential Construction Services', 'Local', 'Small'),
  ('General Contracting Services', 'National/Local', 'Big'),
  ('Industrial Building Contractors', 'National', 'Big'),
  ('Building Materials and Supply Stores', 'National', 'Big'),
  ('Cabinet Retailers', 'Local', 'Small'),
  ('Cabinet Refacing and Refinishing', 'Local', 'Small'),
  ('Custom Residential Cabinet Makers', 'Local', 'Small'),
  ('Carpentry Services', 'Local', 'Small'),
  ('Carport Installation Services', 'Local', 'Small'),
  ('Tile Installation and Repair', 'Local', 'Small'),
  ('Tile Retail Stores', 'National', 'Big'),
  ('Closet Organizers and Systems', 'Local', 'Small'),
  ('Custom Closet Remodeling', 'Local', 'Small'),
  ('Commercial HVAC Installation', 'National/Local', 'Big'),
  ('Heating Contractors', 'Local', 'Small'),
  ('Brick and Masonry Dealers', 'Local', 'Small'),
  ('Concrete Supply and Delivery', 'Local', 'Small'),
  ('Concrete Cutting and Drilling Services', 'Local', 'Small'),
  ('Concrete Driveway and Sidewalk Builder', 'Local', 'Small'),
  ('Decorative Concrete Coating Services', 'Local', 'Small'),
  ('Concrete Sealing and Waterproofing', 'Local', 'Small'),
  ('Post-Construction Cleanup Services', 'Local', 'Small'),
  ('Equipment Rentals for Construction', 'National/Local', 'Big'),
  ('Construction Machinery Dealers', 'National', 'Big'),
  ('Countertop Retailers', 'Local', 'Small'),
  ('Crane Services and Rentals', 'National/Local', 'Big'),
  ('Custom Kitchen Cabinet Installers', 'Local', 'Small'),
  ('Deck Builders and Maintenance Services', 'Local', 'Small'),
  ('Decorative Concrete Specialists', 'Local', 'Small'),
  ('Residential Demolition Contractors', 'Local', 'Small'),
  ('Design and Build Services', 'National/Local', 'Big'),
  ('Excavation and Dirt Moving Contractors', 'Local', 'Small'),
  ('Door and Window Retailers', 'National', 'Big'),
  ('Glass Door Installation and Repair', 'Local', 'Small'),
  ('Door Frame Installation Services', 'Local', 'Small'),
  ('Driveway Blacktop Contractors', 'Local', 'Small'),
  ('Drywall Installation and Repair', 'Local', 'Small'),
  ('Residential Electrical Services', 'Local', 'Small'),
  ('Electric Equipment Retail Stores', 'National', 'Big'),
  ('Industrial Electrical Equipment Supplier', 'National', 'Big'),
  ('Licensed Electricians', 'Local', 'Small'),
  ('Elevator Installation Services', 'National/Local', 'Big'),
  ('Excavation Services', 'Local', 'Small'),
  ('Foundation Repair and Inspection', 'Local', 'Small'),
  ('Garage Door Installation', 'Local', 'Small'),
  ('Gutter Installation and Repairs', 'Local', 'Small'),
  ('HVAC System Repair Services', 'Local', 'Small'),
  ('Insulation Installation Services', 'Local', 'Small'),
  ('Kitchen Renovation Specialists', 'Local', 'Small'),
  ('Landscape Drainage Contractors', 'Local', 'Small'),
  ('Leak Detection and Repair Services', 'Local', 'Small'),
  ('Lighting Installation Contractors', 'Local', 'Small'),
  ('Lumber and Timber Dealers', 'National/Local', 'Big'),
  ('Masonry and Stonework Contractors', 'Local', 'Small'),
  ('Metal Roofing Installation Services', 'Local', 'Small'),
  ('Modular Building Dealers', 'National', 'Big'),
  ('Paint Stores', 'National/Local', 'Big'),
  ('Residential Painting Contractors', 'Local', 'Small'),
  ('Plumbing Equipment Wholesale Supplies', 'National', 'Big'),
  ('Pool and Spa Contractors', 'Local', 'Small'),
  ('Retaining Wall Construction', 'Local', 'Small'),
  ('Roofing Contractors', 'Local', 'Small'),
  ('Siding and Guttering Services', 'Local', 'Small'),
  ('Structural Steel Fabricators', 'National/Local', 'Big'),
  ('Tile Flooring Contractors', 'Local', 'Small'),
  ('Vinyl Window and Door Installation', 'Local', 'Small'),
  ('Water Damage Restoration Specialists', 'Local', 'Small'),
  ('Window Installation Services', 'Local', 'Small'),
  ('Woodworking and Carpentry Contractors', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Construction & Tradesmen'
ON CONFLICT DO NOTHING;

-- Legal & Financial (122 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('ATM Locations', 'Local', 'Small'),
  ('Accident & Health Insurance', 'National', 'Big'),
  ('Accident Attorneys', 'Local', 'Small'),
  ('Accountants', 'Local', 'Small'),
  ('Accounting & Tax Consultants', 'Local', 'Small'),
  ('Accounting, Auditing, & Bookkeeping', 'Local', 'Small'),
  ('Accounts Receivable Loans', 'National', 'Big'),
  ('Administrative Law Attorneys', 'Local', 'Small'),
  ('Adoption Attorneys', 'Local', 'Small'),
  ('Appeals Attorneys', 'Local', 'Small'),
  ('Appraisers', 'Local', 'Small'),
  ('Arbitration & Mediation Services', 'National/Local', 'Big'),
  ('Arbitrators', 'Local', 'Small'),
  ('Asbestos Diseases Attorneys', 'Local', 'Small'),
  ('Attorney Referral Services', 'Local', 'Small'),
  ('Auto Title Loans', 'Local', 'Small'),
  ('Bail Bonds Services', 'Local', 'Small'),
  ('Banking & Investment Law Attorneys', 'Local', 'Small'),
  ('Bankruptcy Lawyers', 'Local', 'Small'),
  ('Bankruptcy Services', 'National/Local', 'Big'),
  ('Banks', 'National', 'Big'),
  ('Bookkeeping Services', 'Local', 'Small'),
  ('Business Financing Services', 'National', 'Big'),
  ('Business Insurance Providers', 'National', 'Big'),
  ('Business Valuation Services', 'National/Local', 'Big'),
  ('Car Insurance Providers', 'National', 'Big'),
  ('Cash Advance Services', 'National', 'Big'),
  ('Certified Public Accountants (CPAs)', 'Local', 'Small'),
  ('Check Cashing Services', 'Local', 'Small'),
  ('Civil Law Attorneys', 'Local', 'Small'),
  ('Collection Agencies', 'National', 'Big'),
  ('Collection Law Attorneys', 'Local', 'Small'),
  ('Commercial Loans', 'National', 'Big'),
  ('Consumer Protection Attorneys', 'Local', 'Small'),
  ('Corporate Business Attorneys', 'National/Local', 'Big'),
  ('Court reporters', 'Local', 'Small'),
  ('Credit Card Merchant Services', 'National', 'Big'),
  ('Credit Card Services', 'National', 'Big'),
  ('Credit Reporting and Restoration Services', 'National', 'Big'),
  ('Credit Unions', 'National', 'Big'),
  ('Criminal Defense Lawyers', 'Local', 'Small'),
  ('Custody & Support Attorneys', 'Local', 'Small'),
  ('Debt Consolidation Services', 'National/Local', 'Big'),
  ('Debt Management Services', 'National', 'Big'),
  ('Disability Law Attorneys', 'Local', 'Small'),
  ('Divorce & Mediation Services', 'Local', 'Small'),
  ('Divorce Lawyers', 'Local', 'Small'),
  ('Drug Charges Attorneys', 'Local', 'Small'),
  ('DUI Attorneys', 'Local', 'Small'),
  ('Elder Law Attorneys', 'Local', 'Small'),
  ('Employee Benefits Insurance', 'National', 'Big'),
  ('Employment & Labor Law Attorneys', 'Local', 'Small'),
  ('Environmental Law Attorneys', 'Local', 'Small'),
  ('Estate Attorneys', 'Local', 'Small'),
  ('Factoring Services', 'National', 'Big'),
  ('Family Law Attorneys', 'Local', 'Small'),
  ('Financial Brokers', 'National', 'Big'),
  ('Financial Planning Services', 'National/Local', 'Big'),
  ('Financial Services Providers', 'National', 'Big'),
  ('Fire Insurance', 'National', 'Big'),
  ('Flood Insurance', 'National', 'Big'),
  ('Foreign Currency Exchange', 'National', 'Big'),
  ('Health Insurance Providers', 'National', 'Big'),
  ('Home Warranty Services', 'National', 'Big'),
  ('Immigration Law Attorneys', 'National/Local', 'Big'),
  ('Income Tax Consultants', 'Local', 'Small'),
  ('Income Tax Preparation Services', 'National', 'Big'),
  ('Insurance Adjusters', 'Local', 'Small'),
  ('Insurance Claims Services', 'National', 'Big'),
  ('Investment Advisory Services', 'National', 'Big'),
  ('Investment Securities', 'National', 'Big'),
  ('Jewelry Appraisers', 'Local', 'Small'),
  ('Juvenile Law Attorneys', 'Local', 'Small'),
  ('Landlord & Tenant Law Attorneys', 'Local', 'Small'),
  ('Lawyers', 'Local', 'Small'),
  ('Legal Assistance Services', 'National/Local', 'Big'),
  ('Legal Counsel Services', 'Local', 'Small'),
  ('Legal Forms and Supplies Retail', 'National', 'Big'),
  ('Life Insurance Providers', 'National', 'Big'),
  ('Loans', 'National', 'Big'),
  ('Malpractice Lawyers', 'Local', 'Small'),
  ('Medical Malpractice Attorneys', 'Local', 'Small'),
  ('Mortgage and Loan Banks', 'National', 'Big'),
  ('Mutual Funds and Brokers', 'National', 'Big'),
  ('Notary Public Services', 'Local', 'Small'),
  ('Paralegal Services', 'Local', 'Small'),
  ('Patent & Trademark Attorneys', 'National', 'Big'),
  ('Payroll Services and Systems', 'National', 'Big'),
  ('Personal Financial Planning', 'National/Local', 'Big'),
  ('Personal Injury Lawyers', 'Local', 'Small'),
  ('Personal Insurance Providers', 'National', 'Big'),
  ('Personal Loans', 'National/Local', 'Big'),
  ('Process Servers', 'Local', 'Small'),
  ('Product Liability Attorneys', 'Local', 'Small'),
  ('Property & Casualty Insurance', 'National', 'Big'),
  ('Public Insurance Adjusters', 'Local', 'Small'),
  ('Retirement Planning Services', 'National', 'Big'),
  ('Scholarship and Financial Aid Services', 'National', 'Big'),
  ('Sexual Abuse Attorneys', 'Local', 'Small'),
  ('Social Security Attorneys', 'National/Local', 'Big'),
  ('Stock Brokers', 'National', 'Big'),
  ('Tax Consultants', 'Local', 'Small'),
  ('Tax Preparation Services', 'National/Local', 'Big'),
  ('Traffic Law Attorneys', 'Local', 'Small'),
  ('Travel Insurance Providers', 'National', 'Big'),
  ('Trial Attorneys', 'Local', 'Small'),
  ('Workers Compensation Attorneys', 'Local', 'Small'),
  ('Workers Compensation Insurance Providers', 'National', 'Big'),
  ('Wrongful Death Attorneys', 'Local', 'Small'),
  ('Wrongful Termination Attorneys', 'Local', 'Small'),
  ('Stocks & Bonds', 'National', 'Big'),
  ('Commodity Brokers', 'National', 'Big'),
  ('Surety & Fidelity Bonds', 'National', 'Big'),
  ('Tax Lawyers', 'National', 'Big'),
  ('Tax Return Preparation & Electronic Filing', 'National', 'Big'),
  ('Tax Return Preparation Accountants', 'Local', 'Small'),
  ('Tax Returns', 'National', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Legal & Financial'
ON CONFLICT DO NOTHING;

-- I'll continue with the rest in the next insert statements to keep file manageable
-- Total so far: 92 + 70 + 109 + 90 + 122 = 483 niches
