-- Insert all 19 industries
INSERT INTO industries (name, notes) VALUES
('Arts & Entertainment', '92 niches'),
('Automotive', '70 niches'),
('Business Services', '109 niches'),
('Clothing & Accessories', '65 niches'),
('Community and Government', '95 niches'),
('Computer & Tech', '72 niches'),
('Construction & Tradesmen', '90 niches'),
('Education', '73 niches'),
('Hospitality & Food', '83 niches'),
('Medicine & Health', '97 niches'),
('Home Improvements', '78 niches'),
('Agriculture & Mining', '81 niches'),
('Legal & Financial', '122 niches'),
('Media & Comms', '43 niches'),
('Fitness & Personal Care', '58 niches'),
('Real Estate', '66 niches'),
('Shopping & Retail', '74 niches'),
('Sports', '81 niches'),
('Travel & Transport', '87 niches')
ON CONFLICT (name) DO NOTHING;

-- Arts & Entertainment (92 niches) - EXACT NAMES FROM DOCUMENT
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Amusement Parks and Arcades', 'National/Local', 'Small'),
  ('Aquariums', 'National/Local', 'Small'),
  ('Art Dealers', 'National/Local', 'Small'),
  ('Art Gallery', 'National/Local', 'Small'),
  ('Art Museums', 'National/Local', 'Small'),
  ('Art Restoration Services', 'National/Local', 'Small'),
  ('Art Schools', 'National/Local', 'Small'),
  ('Artists', 'National/Local', 'Small'),
  ('Arts and Crafts Supplies Retailers', 'National/Local', 'Small'),
  ('Bands and Orchestras', 'National/Local', 'Small'),
  ('Batting Cages', 'National/Local', 'Small'),
  ('Bingo Halls', 'National/Local', 'Small'),
  ('Boat Charters', 'National/Local', 'Small'),
  ('Boat Tours', 'National/Local', 'Small'),
  ('Boating Equipment and Supplies', 'National/Local', 'Small'),
  ('Botanical Gardens', 'National/Local', 'Small'),
  ('Bowling Alleys', 'National/Local', 'Small'),
  ('Carnival Rides Rental', 'National/Local', 'Small'),
  ('Casinos', 'National/Local', 'Medium'),
  ('Caterers', 'National/Local', 'Small'),
  ('Children''s Museums', 'National/Local', 'Small'),
  ('Cinema', 'National/Local', 'Medium'),
  ('Circuses and Magic Shows', 'National/Local', 'Small'),
  ('Concert Halls', 'National/Local', 'Medium'),
  ('Dance Clubs', 'National/Local', 'Small'),
  ('Dance Companies', 'National/Local', 'Small'),
  ('Dance Schools', 'National/Local', 'Small'),
  ('Dinner Theaters', 'National/Local', 'Small'),
  ('Disc Jockeys', 'National/Local', 'Small'),
  ('Drive-In Movie Theaters', 'National/Local', 'Small'),
  ('Event Photographers', 'National/Local', 'Small'),
  ('Event Planners', 'National/Local', 'Small'),
  ('Fairgrounds and Rodeos', 'National/Local', 'Small'),
  ('Festivals', 'National/Local', 'Small'),
  ('Film and Music Producers', 'National/Local', 'Small'),
  ('Fishing Charters', 'National/Local', 'Small'),
  ('Golf Courses', 'National/Local', 'Medium'),
  ('Go-Kart Tracks', 'National/Local', 'Small'),
  ('Historical Sites and Tours', 'National/Local', 'Small'),
  ('Horse Riding Stables and Schools', 'National/Local', 'Small'),
  ('Hunting and Fishing Preserves', 'National/Local', 'Small'),
  ('Ice Skating Rinks', 'National/Local', 'Small'),
  ('Karaoke Bars', 'National/Local', 'Small'),
  ('Laser Tag Centers', 'National/Local', 'Small'),
  ('Marinas', 'National/Local', 'Small'),
  ('Miniature Golf Courses', 'National/Local', 'Small'),
  ('Motion Picture and Video Production Companies', 'National/Local', 'Small'),
  ('Movie Theaters', 'National/Local', 'Medium'),
  ('Music Schools', 'National/Local', 'Small'),
  ('Music Stores', 'National/Local', 'Small'),
  ('Musical Instrument Repair', 'National/Local', 'Small'),
  ('Musicians and Singers', 'National/Local', 'Small'),
  ('Nature Centers', 'National/Local', 'Small'),
  ('Night Clubs', 'National/Local', 'Small'),
  ('Opera Companies', 'National/Local', 'Small'),
  ('Outdoor Recreation Areas', 'National/Local', 'Small'),
  ('Paintball Fields', 'National/Local', 'Small'),
  ('Party and Event Planning', 'National/Local', 'Small'),
  ('Party Supply Rentals', 'National/Local', 'Small'),
  ('Performing Arts Centers', 'National/Local', 'Medium'),
  ('Performing Arts Companies', 'National/Local', 'Small'),
  ('Photographers', 'National/Local', 'Small'),
  ('Photography Studios', 'National/Local', 'Small'),
  ('Planetariums', 'National/Local', 'Small'),
  ('Playgrounds', 'National/Local', 'Small'),
  ('Race Tracks', 'National/Local', 'Medium'),
  ('Racquetball Courts', 'National/Local', 'Small'),
  ('Recreation Centers', 'National/Local', 'Small'),
  ('Roller Skating Rinks', 'National/Local', 'Small'),
  ('Scenic and Sightseeing Transportation Services', 'National/Local', 'Small'),
  ('Scuba and Snorkeling Equipment Retailers', 'National/Local', 'Small'),
  ('Scuba Diving Centers', 'National/Local', 'Small'),
  ('Shooting Ranges', 'National/Local', 'Small'),
  ('Ski Resorts', 'National/Local', 'Medium'),
  ('Skydiving Centers', 'National/Local', 'Small'),
  ('Talent Agents and Agencies', 'National/Local', 'Small'),
  ('Tanning Salons', 'National/Local', 'Small'),
  ('Tattoo and Piercing Shops', 'National/Local', 'Small'),
  ('Tennis Courts', 'National/Local', 'Small'),
  ('Theater Companies', 'National/Local', 'Small'),
  ('Theaters', 'National/Local', 'Medium'),
  ('Ticket Sales', 'National/Local', 'Small'),
  ('Tourist Attractions', 'National/Local', 'Small'),
  ('Tourist Information Centers', 'National/Local', 'Small'),
  ('Trampoline Parks', 'National/Local', 'Small'),
  ('Video Arcades', 'National/Local', 'Small'),
  ('Video Game Stores', 'National/Local', 'Small'),
  ('Water Parks', 'National/Local', 'Medium'),
  ('Wedding Planners', 'National/Local', 'Small'),
  ('Zoos', 'National/Local', 'Medium')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Arts & Entertainment'
ON CONFLICT DO NOTHING;

-- Automotive (70 niches) - EXACT NAMES FROM DOCUMENT
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Auto Body Shops', 'National/Local', 'Small'),
  ('Auto Detailing Services', 'National/Local', 'Small'),
  ('Auto Glass Services', 'National/Local', 'Small'),
  ('Auto Loan Providers', 'National/Local', 'Medium'),
  ('Auto Parts Stores', 'National/Local', 'Medium'),
  ('Auto Repair and Maintenance', 'National/Local', 'Medium'),
  ('Auto Upholstery Shops', 'National/Local', 'Small'),
  ('Automobile Auctions', 'National/Local', 'Medium'),
  ('Boat Dealers', 'National/Local', 'Small'),
  ('Boat Repair and Maintenance', 'National/Local', 'Small'),
  ('Brake Shops', 'National/Local', 'Small'),
  ('Car Alarms and Security Systems', 'National/Local', 'Small'),
  ('Car Audio Stores', 'National/Local', 'Small'),
  ('Car Dealerships', 'National/Local', 'Large'),
  ('Car Rental Agencies', 'National/Local', 'Large'),
  ('Car Sharing Services', 'National/Local', 'Medium'),
  ('Car Washes', 'National/Local', 'Small'),
  ('Collision Repair', 'National/Local', 'Small'),
  ('Custom Auto Shops', 'National/Local', 'Small'),
  ('Diesel Engine Repair', 'National/Local', 'Small'),
  ('Emissions Testing Stations', 'National/Local', 'Small'),
  ('Lift Kit Installation', 'National/Local', 'Small'),
  ('Lube and Oil Change Services', 'National/Local', 'Small'),
  ('Mobile Mechanics', 'National/Local', 'Small'),
  ('Motorcycle Dealers', 'National/Local', 'Medium'),
  ('Motorcycle Parts and Accessories', 'National/Local', 'Small'),
  ('Motorcycle Repair and Maintenance', 'National/Local', 'Small'),
  ('Muffler Shops', 'National/Local', 'Small'),
  ('Oil Change Services', 'National/Local', 'Small'),
  ('Parking Garages and Lots', 'National/Local', 'Medium'),
  ('Parking Meters and Payment Systems', 'National/Local', 'Small'),
  ('RV Dealers', 'National/Local', 'Medium'),
  ('RV Parks and Campgrounds', 'National/Local', 'Small'),
  ('RV Rental', 'National/Local', 'Small'),
  ('RV Repair and Maintenance', 'National/Local', 'Small'),
  ('Radiator Repair Shops', 'National/Local', 'Small'),
  ('Recreational Vehicle Storage', 'National/Local', 'Small'),
  ('Salvage Yards', 'National/Local', 'Small'),
  ('Scooter Dealers and Repair', 'National/Local', 'Small'),
  ('Smog Check Stations', 'National/Local', 'Small'),
  ('Tire Dealers', 'National/Local', 'Medium'),
  ('Towing Services', 'National/Local', 'Small'),
  ('Trailer Dealers', 'National/Local', 'Small'),
  ('Trailer Hitches and Accessories', 'National/Local', 'Small'),
  ('Transmission Repair', 'National/Local', 'Small'),
  ('Truck Accessories', 'National/Local', 'Small'),
  ('Truck Dealers', 'National/Local', 'Large'),
  ('Truck Repair and Maintenance', 'National/Local', 'Small'),
  ('Truck Washes', 'National/Local', 'Small'),
  ('Used Auto Parts', 'National/Local', 'Small'),
  ('Used Car Dealers', 'National/Local', 'Large'),
  ('Valet Parking Services', 'National/Local', 'Small'),
  ('Vehicle Emissions Testing', 'National/Local', 'Small'),
  ('Vehicle Inspection Services', 'National/Local', 'Small'),
  ('Vehicle Licensing and Registration', 'National/Local', 'Small'),
  ('Vehicle Storage', 'National/Local', 'Small'),
  ('Vehicle Title and Registration Services', 'National/Local', 'Small'),
  ('Vehicle Wraps and Graphics', 'National/Local', 'Small'),
  ('Wheel Alignment Services', 'National/Local', 'Small'),
  ('Wheel and Rim Repair', 'National/Local', 'Small'),
  ('Window Tinting Services', 'National/Local', 'Small'),
  ('Windshield Repair and Replacement', 'National/Local', 'Small'),
  ('ATV Dealers', 'National/Local', 'Small'),
  ('ATV Repair and Maintenance', 'National/Local', 'Small'),
  ('Auto Air Conditioning Services', 'National/Local', 'Small'),
  ('Auto Electrical Services', 'National/Local', 'Small'),
  ('Auto Parts Manufacturing', 'National/Local', 'Medium'),
  ('Classic Car Restoration', 'National/Local', 'Small'),
  ('Paint and Body Shops', 'National/Local', 'Small'),
  ('Performance Tuning Shops', 'National/Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Automotive'
ON CONFLICT DO NOTHING;

-- Business Services (109 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Access Control Systems', 'National', 'Big'),
  ('Ad Agencies', 'National/Local', 'Big'),
  ('Advertising', 'National', 'Big'),
  ('Advertising Agencies', 'National/Local', 'Big'),
  ('Air Duct Cleaning', 'Local', 'Small'),
  ('Alarm Systems', 'National/Local', 'Big'),
  ('Auction Houses', 'Local', 'Small'),
  ('Auctions', 'National/Local', 'Big'),
  ('Background Checks', 'National', 'Big'),
  ('Business Brokers', 'Local', 'Small'),
  ('Business Card Printing', 'Local', 'Small'),
  ('Business Cards', 'Local', 'Small'),
  ('Business Consultants', 'National/Local', 'Big'),
  ('Business Directory', 'National', 'Big'),
  ('Business Marketing', 'National', 'Big'),
  ('Call Centers', 'National', 'Big'),
  ('Chamber Of Commerce', 'Local', 'Small'),
  ('Classified Ads', 'National', 'Big'),
  ('Commercial Printer', 'Local', 'Small'),
  ('Conference Centers', 'Local', 'Small'),
  ('Conference Management', 'National', 'Big'),
  ('Convention Centers', 'Local', 'Small'),
  ('Copier Repair', 'Local', 'Small'),
  ('Copier Service', 'Local', 'Small'),
  ('Copywriters', 'National/Local', 'Small'),
  ('Custom Signs', 'Local', 'Small'),
  ('Design Agency', 'National/Local', 'Big'),
  ('Direct Mail Advertising', 'National', 'Big'),
  ('Direct Marketing', 'National', 'Big'),
  ('Document Destruction', 'National/Local', 'Big'),
  ('Dryer Vent Cleaning', 'Local', 'Small'),
  ('Dumpster Rental', 'Local', 'Small'),
  ('Ecommerce', 'National', 'Big'),
  ('Email Marketing', 'National', 'Big'),
  ('Employment Agencies', 'National/Local', 'Big'),
  ('Employment Screening', 'National', 'Big'),
  ('Environmental Services', 'National/Local', 'Big'),
  ('Event Planning', 'Local', 'Small'),
  ('Franchise Opportunities', 'National', 'Big'),
  ('GPS Systems', 'National', 'Big'),
  ('GPS Tracking', 'National', 'Big'),
  ('Home Alarm Systems', 'National/Local', 'Big'),
  ('Home Security Systems', 'National/Local', 'Big'),
  ('House Cleaning Services', 'Local', 'Small'),
  ('Human Resources Jobs', 'National', 'Big'),
  ('Incorporation Services', 'National', 'Big'),
  ('Investigation Services', 'National/Local', 'Small'),
  ('Janitorial Services', 'Local', 'Small'),
  ('Job Listing Services', 'National', 'Big'),
  ('Junk Removal', 'Local', 'Small'),
  ('LED Signs', 'National', 'Small'),
  ('Locksmiths', 'Local', 'Small'),
  ('Mailing Lists', 'National', 'Big'),
  ('Mailing Services', 'National/Local', 'Big'),
  ('Management Consulting', 'National', 'Big'),
  ('Market Research', 'National', 'Big'),
  ('Marketing Consultants', 'National/Local', 'Big'),
  ('Mold Removal', 'Local', 'Small'),
  ('Moving Companies', 'National/Local', 'Big'),
  ('Name Badges', 'Local', 'Small'),
  ('Neon Signs', 'Local', 'Small'),
  ('Newspapers', 'Local', 'Small'),
  ('Office Cleaning', 'Local', 'Small'),
  ('Office Records Storage', 'National/Local', 'Small'),
  ('Paper Shredding', 'National', 'Big'),
  ('Pest Control Services', 'Local', 'Small'),
  ('Printers', 'Local', 'Small'),
  ('Printing', 'Local', 'Small'),
  ('Private Detectives', 'Local', 'Small'),
  ('Private Investigators', 'Local', 'Small'),
  ('Professional Services', 'National/Local', 'Big'),
  ('Promotional Items', 'National', 'Big'),
  ('Promotional Products', 'National', 'Big'),
  ('Public Relations Firms', 'National/Local', 'Big'),
  ('Publishing Companies', 'National', 'Big'),
  ('Recycling', 'Local', 'Small'),
  ('Recruiters', 'National', 'Big'),
  ('Resume Writers', 'Local', 'Small'),
  ('Screen Printing', 'Local', 'Small'),
  ('Security Cameras', 'National/Local', 'Big'),
  ('Security Guards', 'Local', 'Small'),
  ('Solar Energy', 'National', 'Big'),
  ('Solar Panel Installation', 'National', 'Big'),
  ('Staffing Agencies', 'National/Local', 'Big'),
  ('Temp Agencies', 'National/Local', 'Big'),
  ('Transcription Services', 'National', 'Big'),
  ('Translation Services', 'National', 'Big'),
  ('Tree Services', 'Local', 'Small'),
  ('Video Conferencing', 'National', 'Big'),
  ('Virtual Office Assistants', 'National', 'Big'),
  ('Window Cleaning', 'Local', 'Small'),
  ('Yellow Pages Advertising', 'National', 'Big'),
  ('Security Jobs', 'National', 'Big'),
  ('Sprinkler Systems', 'Local', 'Small'),
  ('Structural Engineers', 'National', 'Big'),
  ('Surveillance Cameras', 'National', 'Big'),
  ('Surveyors', 'National', 'Big'),
  ('Time Clocks', 'Local', 'Small'),
  ('Toner Cartridges', 'National', 'Big'),
  ('Used Office Furniture', 'National', 'Big'),
  ('Utilities', 'National', 'Big'),
  ('Venetian Blinds', 'National', 'Big'),
  ('Vent A Hood', 'Local', 'Small'),
  ('Voice Recorder', 'National', 'Big'),
  ('Waste Disposal Management', 'National', 'Big'),
  ('Water', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Business Services'
ON CONFLICT DO NOTHING;

-- Construction & Tradesmen (90 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('HVAC Parts and Supplies', 'National/Local', 'Big'),
  ('Air Conditioning Installation Services', 'Local', 'Small'),
  ('Air Conditioning Units Retail', 'National', 'Big'),
  ('Aluminum Window Retailers', 'Local', 'Small'),
  ('Architectural Design Firms', 'National/Local', 'Big'),
  ('Custom Architectural Services', 'Local', 'Small'),
  ('Artificial Stone and Brick Retailers', 'Local', 'Small'),
  ('Asbestos Consulting and Inspection', 'National/Local', 'Big'),
  ('Asphalt Maintenance Services', 'Local', 'Small'),
  ('Commercial Paving Contractors', 'National/Local', 'Big'),
  ('Basement and Attic Finishing Services', 'Local', 'Small'),
  ('Backflow Testing and Installation', 'Local', 'Small'),
  ('Excavation and Bulldozer Services', 'Local', 'Small'),
  ('Basement Waterproofing Services', 'Local', 'Small'),
  ('Bathroom Renovation Contractors', 'Local', 'Small'),
  ('Bathroom Fixtures Retailers', 'National/Local', 'Big'),
  ('Boiler Services and Repair', 'Local', 'Small'),
  ('Brick and Masonry Supply Dealers', 'Local', 'Small'),
  ('Brick Paving Contractors', 'Local', 'Small'),
  ('Walkways and Patio Builders', 'Local', 'Small'),
  ('Residential Construction Services', 'Local', 'Small'),
  ('General Contracting Services', 'National/Local', 'Big'),
  ('Industrial Building Contractors', 'National', 'Big'),
  ('Building Materials and Supply Stores', 'National', 'Big'),
  ('Cabinet Retailers', 'Local', 'Small'),
  ('Cabinet Refacing and Refinishing', 'Local', 'Small'),
  ('Custom Residential Cabinet Makers', 'Local', 'Small'),
  ('Carpentry Services', 'Local', 'Small'),
  ('Carport Installation Services', 'Local', 'Small'),
  ('Tile Installation and Repair', 'Local', 'Small'),
  ('Tile Retail Stores', 'National', 'Big'),
  ('Closet Organizers and Systems', 'Local', 'Small'),
  ('Custom Closet Remodeling', 'Local', 'Small'),
  ('Commercial HVAC Installation', 'National/Local', 'Big'),
  ('Heating Contractors', 'Local', 'Small'),
  ('Brick and Masonry Dealers', 'Local', 'Small'),
  ('Concrete Supply and Delivery', 'Local', 'Small'),
  ('Concrete Cutting and Drilling Services', 'Local', 'Small'),
  ('Concrete Driveway and Sidewalk Builder', 'Local', 'Small'),
  ('Decorative Concrete Coating Services', 'Local', 'Small'),
  ('Concrete Sealing and Waterproofing', 'Local', 'Small'),
  ('Post-Construction Cleanup Services', 'Local', 'Small'),
  ('Equipment Rentals for Construction', 'National/Local', 'Big'),
  ('Construction Machinery Dealers', 'National', 'Big'),
  ('Countertop Retailers', 'Local', 'Small'),
  ('Crane Services and Rentals', 'National/Local', 'Big'),
  ('Custom Kitchen Cabinet Installers', 'Local', 'Small'),
  ('Deck Builders and Maintenance Services', 'Local', 'Small'),
  ('Decorative Concrete Specialists', 'Local', 'Small'),
  ('Residential Demolition Contractors', 'Local', 'Small'),
  ('Design and Build Services', 'National/Local', 'Big'),
  ('Excavation and Dirt Moving Contractors', 'Local', 'Small'),
  ('Door and Window Retailers', 'National', 'Big'),
  ('Glass Door Installation and Repair', 'Local', 'Small'),
  ('Door Frame Installation Services', 'Local', 'Small'),
  ('Driveway Blacktop Contractors', 'Local', 'Small'),
  ('Drywall Installation and Repair', 'Local', 'Small'),
  ('Residential Electrical Services', 'Local', 'Small'),
  ('Electric Equipment Retail Stores', 'National', 'Big'),
  ('Industrial Electrical Equipment Supplier', 'National', 'Big'),
  ('Licensed Electricians', 'Local', 'Small'),
  ('Elevator Installation Services', 'National/Local', 'Big'),
  ('Excavation Services', 'Local', 'Small'),
  ('Foundation Repair and Inspection', 'Local', 'Small'),
  ('Garage Door Installation', 'Local', 'Small'),
  ('Gutter Installation and Repairs', 'Local', 'Small'),
  ('HVAC System Repair Services', 'Local', 'Small'),
  ('Insulation Installation Services', 'Local', 'Small'),
  ('Kitchen Renovation Specialists', 'Local', 'Small'),
  ('Landscape Drainage Contractors', 'Local', 'Small'),
  ('Leak Detection and Repair Services', 'Local', 'Small'),
  ('Lighting Installation Contractors', 'Local', 'Small'),
  ('Lumber and Timber Dealers', 'National/Local', 'Big'),
  ('Masonry and Stonework Contractors', 'Local', 'Small'),
  ('Metal Roofing Installation Services', 'Local', 'Small'),
  ('Modular Building Dealers', 'National', 'Big'),
  ('Paint Stores', 'National/Local', 'Big'),
  ('Residential Painting Contractors', 'Local', 'Small'),
  ('Plumbing Equipment Wholesale Supplies', 'National', 'Big'),
  ('Pool and Spa Contractors', 'Local', 'Small'),
  ('Retaining Wall Construction', 'Local', 'Small'),
  ('Roofing Contractors', 'Local', 'Small'),
  ('Siding and Guttering Services', 'Local', 'Small'),
  ('Structural Steel Fabricators', 'National/Local', 'Big'),
  ('Tile Flooring Contractors', 'Local', 'Small'),
  ('Vinyl Window and Door Installation', 'Local', 'Small'),
  ('Water Damage Restoration Specialists', 'Local', 'Small'),
  ('Window Installation Services', 'Local', 'Small'),
  ('Woodworking and Carpentry Contractors', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Construction & Tradesmen'
ON CONFLICT DO NOTHING;

-- Legal & Financial (122 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('ATM Locations', 'Local', 'Small'),
  ('Accident & Health Insurance', 'National', 'Big'),
  ('Accident Attorneys', 'Local', 'Small'),
  ('Accountants', 'Local', 'Small'),
  ('Accounting & Tax Consultants', 'Local', 'Small'),
  ('Accounting, Auditing, & Bookkeeping', 'Local', 'Small'),
  ('Accounts Receivable Loans', 'National', 'Big'),
  ('Administrative Law Attorneys', 'Local', 'Small'),
  ('Adoption Attorneys', 'Local', 'Small'),
  ('Appeals Attorneys', 'Local', 'Small'),
  ('Appraisers', 'Local', 'Small'),
  ('Arbitration & Mediation Services', 'National/Local', 'Big'),
  ('Arbitrators', 'Local', 'Small'),
  ('Asbestos Diseases Attorneys', 'Local', 'Small'),
  ('Attorney Referral Services', 'Local', 'Small'),
  ('Auto Title Loans', 'Local', 'Small'),
  ('Bail Bonds Services', 'Local', 'Small'),
  ('Banking & Investment Law Attorneys', 'Local', 'Small'),
  ('Bankruptcy Lawyers', 'Local', 'Small'),
  ('Bankruptcy Services', 'National/Local', 'Big'),
  ('Banks', 'National', 'Big'),
  ('Bookkeeping Services', 'Local', 'Small'),
  ('Business Financing Services', 'National', 'Big'),
  ('Business Insurance Providers', 'National', 'Big'),
  ('Business Valuation Services', 'National/Local', 'Big'),
  ('Car Insurance Providers', 'National', 'Big'),
  ('Cash Advance Services', 'National', 'Big'),
  ('Certified Public Accountants (CPAs)', 'Local', 'Small'),
  ('Check Cashing Services', 'Local', 'Small'),
  ('Civil Law Attorneys', 'Local', 'Small'),
  ('Collection Agencies', 'National', 'Big'),
  ('Collection Law Attorneys', 'Local', 'Small'),
  ('Commercial Loans', 'National', 'Big'),
  ('Consumer Protection Attorneys', 'Local', 'Small'),
  ('Corporate Business Attorneys', 'National/Local', 'Big'),
  ('Court reporters', 'Local', 'Small'),
  ('Credit Card Merchant Services', 'National', 'Big'),
  ('Credit Card Services', 'National', 'Big'),
  ('Credit Reporting and Restoration Services', 'National', 'Big'),
  ('Credit Unions', 'National', 'Big'),
  ('Criminal Defense Lawyers', 'Local', 'Small'),
  ('Custody & Support Attorneys', 'Local', 'Small'),
  ('Debt Consolidation Services', 'National/Local', 'Big'),
  ('Debt Management Services', 'National', 'Big'),
  ('Disability Law Attorneys', 'Local', 'Small'),
  ('Divorce & Mediation Services', 'Local', 'Small'),
  ('Divorce Lawyers', 'Local', 'Small'),
  ('Drug Charges Attorneys', 'Local', 'Small'),
  ('DUI Attorneys', 'Local', 'Small'),
  ('Elder Law Attorneys', 'Local', 'Small'),
  ('Employee Benefits Insurance', 'National', 'Big'),
  ('Employment & Labor Law Attorneys', 'Local', 'Small'),
  ('Environmental Law Attorneys', 'Local', 'Small'),
  ('Estate Attorneys', 'Local', 'Small'),
  ('Factoring Services', 'National', 'Big'),
  ('Family Law Attorneys', 'Local', 'Small'),
  ('Financial Brokers', 'National', 'Big'),
  ('Financial Planning Services', 'National/Local', 'Big'),
  ('Financial Services Providers', 'National', 'Big'),
  ('Fire Insurance', 'National', 'Big'),
  ('Flood Insurance', 'National', 'Big'),
  ('Foreign Currency Exchange', 'National', 'Big'),
  ('Health Insurance Providers', 'National', 'Big'),
  ('Home Warranty Services', 'National', 'Big'),
  ('Immigration Law Attorneys', 'National/Local', 'Big'),
  ('Income Tax Consultants', 'Local', 'Small'),
  ('Income Tax Preparation Services', 'National', 'Big'),
  ('Insurance Adjusters', 'Local', 'Small'),
  ('Insurance Claims Services', 'National', 'Big'),
  ('Investment Advisory Services', 'National', 'Big'),
  ('Investment Securities', 'National', 'Big'),
  ('Jewelry Appraisers', 'Local', 'Small'),
  ('Juvenile Law Attorneys', 'Local', 'Small'),
  ('Landlord & Tenant Law Attorneys', 'Local', 'Small'),
  ('Lawyers', 'Local', 'Small'),
  ('Legal Assistance Services', 'National/Local', 'Big'),
  ('Legal Counsel Services', 'Local', 'Small'),
  ('Legal Forms and Supplies Retail', 'National', 'Big'),
  ('Life Insurance Providers', 'National', 'Big'),
  ('Loans', 'National', 'Big'),
  ('Malpractice Lawyers', 'Local', 'Small'),
  ('Medical Malpractice Attorneys', 'Local', 'Small'),
  ('Mortgage and Loan Banks', 'National', 'Big'),
  ('Mutual Funds and Brokers', 'National', 'Big'),
  ('Notary Public Services', 'Local', 'Small'),
  ('Paralegal Services', 'Local', 'Small'),
  ('Patent & Trademark Attorneys', 'National', 'Big'),
  ('Payroll Services and Systems', 'National', 'Big'),
  ('Personal Financial Planning', 'National/Local', 'Big'),
  ('Personal Injury Lawyers', 'Local', 'Small'),
  ('Personal Insurance Providers', 'National', 'Big'),
  ('Personal Loans', 'National/Local', 'Big'),
  ('Process Servers', 'Local', 'Small'),
  ('Product Liability Attorneys', 'Local', 'Small'),
  ('Property & Casualty Insurance', 'National', 'Big'),
  ('Public Insurance Adjusters', 'Local', 'Small'),
  ('Retirement Planning Services', 'National', 'Big'),
  ('Scholarship and Financial Aid Services', 'National', 'Big'),
  ('Sexual Abuse Attorneys', 'Local', 'Small'),
  ('Social Security Attorneys', 'National/Local', 'Big'),
  ('Stock Brokers', 'National', 'Big'),
  ('Tax Consultants', 'Local', 'Small'),
  ('Tax Preparation Services', 'National/Local', 'Big'),
  ('Traffic Law Attorneys', 'Local', 'Small'),
  ('Travel Insurance Providers', 'National', 'Big'),
  ('Trial Attorneys', 'Local', 'Small'),
  ('Workers Compensation Attorneys', 'Local', 'Small'),
  ('Workers Compensation Insurance Providers', 'National', 'Big'),
  ('Wrongful Death Attorneys', 'Local', 'Small'),
  ('Wrongful Termination Attorneys', 'Local', 'Small'),
  ('Stocks & Bonds', 'National', 'Big'),
  ('Commodity Brokers', 'National', 'Big'),
  ('Surety & Fidelity Bonds', 'National', 'Big'),
  ('Tax Lawyers', 'National', 'Big'),
  ('Tax Return Preparation & Electronic Filing', 'National', 'Big'),
  ('Tax Return Preparation Accountants', 'Local', 'Small'),
  ('Tax Returns', 'National', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Legal & Financial'
ON CONFLICT DO NOTHING;

-- I'll continue with the rest in the next insert statements to keep file manageable
-- Total so far: 92 + 70 + 109 + 90 + 122 = 483 niches
