-- Insert Industries and Niches - Part 2
-- Automotive (70 niches)

-- Insert Automotive Industry
INSERT INTO industries (name, description, sort_order)
VALUES ('Automotive', 'Vehicle sales, service, and automotive services', 3)
ON CONFLICT (name) DO NOTHING;

-- Insert Automotive Niches (70 niches)
INSERT INTO niches (industry_id, name, scale, estimated_database_size) VALUES
((SELECT id FROM industries WHERE name = 'Automotive'), 'New Car Dealers', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Used Car Dealers', 'National/Local', 40000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Recreational Vehicle Dealers', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Motorcycle Dealers', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Boat Dealers', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Parts and Accessories Stores', 'National/Local', 30000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Tire Dealers', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Oil Change and Lubrication Shops', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Car Washes', 'National/Local', 30000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Repair and Maintenance', 'National/Local', 80000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Body and Paint Shops', 'National/Local', 35000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Glass Replacement Shops', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Transmission Repair', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Exhaust System Repair', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Other Automotive Mechanical and Electrical Repair', 'National/Local', 40000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Parking Lots and Garages', 'National/Local', 20000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Equipment Rental and Leasing', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Truck Rental and Leasing', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Passenger Car Rental', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Towing Services', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'All Other Automotive Repair and Maintenance', 'National/Local', 35000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Battery Stores', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Upholstery and Interior Repair', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Customization', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Auto Detailing', 'National/Local', 25000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Window Tinting', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Sound System Installation', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Alarm and Security Installation', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Windshield Repair', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Dent and Scratch Removal', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Mobile Auto Repair', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Mobile Oil Change Services', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Diesel Engine Repair', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Truck and Bus Body Repair', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Wheel Alignment and Balancing', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Brake Repair', 'National/Local', 18000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Air Conditioning Repair', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Muffler Repair', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Radiator Repair', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Tune-Up Services', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Smog and Emissions Testing', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Vehicle Inspection Services', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Classic and Antique Car Restoration', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Performance Tuning and Modification', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Race Car Preparation', 'National/Local', 2000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Paint Protection Film Installation', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Vehicle Wrap and Graphics', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Locksmith Services', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Key Cutting and Programming', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Fleet Maintenance Services', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Truck Cap and Tonneau Cover Installation', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Lift Kit Installation', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Trailer Hitch Installation', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Running Board and Step Installation', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Headlight Restoration', 'National/Local', 6000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Automotive Ceramic Coating', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'PDR (Paintless Dent Repair)', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Motorcycle Repair and Maintenance', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'ATV and Off-Road Vehicle Repair', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Snowmobile Repair', 'Local', 3000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Golf Cart Sales and Service', 'National/Local', 5000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Marine Engine Repair', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Jet Ski Repair', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'RV Repair and Service', 'National/Local', 12000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'RV Storage', 'National/Local', 8000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Boat Storage', 'National/Local', 10000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Vehicle Storage', 'National/Local', 15000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Auto Auction Services', 'National/Local', 3000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Vehicle Appraisal Services', 'National/Local', 4000),
((SELECT id FROM industries WHERE name = 'Automotive'), 'Pre-Purchase Vehicle Inspection', 'National/Local', 5000);
