-- Home Improvements (78 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Interior Designers and Decorators', 'Local', 'Small'),
  ('Adjustable Bed Retailers', 'National', 'Big'),
  ('Air Purification Equipment Dealers', 'National', 'Big'),
  ('Air Conditioning Repair Services', 'Local', 'Small'),
  ('Air Duct Cleaning Services', 'Local', 'Small'),
  ('Alarm Installation Services', 'National/Local', 'Big'),
  ('Home Security System Dealers', 'National', 'Big'),
  ('Animal Shelters', 'Local', 'Small'),
  ('Wildlife Trapping Services', 'Local', 'Small'),
  ('Antique Dealers', 'Local', 'Small'),
  ('Appliance Retail Stores', 'National', 'Big'),
  ('Appliance Parts Suppliers', 'National', 'Big'),
  ('Appliance Repair Services', 'Local', 'Small'),
  ('Aquarium Retail and Supplies', 'Local', 'Small'),
  ('Tree Care Specialists (Arborists)', 'Local', 'Small'),
  ('Awnings and Shade Structures Retail', 'Local', 'Small'),
  ('Baby Furniture Stores', 'Local', 'Small'),
  ('Babysitting Services', 'Local', 'Small'),
  ('Bamboo and Wicker Furniture Retail', 'Local', 'Small'),
  ('Bar Stool Retailers', 'Local', 'Small'),
  ('BBQ Equipment and Supplies', 'Local', 'Small'),
  ('Bathtub Repair and Refinishing Services', 'Local', 'Small'),
  ('Bathtub Retailers', 'Local', 'Small'),
  ('Bedding Stores', 'National/Local', 'Big'),
  ('Bedroom Furniture Retailers', 'National/Local', 'Big'),
  ('Bed Retailers', 'National/Local', 'Big'),
  ('Bee Control Services', 'Local', 'Small'),
  ('Bird Supplies Retail', 'Local', 'Small'),
  ('Blinds Installation and Repair Services', 'Local', 'Small'),
  ('Custom Blinds Retail', 'Local', 'Small'),
  ('Home Burglar Alarm Installation', 'Local', 'Small'),
  ('Cable TV Providers', 'National', 'Big'),
  ('Carpet Cleaning Services', 'Local', 'Small'),
  ('Carpet Installation Services', 'Local', 'Small'),
  ('Carpet Retail Stores', 'National/Local', 'Big'),
  ('Rug and Upholstery Repair Services', 'Local', 'Small'),
  ('Ceiling Fan Retailers', 'Local', 'Small'),
  ('Children''s Furniture Retailers', 'Local', 'Small'),
  ('Chimney Cleaning Services', 'Local', 'Small'),
  ('Cleaning Equipment Retail', 'National', 'Big'),
  ('Home Cleaning Services', 'Local', 'Small'),
  ('Security Camera Installation', 'National/Local', 'Big'),
  ('Contemporary Furniture Stores', 'Local', 'Small'),
  ('Decorative Concrete Specialists', 'Local', 'Small'),
  ('Dinette Set Retailers', 'Local', 'Small'),
  ('Dishwasher Sales and Service', 'Local', 'Small'),
  ('Pet Grooming and Boarding Services', 'Local', 'Small'),
  ('Pet Supplies and Accessories', 'National/Local', 'Big'),
  ('Dog Training Services', 'Local', 'Small'),
  ('Domestic Cleaning Services', 'Local', 'Small'),
  ('Garage Door Repair Services', 'Local', 'Small'),
  ('Garden Centers', 'Local', 'Small'),
  ('Landscapers', 'Local', 'Small'),
  ('Lawn Care Services', 'Local', 'Small'),
  ('Lighting Retail Stores', 'National/Local', 'Big'),
  ('Locksmith Services', 'Local', 'Small'),
  ('Major Appliance Dealers', 'National/Local', 'Big'),
  ('Mattresses Retail', 'National/Local', 'Big'),
  ('Nurseries and Plant Retailers', 'Local', 'Small'),
  ('Outdoor Furniture Retailers', 'National/Local', 'Big'),
  ('Pest Control Services', 'Local', 'Small'),
  ('Pet Shops', 'Local', 'Small'),
  ('Plumbers', 'Local', 'Small'),
  ('Pool Maintenance Services', 'Local', 'Small'),
  ('Recycling Centers', 'Local', 'Small'),
  ('Residential Painting Services', 'Local', 'Small'),
  ('Security Equipment Retailers', 'National', 'Big'),
  ('Self-Service Laundries', 'Local', 'Small'),
  ('Swimming Pool Contractors', 'Local', 'Small'),
  ('Tile Retailers', 'National/Local', 'Big'),
  ('Tree Removal Services', 'Local', 'Small'),
  ('Tree Trimming Services', 'Local', 'Small'),
  ('Used Furniture Stores', 'Local', 'Small'),
  ('Vacuum Cleaner Sales and Service', 'Local', 'Small'),
  ('Wallpaper Installation Services', 'Local', 'Small'),
  ('Window Cleaning Services', 'Local', 'Small'),
  ('Window Covering Retail', 'National/Local', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Home Improvements'
ON CONFLICT DO NOTHING;

-- Medicine & Health (97 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Abortion Clinics', 'Local', 'Small'),
  ('Abortion Information Services', 'Local', 'Small'),
  ('Acupuncture and Acupressure Clinics', 'Local', 'Small'),
  ('Addiction Treatment Centers', 'National/Local', 'Big'),
  ('Air Ambulance Services', 'National', 'Big'),
  ('Alcoholics Anonymous Groups', 'Local', 'Small'),
  ('Allergy and Immunology Physicians', 'Local', 'Small'),
  ('Alternative Medicine Practitioners', 'Local', 'Small'),
  ('Animal Health Services', 'Local', 'Small'),
  ('Veterinary Hospitals', 'Local', 'Small'),
  ('Anti-Aging Specialists', 'National/Local', 'Big'),
  ('Audiologists and Hearing Specialists', 'Local', 'Small'),
  ('Water Filtration and Purification Services', 'National', 'Big'),
  ('Bariatric Physicians', 'National/Local', 'Big'),
  ('Blood Banks', 'National/Local', 'Big'),
  ('Blood Testing Services', 'Local', 'Small'),
  ('Cancer Support and Referral Services', 'National/Local', 'Big'),
  ('Cardiologists', 'Local', 'Small'),
  ('Cemeteries and Memorial Parks', 'Local', 'Small'),
  ('Chiropractic Clinics', 'Local', 'Small'),
  ('Chiropractors', 'Local', 'Small'),
  ('General Health Clinics', 'Local', 'Small'),
  ('Colon Hydrotherapy', 'Local', 'Small'),
  ('Contact Lens Retailers', 'National/Local', 'Big'),
  ('Pediatric Cosmetic Surgeons', 'National', 'Big'),
  ('Cosmetic Dentists', 'Local', 'Small'),
  ('Cremation Services', 'Local', 'Small'),
  ('Cremation Urns Retail', 'National', 'Big'),
  ('Dental Clinics', 'Local', 'Small'),
  ('Dental Implant Specialists', 'National/Local', 'Big'),
  ('Dental Referral Services', 'National', 'Big'),
  ('Dental Insurance Providers', 'National', 'Big'),
  ('Dental Laboratories', 'National/Local', 'Big'),
  ('Dentists', 'Local', 'Small'),
  ('Dentures Retailers', 'Local', 'Small'),
  ('Pediatric Dermatologists', 'Local', 'Small'),
  ('Dermatologists', 'Local', 'Small'),
  ('Diabetes Specialists', 'Local', 'Small'),
  ('Diabetic Supplies Retail', 'National', 'Big'),
  ('Dialysis Clinics', 'Local', 'Small'),
  ('Dietitians', 'Local', 'Small'),
  ('Special Needs Equipment Retailers', 'National/Local', 'Big'),
  ('Home Health Care Services', 'National/Local', 'Big'),
  ('Home Companion Services', 'Local', 'Small'),
  ('Drug and Alcohol Testing Services', 'National', 'Big'),
  ('Drug Treatment Facilities', 'National/Local', 'Big'),
  ('Pharmaceuticals', 'National', 'Big'),
  ('ENT Specialists', 'Local', 'Small'),
  ('Elder Care Services', 'Local', 'Small'),
  ('Emergency Medical Services', 'Local', 'Small'),
  ('Emergency Dental Clinics', 'Local', 'Small'),
  ('Emergency Veterinary Services', 'Local', 'Small'),
  ('Endocrinologists', 'Local', 'Small'),
  ('Endodontists', 'Local', 'Small'),
  ('Optical Goods Stores', 'National', 'Big'),
  ('Family Practice Physicians', 'Local', 'Small'),
  ('Family Planning Clinics', 'Local', 'Small'),
  ('Fertility Specialists', 'National/Local', 'Big'),
  ('Fertility Clinics', 'National/Local', 'Big'),
  ('First Aid Supplies Retail', 'National', 'Big'),
  ('Funeral Homes', 'Local', 'Small'),
  ('Gastroenterologists', 'Local', 'Small'),
  ('General Surgeons', 'Local', 'Small'),
  ('Group Medical Practices', 'National/Local', 'Big'),
  ('OB-GYN Specialists', 'Local', 'Small'),
  ('Hair Loss Clinics', 'National/Local', 'Big'),
  ('Health and Wellness Programs', 'National/Local', 'Big'),
  ('Health Associations', 'National', 'Big'),
  ('Health Care Plan Providers', 'National', 'Big'),
  ('Health Food Stores', 'Local', 'Small'),
  ('Hearing Aid Retailers', 'National', 'Big'),
  ('Herbal Product Retailers', 'National/Local', 'Big'),
  ('Holistic Health Services', 'Local', 'Small'),
  ('Hospice Services', 'Local', 'Small'),
  ('Hospital Equipment Retailers', 'National', 'Big'),
  ('Hospitals', 'National/Local', 'Big'),
  ('Hypnotherapists', 'Local', 'Small'),
  ('Internal Medicine Physicians', 'Local', 'Small'),
  ('Laser Surgery Clinics', 'Local', 'Small'),
  ('Laser Vision Correction Centers', 'Local', 'Small'),
  ('Liposuction Specialists', 'National/Local', 'Big'),
  ('Medical Imaging Centers', 'National/Local', 'Big'),
  ('Mental Health Clinics', 'Local', 'Small'),
  ('Mental Health Practitioners', 'Local', 'Small'),
  ('Physical Therapy Providers', 'National/Local', 'Big'),
  ('Plastic Surgery Clinics', 'National/Local', 'Big'),
  ('Podiatrists', 'Local', 'Small'),
  ('Prescription Drug Providers', 'National', 'Big'),
  ('Psychiatric Hospitals', 'Local', 'Small'),
  ('Pulmonologists', 'Local', 'Small'),
  ('Radiologists', 'Local', 'Small'),
  ('Rehabilitation Centers', 'National/Local', 'Big'),
  ('Respiratory Therapy Clinics', 'Local', 'Small'),
  ('Weight Loss Programs', 'National/Local', 'Big'),
  ('Women''s Health Physicians', 'Local', 'Small'),
  ('Yoga and Wellness Instruction', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Medicine & Health'
ON CONFLICT DO NOTHING;
