-- Corrected all niche names to match document exactly, fixed "National/Loca" to "National/Local"
-- Agriculture & Mining (81 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Agricultural Equipment', 'National/Local', 'Big'),
  ('Air & Gas Compressors', 'National/Local', 'Big'),
  ('Animal Feed', 'Local', 'Small'),
  ('Bags Wholesale', 'National', 'Big'),
  ('Banners', 'National', 'Big'),
  ('Barcode Scanners', 'National', 'Big'),
  ('Batteries', 'National/Local', 'Big'),
  ('Bearings', 'National/Local', 'Big'),
  ('Boxes', 'Local', 'Small'),
  ('CNC Machining', 'Local', 'Small'),
  ('Cash Registers', 'National', 'Big'),
  ('Chemicals', 'National', 'Big'),
  ('Chrome Plating', 'Local', 'Small'),
  ('Containers', 'National/Local', 'Big'),
  ('Corrugated Boxes', 'Local', 'Small'),
  ('Credit Card Equipment', 'National', 'Big'),
  ('Diesel Engines', 'National/Local', 'Big'),
  ('Electric Equipment Repair', 'Local', 'Small'),
  ('Electric Motor Repair', 'Local', 'Small'),
  ('Exporters', 'National', 'Big'),
  ('Fabrics', 'Local', 'Small'),
  ('Farm Equipment', 'National/Local', 'Big'),
  ('Farms', 'Local', 'Small'),
  ('Flags & Flagpoles', 'National', 'Big'),
  ('Forklifts', 'National/Local', 'Big'),
  ('Forklift Rental', 'Local', 'Small'),
  ('Fuel Oil', 'National/Local', 'Big'),
  ('Fuels', 'Local', 'Small'),
  ('Gas Engines', 'Local', 'Small'),
  ('General Merchandise Wholesale', 'National', 'Big'),
  ('Generators', 'National/Local', 'Big'),
  ('Importers', 'National', 'Big'),
  ('Industrial Equipment', 'National/Local', 'Big'),
  ('Industrial Equipment Rental', 'National/Local', 'Big'),
  ('Lathes', 'Local', 'Small'),
  ('Machine Shops', 'Local', 'Small'),
  ('Magnets', 'National/Local', 'Big'),
  ('Manufacturing', 'National', 'Big'),
  ('Material Handling Equipment', 'National', 'Big'),
  ('Metal Fabrication', 'Local', 'Small'),
  ('Metals Wholesale', 'National', 'Big'),
  ('Moving Boxes', 'Local', 'Small'),
  ('Oil & Gas', 'National', 'Big'),
  ('Ornamental Iron', 'Local', 'Small'),
  ('Packaging & Shipping Supplies', 'National', 'Big'),
  ('Packing Materials', 'National', 'Big'),
  ('Pallets', 'Local', 'Small'),
  ('Pallets Wholesale', 'National', 'Big'),
  ('Paper Bags', 'National', 'Big'),
  ('Paper Products Wholesale', 'National', 'Big'),
  ('Paperboard Boxes', 'Local', 'Small'),
  ('Plastic Products', 'National/Local', 'Big'),
  ('Plastics Wholesale', 'National', 'Big'),
  ('Plastic Bags', 'National', 'Big'),
  ('Plastic Molding', 'National/Local', 'Big'),
  ('Plastic Scrap', 'Local', 'Small'),
  ('Powder Coating', 'Local', 'Small'),
  ('Product Packaging', 'National/Local', 'Big'),
  ('Propane', 'Local', 'Small'),
  ('Propane Equipment', 'Local', 'Small'),
  ('Pump Repair', 'Local', 'Small'),
  ('Pumps', 'Local', 'Small'),
  ('Racks', 'National', 'Big'),
  ('Reptiles', 'Local', 'Small'),
  ('Rubber Products', 'Local', 'Small'),
  ('Sawmills', 'Local', 'Small'),
  ('Scrap & Waste Materials', 'Local', 'Small'),
  ('Scrap Metal', 'Local', 'Small'),
  ('Shelving', 'National/Local', 'Big'),
  ('Shelving Wholesale', 'National', 'Big'),
  ('Specialty Bags', 'National', 'Big'),
  ('Store Fixtures', 'National', 'Big'),
  ('Topsoil', 'Local', 'Small'),
  ('Tractor Parts', 'National/Local', 'Big'),
  ('Upholstery Fabrics', 'Local', 'Small'),
  ('Used Industrial Equipment', 'National/Local', 'Big'),
  ('Used Machine Tools', 'Local', 'Small'),
  ('Welding Contractors', 'Local', 'Small'),
  ('Welding Equipment', 'National', 'Big'),
  ('Welding Services', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Agriculture & Mining'
ON CONFLICT DO NOTHING;

-- Clothing & Accessories (65 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Alterations', 'Local', 'Small'),
  ('Antique Jewelry', 'Local', 'Small'),
  ('Athletic Footwear', 'Local', 'Small'),
  ('Boots', 'National/Local', 'Big'),
  ('Boot & Shoe Repair', 'Local', 'Small'),
  ('Boutiques', 'Local', 'Small'),
  ('Bras', 'Local', 'Small'),
  ('Bridal Shops', 'National/Local', 'Big'),
  ('Bridal Accessories', 'Local', 'Small'),
  ('Children''s Accessories', 'Local', 'Small'),
  ('Children''s Clothing', 'Local', 'Small'),
  ('Clothing Consignment', 'Local', 'Small'),
  ('Clothing Accessories', 'Local', 'Small'),
  ('Clothing Retail', 'National/Local', 'Big'),
  ('Clothing Wholesale', 'National', 'Big'),
  ('Costumes', 'Local', 'Small'),
  ('Custom Sportswear', 'National/Local', 'Big'),
  ('Custom Jewelry', 'Local', 'Small'),
  ('Custom T-Shirts', 'National/Local', 'Big'),
  ('Dance Apparel', 'Local', 'Small'),
  ('Diamond Buyers', 'National/Local', 'Big'),
  ('Diamonds', 'National', 'Big'),
  ('Dresses', 'Local', 'Small'),
  ('Dry Cleaning', 'Local', 'Small'),
  ('Eyeglasses', 'National/Local', 'Big'),
  ('Formal Wear', 'Local', 'Small'),
  ('Garment Storage', 'Local', 'Small'),
  ('Gemstones', 'National/Local', 'Big'),
  ('Gold & Silver', 'National', 'Big'),
  ('Hair Accessories', 'Local', 'Small'),
  ('Handbags', 'Local', 'Small'),
  ('Handbags Wholesale', 'National', 'Big'),
  ('Jewelry Equipment', 'Local', 'Small'),
  ('Jewelry', 'National/Local', 'Big'),
  ('Jewelry Buyers', 'National', 'Big'),
  ('Jewelry Cases', 'Local', 'Small'),
  ('Jewelry Repair', 'Local', 'Small'),
  ('Jewelry Wholesale', 'National', 'Big'),
  ('Laundry', 'Local', 'Small'),
  ('Mannequins', 'National', 'Small'),
  ('Masquerades', 'Local', 'Small'),
  ('Maternity Clothing', 'Local', 'Small'),
  ('Men''s Clothing', 'National/Local', 'Big'),
  ('Men''s Shoes', 'Local', 'Small'),
  ('Riding Apparel', 'Local', 'Small'),
  ('Safety Clothing & Equipment', 'National', 'Big'),
  ('Shoes', 'National/Local', 'Big'),
  ('Sportswear', 'National/Local', 'Big'),
  ('Swimwear', 'Local', 'Small'),
  ('T-Shirts', 'Local', 'Small'),
  ('T-Shirts Wholesale', 'National', 'Big'),
  ('Tailors', 'Local', 'Small'),
  ('Tuxedos', 'Local', 'Small'),
  ('Uniforms', 'National', 'Big'),
  ('Uniforms Retail', 'National/Local', 'Big'),
  ('Used Clothing', 'Local', 'Small'),
  ('Watches', 'National/Local', 'Big'),
  ('Watch Repair', 'Local', 'Small'),
  ('Wedding Gowns', 'National/Local', 'Big'),
  ('Wedding Rings', 'Local', 'Small'),
  ('Women''s Apparel', 'National/Local', 'Big'),
  ('Women''s Apparel Large Sizes', 'Local', 'Small'),
  ('Women''s Shoes', 'Local', 'Small'),
  ('Women''s Undergarments', 'National/Local', 'Big'),
  ('Wrist Watches', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Clothing & Accessories'
ON CONFLICT DO NOTHING;

-- Community and Government (95 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Adoption', 'National/Local', 'Big'),
  ('Adult Day Care', 'Local', 'Small'),
  ('Ambulance Services', 'Local', 'Small'),
  ('Army & Navy Goods', 'Local', 'Small'),
  ('Assembly Of God Churches', 'Local', 'Small'),
  ('Astrologers', 'Local', 'Small'),
  ('Baptist Churches', 'Local', 'Small'),
  ('Bibles', 'National', 'Big'),
  ('Birth Records', 'National', 'Big'),
  ('Catholic Churches', 'Local', 'Small'),
  ('Charitable Organizations', 'National/Local', 'Big'),
  ('Charity Fundraising', 'National/Local', 'Big'),
  ('Child Care Centers', 'Local', 'Small'),
  ('Child Care Services', 'Local', 'Small'),
  ('Child Support', 'National', 'Big'),
  ('Christian Churches', 'Local', 'Small'),
  ('Christian Science Practitioners', 'Local', 'Small'),
  ('Church & Religious Organizations', 'National/Local', 'Big'),
  ('Church Furniture', 'National', 'Small'),
  ('Church Supplies', 'National', 'Small'),
  ('Churches Of Christ', 'Local', 'Small'),
  ('Churches Of Jesus Christ Of Latter Day Saints', 'Local', 'Small'),
  ('Churches', 'Local', 'Small'),
  ('Community Centers', 'Local', 'Small'),
  ('Community Organizations', 'Local', 'Small'),
  ('Community Services', 'Local', 'Small'),
  ('Correctional Facilities', 'National/Local', 'Big'),
  ('Counseling', 'Local', 'Small'),
  ('Counseling Services', 'Local', 'Small'),
  ('County Government', 'Local', 'Big'),
  ('Courts', 'Local', 'Small'),
  ('Crisis Intervention', 'Local', 'Small'),
  ('Divorce Assistance', 'Local', 'Small'),
  ('Emergency Supplies', 'National/Local', 'Big'),
  ('Federal Government', 'National', 'Big'),
  ('Fire Protection', 'Local', 'Small'),
  ('Flood Damage', 'National/Local', 'Big'),
  ('Fortune Tellers', 'Local', 'Small'),
  ('Fraternal Organizations', 'Local', 'Small'),
  ('Government Contractors', 'National', 'Big'),
  ('Government Offices', 'National', 'Big'),
  ('Home Child Care', 'Local', 'Small'),
  ('Housing Authorities', 'Local', 'Big'),
  ('Immigration & Naturalization Consultants', 'National', 'Big'),
  ('Information & Referral Services', 'Local', 'Small'),
  ('Intervention Services', 'Local', 'Small'),
  ('Jehovah''s Witnesses Kingdom Halls', 'Local', 'Small'),
  ('Local Government', 'Local', 'Big'),
  ('Lutheran Churches', 'Local', 'Small'),
  ('Marriage & Family Therapists', 'Local', 'Small'),
  ('Marriage Counseling', 'Local', 'Small'),
  ('Marriage Records', 'National', 'Big'),
  ('Medical Emergency Services', 'Local', 'Small'),
  ('Messianic Jewish Churches', 'Local', 'Small'),
  ('Methodist Churches', 'Local', 'Small'),
  ('Military & Veterans Organizations', 'National', 'Big'),
  ('Military Recruiters', 'National', 'Big'),
  ('Ministries', 'Local', 'Small'),
  ('Missionaries', 'Local', 'Small'),
  ('Mosques', 'Local', 'Small'),
  ('Municipal Courts', 'Local', 'Small'),
  ('National Guard', 'National', 'Big'),
  ('Non-Denominational Churches', 'Local', 'Small'),
  ('Palmists', 'Local', 'Small'),
  ('Pentecostal Churches', 'Local', 'Small'),
  ('Police Departments', 'Local', 'Small'),
  ('Police Equipment & Supplies', 'National/Local', 'Big'),
  ('Postal Services', 'National', 'Big'),
  ('Presbyterian Churches', 'Local', 'Small'),
  ('Psychics', 'Local', 'Small'),
  ('Psychics & Mediums', 'Local', 'Small'),
  ('Public Health', 'Local', 'Small'),
  ('Religious Goods', 'National', 'Big'),
  ('Residential Care', 'Local', 'Small'),
  ('Retirement & Assisted Living', 'Local', 'Small'),
  ('Retirement Homes', 'Local', 'Small'),
  ('Salvation Army', 'National', 'Big'),
  ('Search & Rescue', 'National/Local', 'Big'),
  ('Senior Citizens Service Organizations', 'Local', 'Small'),
  ('Senior Citizens Products & Services', 'National/Local', 'Big'),
  ('Sheriffs', 'Local', 'Small'),
  ('Singles Organizations', 'Local', 'Small'),
  ('Social Service Organizations', 'National/Local', 'Big'),
  ('Social Security', 'National', 'Big'),
  ('Social Security Representatives', 'National', 'Big'),
  ('Social Workers', 'Local', 'Small'),
  ('State Government', 'National', 'Big'),
  ('Synagogues', 'Local', 'Small'),
  ('Unitarian Universalist Churches', 'Local', 'Small'),
  ('Urgent Care Centers', 'Local', 'Small'),
  ('Vehicle Licensing', 'Local', 'Big'),
  ('Volunteer Organizations', 'National/Local', 'Big'),
  ('Women''s Organizations', 'Local', 'Small'),
  ('Youth Organizations & Centers', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Community and Government'
ON CONFLICT DO NOTHING;
