-- Agriculture & Mining (81 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Agricultural Equipment Retailers', 'National/Loca', 'Big'),
  ('Air & Gas Compressor Dealers', 'National/Loca', 'Big'),
  ('Animal Feed Suppliers', 'Local', 'Small'),
  ('Wholesale Bags Manufacturers', 'National', 'Big'),
  ('Banner and Flag Manufacturers', 'National', 'Big'),
  ('Barcode Scanning Equipment Suppliers', 'National', 'Big'),
  ('Battery Retail Stores', 'National/Loca', 'Big'),
  ('Bearings Dealers', 'National/Loca', 'Big'),
  ('Boxes and Packaging Retailers', 'Local', 'Small'),
  ('CNC Machining and Milling Shops', 'Local', 'Small'),
  ('Cash Register Equipment Suppliers', 'National', 'Big'),
  ('Chemicals Wholesale and Manufacturing', 'National', 'Big'),
  ('Chrome Plating Services', 'Local', 'Small'),
  ('Industrial Containers Suppliers', 'National/Loca', 'Big'),
  ('Corrugated Box Retailers', 'Local', 'Small'),
  ('Credit Card Equipment Providers', 'National', 'Big'),
  ('Diesel Engine Services and Parts', 'National/Loca', 'Big'),
  ('Electric Equipment Repair Services', 'Local', 'Small'),
  ('Electric Motor Repair Services', 'Local', 'Small'),
  ('Exporting Companies', 'National', 'Big'),
  ('Fabric and Textile Shops', 'Local', 'Small'),
  ('Farm Equipment Dealers', 'National/Loca', 'Big'),
  ('Farms and Ranches', 'Local', 'Small'),
  ('Flag and Flagpole Manufacturers', 'National', 'Big'),
  ('Forklift Dealers', 'National/Loca', 'Big'),
  ('Forklift Rental Services', 'Local', 'Small'),
  ('Fuel Oil Suppliers', 'National/Loca', 'Big'),
  ('Fuel Retail Stores', 'Local', 'Small'),
  ('Gas Engine Dealers', 'Local', 'Small'),
  ('General Merchandise Wholesalers', 'National', 'Big'),
  ('Commercial Generator Suppliers', 'National/Loca', 'Big'),
  ('Importing Companies', 'National', 'Big'),
  ('Industrial Equipment Retailers', 'National/Loca', 'Big'),
  ('Industrial Equipment Rentals', 'National/Loca', 'Big'),
  ('Lathe Dealers', 'Local', 'Small'),
  ('Machine Shops', 'Local', 'Small'),
  ('Magnet Suppliers', 'National/Loca', 'Big'),
  ('Manufacturing and Production Companies', 'National', 'Big'),
  ('Material Handling Equipment Dealers', 'National', 'Big'),
  ('Metal Fabrication Services', 'Local', 'Small'),
  ('Wholesale Metal Products Suppliers', 'National', 'Big'),
  ('Moving Box Retailers', 'Local', 'Small'),
  ('Oil and Gas Companies', 'National', 'Big'),
  ('Ornamental Ironwork Services', 'Local', 'Small'),
  ('Packaging and Shipping Supplies Wholesale', 'National', 'Big'),
  ('Packing Materials Suppliers', 'National', 'Big'),
  ('Pallet Dealers', 'Local', 'Small'),
  ('Wholesale Pallet Manufacturers', 'National', 'Big'),
  ('Paper Bag Manufacturers', 'National', 'Big'),
  ('Paper Products Wholesale Suppliers', 'National', 'Big'),
  ('Retail Paperboard Box Suppliers', 'Local', 'Small'),
  ('Plastic Product Retailers', 'National/Loca', 'Big'),
  ('Plastic Product Wholesale Suppliers', 'National', 'Big'),
  ('Plastic Bag Manufacturers', 'National', 'Big'),
  ('Plastic Injection Molding Services', 'National/Loca', 'Big'),
  ('Plastic Scrap Suppliers', 'Local', 'Small'),
  ('Powder Coating Services', 'Local', 'Small'),
  ('Product Packaging and Shipping Services', 'National/Loca', 'Big'),
  ('Propane Gas Suppliers', 'Local', 'Small'),
  ('Propane Equipment Suppliers', 'Local', 'Small'),
  ('Pump Repair Services', 'Local', 'Small'),
  ('Pump Parts Dealers', 'Local', 'Small'),
  ('Rack Suppliers', 'National', 'Big'),
  ('Reptile Dealers', 'Local', 'Small'),
  ('Rubber Product Retailers', 'Local', 'Small'),
  ('Sawmills', 'Local', 'Small'),
  ('Scrap and Waste Material Buyers', 'Local', 'Small'),
  ('Scrap Iron and Metal Dealers', 'Local', 'Small'),
  ('Shelving Dealers', 'National/Loca', 'Big'),
  ('Industrial Shelving Suppliers', 'National', 'Big'),
  ('Specialty Bag Manufacturers', 'National', 'Big'),
  ('Store Fixture Suppliers', 'National', 'Big'),
  ('Topsoil and Fill Dirt Dealers', 'Local', 'Small'),
  ('Tractor Parts and Equipment Dealers', 'National/Loca', 'Big'),
  ('Upholstery Fabric Retailers', 'Local', 'Small'),
  ('Used Industrial Equipment Dealers', 'National/Loca', 'Big'),
  ('Used Machine Tool Dealers', 'Local', 'Small'),
  ('Welding Contractors', 'Local', 'Small'),
  ('Welding Equipment Retailers', 'National', 'Big'),
  ('Welding Services', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Agriculture & Mining'
ON CONFLICT DO NOTHING;

-- Clothing & Accessories (65 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Alterations and Tailoring Services', 'Local', 'Small'),
  ('Antique and Vintage Jewelry Retail', 'Local', 'Small'),
  ('Athletic and Dance Footwear Shop', 'Local', 'Small'),
  ('Work Boots and Safety Shoes Retail', 'National/Loca', 'Big'),
  ('Shoe and Leather Repair Shops', 'Local', 'Small'),
  ('Boutique Clothing Stores', 'Local', 'Small'),
  ('Specialty Bras and Shapewear', 'Local', 'Small'),
  ('Bridal Shops and Services', 'National/Loca', 'Big'),
  ('Bridal Accessories Retail', 'Local', 'Small'),
  ('Kids'' Accessories Retail', 'Local', 'Small'),
  ('Children''s Clothing Retail', 'Local', 'Small'),
  ('Clothing Consignment and Resale', 'Local', 'Small'),
  ('Fashion Accessories Retail', 'Local', 'Small'),
  ('Clothing Retail Stores', 'National/Loca', 'Big'),
  ('Wholesale Clothing Distributors', 'National', 'Big'),
  ('Costume Rentals and Sales', 'Local', 'Small'),
  ('Custom Sportswear and Embroidery', 'National/Loca', 'Big'),
  ('Personalized Jewelry Shops', 'Local', 'Small'),
  ('Custom T-Shirt Printing', 'National/Loca', 'Big'),
  ('Dance Apparel Retail', 'Local', 'Small'),
  ('Diamond Buyers and Brokers', 'National/Loca', 'Big'),
  ('Diamond Retailers', 'National', 'Big'),
  ('Dress Shops', 'Local', 'Small'),
  ('Dry Cleaning and Laundry Services', 'Local', 'Small'),
  ('Eyewear Stores', 'National/Loca', 'Big'),
  ('Formalwear Rentals and Sales', 'Local', 'Small'),
  ('Garment Storage Solutions', 'Local', 'Small'),
  ('Gemstone Retailers', 'National/Loca', 'Big'),
  ('Precious Metals Dealers', 'National', 'Big'),
  ('Hair Accessories Boutiques', 'Local', 'Small'),
  ('Handbag Retailers', 'Local', 'Small'),
  ('Handbag Manufacturers and Distributors', 'National', 'Big'),
  ('Jewelry Supplies and Equipment Retail', 'Local', 'Small'),
  ('Jewelry Stores', 'National/Loca', 'Big'),
  ('Jewelry Buyers and Brokers', 'National', 'Big'),
  ('Display Cases for Jewelry', 'Local', 'Small'),
  ('Jewelry Repair Services', 'Local', 'Small'),
  ('Jewelry Manufacturers and Wholesale', 'National', 'Big'),
  ('Laundry Services', 'Local', 'Small'),
  ('Mannequin Suppliers', 'National', 'Small'),
  ('Costume and Theatrical Rentals', 'Local', 'Small'),
  ('Maternity Apparel Retail', 'Local', 'Small'),
  ('Men''s Fashion Retailers', 'National/Loca', 'Big'),
  ('Men''s Shoe Stores', 'Local', 'Small'),
  ('Equestrian Apparel and Gear', 'Local', 'Small'),
  ('Safety Gear and Apparel Retail', 'National', 'Big'),
  ('Shoe Stores', 'National/Loca', 'Big'),
  ('Sportswear Shops', 'National/Loca', 'Big'),
  ('Swimwear Retail', 'Local', 'Small'),
  ('T-Shirt Shops', 'Local', 'Small'),
  ('T-Shirt Manufacturers and Wholesale', 'National', 'Big'),
  ('Custom Tailoring Services', 'Local', 'Small'),
  ('Tuxedo Rentals and Sales', 'Local', 'Small'),
  ('Uniform Suppliers (Industrial)', 'National', 'Big'),
  ('Retail Uniform Stores', 'National/Loca', 'Big'),
  ('Used Clothing Shops', 'Local', 'Small'),
  ('Watch Retailers', 'National/Loca', 'Big'),
  ('Watch Repair Services', 'Local', 'Small'),
  ('Wedding Dress Shops', 'National/Loca', 'Big'),
  ('Wedding Jewelry', 'Local', 'Small'),
  ('Women''s Fashion Retailers', 'National/Loca', 'Big'),
  ('Plus-Size Clothing Stores', 'Local', 'Small'),
  ('Women''s Shoe Stores', 'Local', 'Small'),
  ('Lingerie and Undergarment Retail', 'National/Loca', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Clothing & Accessories'
ON CONFLICT DO NOTHING;

-- Community and Government (95 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Adoption Services', 'National/Loca', 'Big'),
  ('Adult Daycare Centers', 'Local', 'Small'),
  ('Emergency Medical Transport Services', 'Local', 'Small'),
  ('Military Surplus Stores', 'Local', 'Small'),
  ('Assembly of God Churches', 'Local', 'Small'),
  ('Astrology and Horoscope Services', 'Local', 'Small'),
  ('Baptist Churches', 'Local', 'Small'),
  ('Religious Books and Bibles Retail', 'National', 'Big'),
  ('Birth Records Services', 'National', 'Big'),
  ('Catholic Churches', 'Local', 'Small'),
  ('Nonprofit Charitable Organizations', 'National/Loca', 'Big'),
  ('Charity Fundraising Groups', 'National/Loca', 'Big'),
  ('Childcare Centers', 'Local', 'Small'),
  ('Childcare Services', 'Local', 'Small'),
  ('Child Support Services', 'National', 'Big'),
  ('Christian Churches', 'Local', 'Small'),
  ('Christian Science Practitioners', 'Local', 'Small'),
  ('Religious Organizations', 'National/Loca', 'Big'),
  ('Church Furniture Suppliers', 'National', 'Small'),
  ('Church Supplies Retail', 'National', 'Small'),
  ('Church of Christ Churches', 'Local', 'Small'),
  ('LDS (Mormon) Churches', 'Local', 'Small'),
  ('Churches', 'Local', 'Small'),
  ('Community Activity Centers', 'Local', 'Small'),
  ('Community Support Organizations', 'Local', 'Small'),
  ('Community Service Providers', 'Local', 'Small'),
  ('Correctional Facilities', 'National/Loca', 'Big'),
  ('Counseling and Therapy Centers', 'Local', 'Small'),
  ('Counseling Services', 'Local', 'Small'),
  ('County Government Offices', 'Local', 'Big'),
  ('Judicial Courts', 'Local', 'Small'),
  ('Crisis Support Services', 'Local', 'Small'),
  ('Divorce Mediation and Counseling', 'Local', 'Small'),
  ('Disaster Preparedness Products', 'National/Loca', 'Big'),
  ('Federal Government Offices', 'National', 'Big'),
  ('Fire Protection Services', 'Local', 'Small'),
  ('Flood Relief Services', 'National/Loca', 'Big'),
  ('Fortune Telling Services', 'Local', 'Small'),
  ('Fraternal Organizations', 'Local', 'Small'),
  ('Government Contractors', 'National', 'Big'),
  ('Government Offices', 'National', 'Big'),
  ('At-Home Childcare Providers', 'Local', 'Small'),
  ('Public Housing Authorities', 'Local', 'Big'),
  ('Immigration and Citizenship Services', 'National', 'Big'),
  ('Family Support Organizations', 'Local', 'Small'),
  ('Personal Counseling Services', 'Local', 'Small'),
  ('Jehovah''s Witness Kingdom Halls', 'Local', 'Small'),
  ('Local Government Offices', 'Local', 'Big'),
  ('Lutheran Churches', 'Local', 'Small'),
  ('Marriage and Family Therapy', 'Local', 'Small'),
  ('Marriage Counseling Referrals', 'Local', 'Small'),
  ('Marriage Records Retrieval', 'National', 'Big'),
  ('Emergency Medical Services', 'Local', 'Small'),
  ('Messianic Jewish Churches', 'Local', 'Small'),
  ('Methodist Churches', 'Local', 'Small'),
  ('Veterans and Military Organizations', 'National', 'Big'),
  ('Military Recruitment Offices', 'National', 'Big'),
  ('Ministry Outreach Churches', 'Local', 'Small'),
  ('Missionary Churches', 'Local', 'Small'),
  ('Mosques', 'Local', 'Small'),
  ('City and Municipal Courts', 'Local', 'Small'),
  ('National Guard Services', 'National', 'Big'),
  ('Non-Denominational Churches', 'Local', 'Small'),
  ('Palm Reading Services', 'Local', 'Small'),
  ('Pentecostal Churches', 'Local', 'Small'),
  ('Local Police Departments', 'Local', 'Small'),
  ('Police Equipment Suppliers', 'National/Loca', 'Big'),
  ('Postal Services', 'National', 'Big'),
  ('Presbyterian Churches', 'Local', 'Small'),
  ('Psychic Reading Services', 'Local', 'Small'),
  ('Mediums and Spiritual Readings', 'Local', 'Small'),
  ('Public Health and Safety Services', 'Local', 'Small'),
  ('Religious Goods Stores', 'National', 'Big'),
  ('Residential Care Homes', 'Local', 'Small'),
  ('Senior Living Centers', 'Local', 'Small'),
  ('Retirement Communities', 'Local', 'Small'),
  ('Salvation Army', 'National', 'Big'),
  ('Search and Rescue Services', 'National/Loca', 'Big'),
  ('Senior Citizens'' Support Centers', 'Local', 'Small'),
  ('Senior Living Products', 'National/Loca', 'Big'),
  ('Sheriff''s Departments', 'Local', 'Small'),
  ('Singles Support Groups', 'Local', 'Small'),
  ('Social and Human Services', 'National/Loca', 'Big'),
  ('Social Security Services', 'National', 'Big'),
  ('Social Security Advocacy Representatives', 'National', 'Big'),
  ('Social Workers', 'Local', 'Small'),
  ('State Government Offices', 'National', 'Big'),
  ('Synagogues and Temples', 'Local', 'Small'),
  ('Unitarian Churches', 'Local', 'Small'),
  ('Urgent Care Clinics', 'Local', 'Small'),
  ('DMV and Licensing Services', 'Local', 'Big'),
  ('Volunteer Programs', 'National/Loca', 'Big'),
  ('Women''s Crisis Support Services', 'Local', 'Small'),
  ('Youth Clubs and Activity Centers', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Community and Government'
ON CONFLICT DO NOTHING;
