-- Computer & Tech (72 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Document Storage and Archives Services', 'National/Loca', 'Big'),
  ('Audio and Video Recording Equipment', 'National/Loca', 'Big'),
  ('AV Equipment Rental and Leasing', 'National/Loca', 'Big'),
  ('Audiovisual Supplies and Dealers', 'National/Loca', 'Big'),
  ('Large Screen Television Stores', 'National/Loca', 'Big'),
  ('High-Speed Broadband Services', 'National', 'Big'),
  ('Business IT Hardware Suppliers', 'National', 'Big'),
  ('Business Software Solutions', 'National', 'Big'),
  ('Cable TV Equipment Stores', 'Local', 'Small'),
  ('Camcorder Retail and Repair', 'Local', 'Small'),
  ('Computer and Software Retailers', 'National', 'Big'),
  ('Computer Cabling and Installation', 'Local', 'Small'),
  ('IT Consulting Services', 'National/Loca', 'Big'),
  ('Computer Workstations and Desks', 'National/Loca', 'Big'),
  ('Computer Parts and Hardware Retailers', 'National', 'Big'),
  ('Networking Equipment and Installation', 'National/Loca', 'Big'),
  ('Computer Network Management Services', 'National/Loca', 'Big'),
  ('Computer Printers and Accessories', 'National', 'Big'),
  ('PC and Laptop Repair Services', 'Local', 'Small'),
  ('Cybersecurity Services', 'National', 'Big'),
  ('Software Retail and Support', 'National/Loca', 'Big'),
  ('Electronics and IT Equipment Stores', 'National', 'Big'),
  ('Computer Parts and Accessories Retail', 'National/Loca', 'Big'),
  ('IT Systems Design and Consulting', 'National/Loca', 'Big'),
  ('PC Upgrades and Customization Services', 'Local', 'Small'),
  ('Computer Rentals and Leasing', 'National/Loca', 'Big'),
  ('Wholesale Computer Distributors', 'National', 'Big'),
  ('DSL Internet Providers', 'National', 'Big'),
  ('Data Recovery and Backup Services', 'National/Loca', 'Big'),
  ('Digital Imaging Services', 'National/Loca', 'Big'),
  ('Electronic Retail Stores', 'National', 'Big'),
  ('Email Marketing Platforms and Services', 'National', 'Big'),
  ('Electronics Retail and Wholesale', 'National', 'Big'),
  ('IT Support and Helpdesk Services', 'National', 'Big'),
  ('Home Theater Installation Services', 'Local', 'Small'),
  ('Custom Home Entertainment Systems', 'Local', 'Small'),
  ('Entertainment Center Sales and Install', 'Local', 'Small'),
  ('IT Services and Solutions', 'National', 'Big'),
  ('Internet Access Providers', 'National', 'Big'),
  ('Online Advertising Services', 'National', 'Big'),
  ('Digital Marketing Agencies', 'National', 'Big'),
  ('Online Products and Services', 'National', 'Big'),
  ('ISP (Internet Service Providers)', 'National', 'Big'),
  ('Internet Solutions Companies', 'National', 'Big'),
  ('Laser Printer Supplies Retail', 'National', 'Big'),
  ('Laser Printer Sales and Support', 'National', 'Big'),
  ('Printer Repair Services', 'Local', 'Small'),
  ('Multimedia Content Creation', 'National/Loca', 'Big'),
  ('IT Networking Consultants', 'National/Loca', 'Big'),
  ('Network Optimization Solutions', 'National/Loca', 'Big'),
  ('POS (Point of Sale) Systems Providers', 'National', 'Big'),
  ('Printing Equipment Repair Services', 'Local', 'Small'),
  ('Satellite Dish Equipment Retailers', 'Local', 'Small'),
  ('Satellite Systems and Installation', 'National/Loca', 'Big'),
  ('TV Equipment and Supplies Retail', 'National/Loca', 'Big'),
  ('Document Scanning Services', 'Local', 'Small'),
  ('Custom Software Development', 'National', 'Big'),
  ('Software Training and Support', 'National/Loca', 'Big'),
  ('Audio and Sound Systems Retail and Lease', 'Local', 'Small'),
  ('Stereo Systems Dealers', 'Local', 'Small'),
  ('Television Sales and Retail', 'National/Loca', 'Big'),
  ('TV Repair Services', 'Local', 'Small'),
  ('Refurbished Computer Retailers', 'Local', 'Small'),
  ('Video Camera Sales and Repair', 'Local', 'Small'),
  ('Video Equipment Installation Services', 'National/Loca', 'Big'),
  ('Video Equipment Leasing and Rentals', 'Local', 'Small'),
  ('Professional Video Gear Retail', 'National/Loca', 'Big'),
  ('Web Design and Development Services', 'National/Loca', 'Big'),
  ('Website Development Agencies', 'National', 'Big'),
  ('Web Hosting Solutions', 'National', 'Big'),
  ('Online Business Websites', 'National', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Computer & Tech'
ON CONFLICT DO NOTHING;

-- Education (73 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Academic Specialty Schools', 'National/Loca', 'Big'),
  ('Accounting and Bookkeeping Training', 'National/Loca', 'Big'),
  ('Adult Education Centers', 'Local', 'Small'),
  ('After School Enrichment Programs', 'Local', 'Small'),
  ('Allied Health Training Programs', 'National/Loca', 'Big'),
  ('Automotive Mechanic Schools', 'National/Loca', 'Big'),
  ('Aviation Training Schools', 'National', 'Big'),
  ('Bartending Schools', 'Local', 'Small'),
  ('Beauty and Cosmetology Schools', 'National/Loca', 'Big'),
  ('Boards of Education', 'Local', 'Small'),
  ('Business Coaching Services', 'National/Loca', 'Big'),
  ('Business Colleges', 'National', 'Big'),
  ('Corporate and Personal Development Training', 'National/Loca', 'Big'),
  ('CPR and First Aid Training', 'Local', 'Small'),
  ('Career and Workplace Education Programs', 'National/Loca', 'Big'),
  ('Child Development and Learning Centers', 'Local', 'Small'),
  ('College Financial Planning Services', 'National', 'Big'),
  ('College Preparatory Schools', 'Local', 'Small'),
  ('Colleges', 'National', 'Big'),
  ('Community Colleges', 'National/Loca', 'Big'),
  ('Computer Programming Classes', 'National/Loca', 'Big'),
  ('IT and Technology Training Schools', 'National', 'Big'),
  ('Computer Skills Training Programs', 'National/Loca', 'Big'),
  ('Continuing Education Programs', 'National/Loca', 'Big'),
  ('Court Reporting Training Schools', 'National', 'Big'),
  ('Culinary Arts Schools', 'National', 'Big'),
  ('Dance and Movement Studios', 'Local', 'Small'),
  ('Dental Assistant Training Schools', 'National', 'Big'),
  ('Educational Administration Services', 'National', 'Big'),
  ('Educational Consulting Services', 'National/Loca', 'Big'),
  ('Educational Supplies and Equipment Retailers', 'National', 'Big'),
  ('Educational Financing Services', 'National', 'Big'),
  ('General Educational Services', 'National/Loca', 'Big'),
  ('Elementary and Secondary Education', 'Local', 'Small'),
  ('Elementary Schools', 'Local', 'Small'),
  ('Fashion Design and Styling Schools', 'National', 'Big'),
  ('Graduate and Professional Degree Programs', 'National', 'Big'),
  ('Graphic Arts and Design Schools', 'National/Loca', 'Big'),
  ('High Schools', 'Local', 'Small'),
  ('Home Schooling Services', 'National', 'Big'),
  ('Industrial and Trade Training Schools', 'National/Loca', 'Big'),
  ('Interior Design Education', 'National', 'Big'),
  ('Middle Schools', 'Local', 'Small'),
  ('Language Instruction and Training', 'National/Loca', 'Big'),
  ('Law Schools', 'National', 'Big'),
  ('Learning and Development Centers', 'Local', 'Small'),
  ('Leadership and Management Training', 'National/Loca', 'Big'),
  ('Management Training and Consulting', 'National', 'Big'),
  ('Medical Assistant and Technician Schools', 'National', 'Big'),
  ('Medical Billing and Records Training', 'National', 'Big'),
  ('Medical Schools', 'National', 'Big'),
  ('Medical Secretarial Training Programs', 'National', 'Big'),
  ('Military Academies', 'National', 'Big'),
  ('Nursing Training Programs', 'National', 'Big'),
  ('Online Education and Correspondence Schools', 'National', 'Big'),
  ('Online College Degree Programs', 'National', 'Big'),
  ('Specialized Training and Instruction', 'National/Loca', 'Big'),
  ('Paralegal Certification Programs', 'National', 'Big'),
  ('Pet Grooming Training Schools', 'Local', 'Small'),
  ('Preschools', 'Local', 'Small'),
  ('Private Education Institutions', 'Local', 'Small'),
  ('Public Schools', 'Local', 'Small'),
  ('Radiology Training Programs', 'National', 'Big'),
  ('Religious and Faith-Based Education', 'Local', 'Small'),
  ('Sales and Business Training', 'National/Loca', 'Big'),
  ('School Supplies and Equipment Retail', 'National', 'Big'),
  ('Secretarial and Administrative Training', 'National', 'Big'),
  ('Self-Defense Training Programs', 'Local', 'Small'),
  ('Sports and Fitness Coaching', 'Local', 'Small'),
  ('Professional Development Training Programs', 'National', 'Big'),
  ('Tutoring and Academic Support Services', 'Local', 'Small'),
  ('Vocational and Technical Education', 'National/Loca', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Education'
ON CONFLICT DO NOTHING;

-- Fitness & Personal Care (58 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Barbers', 'Local', 'Small'),
  ('Barbers'' Equipment & Supplies', 'National', 'Big'),
  ('Beauticians', 'Local', 'Small'),
  ('Beauty Salon Equipment Retail', 'National', 'Big'),
  ('Beauty Salon Equipment Wholesale', 'National', 'Big'),
  ('Beauty Salons', 'Local', 'Small'),
  ('Beauty Supplies Retail', 'National/Loca', 'Big'),
  ('Body Art and Piercing', 'Local', 'Small'),
  ('Body Wrap Salons', 'Local', 'Small'),
  ('Certified Massage Therapists', 'Local', 'Small'),
  ('Cosmetic Tattoos', 'Local', 'Small'),
  ('Cosmetics Retail', 'National/Loca', 'Big'),
  ('Dating Services', 'National', 'Big'),
  ('Day Spas', 'Local', 'Small'),
  ('Delivery and Errand Services', 'Local', 'Small'),
  ('Diapers and Diaper Services', 'Local', 'Small'),
  ('Ear and Body Piercing', 'Local', 'Small'),
  ('Electrolysis Hair Removal', 'Local', 'Small'),
  ('Escorts', 'Local', 'Small'),
  ('Exercise Classes', 'Local', 'Small'),
  ('Facial Treatment Services', 'Local', 'Small'),
  ('Fitness Consultants', 'Local', 'Small'),
  ('Fitness Equipment', 'National/Loca', 'Big'),
  ('Gymnastics Instruction', 'Local', 'Small'),
  ('Hair Care and Treatment', 'Local', 'Small'),
  ('Hair Care Products Retail', 'National', 'Big'),
  ('Hair Clippers Retail', 'National', 'Big'),
  ('Hair Goods Retail', 'National/Loca', 'Big'),
  ('Hair Implants and Transplants', 'Local', 'Small'),
  ('Hair Removal Services', 'Local', 'Small'),
  ('Hair Replacement Services', 'Local', 'Small'),
  ('Hair Weaving Services', 'Local', 'Small'),
  ('Health and Beauty Aids Retail', 'National', 'Big'),
  ('Health Clubs', 'Local', 'Small'),
  ('Health Spas', 'Local', 'Small'),
  ('Laser Hair Removal', 'Local', 'Small'),
  ('Licensed Massage Therapists', 'Local', 'Small'),
  ('Manicures', 'Local', 'Small'),
  ('Martial Arts Equipment Suppliers', 'National', 'Big'),
  ('Massage Equipment Retail', 'National', 'Big'),
  ('Massage Schools', 'Local', 'Small'),
  ('Nail Salon Equipment Wholesale', 'National', 'Big'),
  ('Perfumes and Colognes Retail', 'National', 'Big'),
  ('Permanent Makeup Services', 'Local', 'Small'),
  ('Personal Services', 'Local', 'Small'),
  ('Personal Trainers', 'Local', 'Small'),
  ('Sauna Baths', 'Local', 'Small'),
  ('Skin Care Products Retail', 'National/Loca', 'Big'),
  ('Tanning Beds Retail', 'National', 'Big'),
  ('Tanning Salon Equipment Retail', 'National', 'Big'),
  ('Tanning Salons', 'Local', 'Small'),
  ('Tattoo Removal Services', 'Local', 'Small'),
  ('Tattoo Parlors', 'Local', 'Small'),
  ('Waxing Hair Removal Services', 'Local', 'Small'),
  ('Weight Training Centers', 'Local', 'Small'),
  ('Weightlifting Equipment Retail', 'National', 'Big'),
  ('Wigs and Hairpieces Retail', 'National/Loca', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Fitness & Personal Care'
ON CONFLICT DO NOTHING;
