-- Corrected all niche names to match document exactly, fixed "National/Loca" to "National/Local"
-- Computer & Tech (72 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Archives', 'National/Local', 'Big'),
  ('Audio Visual Equipment', 'National/Local', 'Big'),
  ('Audio Visual Rental', 'National/Local', 'Big'),
  ('Audio-Visual Equipment Supplies', 'National/Local', 'Big'),
  ('Big Screen TVs', 'National/Local', 'Big'),
  ('Broadband', 'National', 'Big'),
  ('Business Computers', 'National', 'Big'),
  ('Business Software', 'National', 'Big'),
  ('Cable TV Equipment', 'Local', 'Small'),
  ('Camcorders', 'Local', 'Small'),
  ('Computers', 'National', 'Big'),
  ('Computer Cabling', 'Local', 'Small'),
  ('Computer Consultants', 'National/Local', 'Big'),
  ('Computer Furniture', 'National/Local', 'Big'),
  ('Computer Hardware', 'National', 'Big'),
  ('Computer Installation & Setup', 'National/Local', 'Big'),
  ('Computer Networks', 'National/Local', 'Big'),
  ('Computer Printers', 'National', 'Big'),
  ('Computer Repair', 'Local', 'Small'),
  ('Computer Security', 'National', 'Big'),
  ('Computer Software', 'National/Local', 'Big'),
  ('Computer Stores', 'National', 'Big'),
  ('Computer Supplies', 'National/Local', 'Big'),
  ('Computer System Designers', 'National/Local', 'Big'),
  ('Computer Upgrades', 'Local', 'Small'),
  ('Computers Rental & Leasing', 'National/Local', 'Big'),
  ('Computers Wholesale', 'National', 'Big'),
  ('DSL', 'National', 'Big'),
  ('Data Recovery', 'National/Local', 'Big'),
  ('Digital Imaging', 'National/Local', 'Big'),
  ('Electronics Retail', 'National', 'Big'),
  ('Email', 'National', 'Big'),
  ('Electronics Wholesale', 'National', 'Big'),
  ('Help Desk Services', 'National', 'Big'),
  ('Home Theater', 'Local', 'Small'),
  ('Home Theater Systems', 'Local', 'Small'),
  ('Entertainment Centers', 'Local', 'Small'),
  ('IT Services', 'National', 'Big'),
  ('Internet Access', 'National', 'Big'),
  ('Internet Advertising', 'National', 'Big'),
  ('Internet Marketing', 'National', 'Big'),
  ('Internet Products & Services', 'National', 'Big'),
  ('Internet Service Providers', 'National', 'Big'),
  ('Internet Solutions', 'National', 'Big'),
  ('Laser Printer Supplies', 'National', 'Big'),
  ('Laser Printers', 'National', 'Big'),
  ('Laser Printers Repair & Service', 'Local', 'Small'),
  ('Multimedia', 'National/Local', 'Big'),
  ('Networking', 'National/Local', 'Big'),
  ('Networks', 'National/Local', 'Big'),
  ('Point Of Sale Equipment', 'National', 'Big'),
  ('Printer Repair', 'Local', 'Small'),
  ('Satellite Dishes', 'Local', 'Small'),
  ('Satellite Systems', 'National/Local', 'Big'),
  ('Satellite TV Equipment & Systems', 'National/Local', 'Big'),
  ('Scanning Services', 'Local', 'Small'),
  ('Software Development', 'National', 'Big'),
  ('Software Training', 'National/Local', 'Big'),
  ('Sound Systems', 'Local', 'Small'),
  ('Stereos', 'Local', 'Small'),
  ('Televisions', 'National/Local', 'Big'),
  ('Television Repair', 'Local', 'Small'),
  ('Used Computers', 'Local', 'Small'),
  ('Video Cameras', 'Local', 'Small'),
  ('Video Equipment', 'National/Local', 'Big'),
  ('Video Equipment Rental', 'Local', 'Small'),
  ('Video Gear', 'National/Local', 'Big'),
  ('Web Design', 'National/Local', 'Big'),
  ('Web Site Design', 'National', 'Big'),
  ('Web Site Hosting', 'National', 'Big'),
  ('Websites', 'National', 'Big'),
  ('Wireless Internet', 'National', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Computer & Tech'
ON CONFLICT DO NOTHING;

-- Education (73 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Academic Schools', 'National/Local', 'Big'),
  ('Accounting Schools', 'National/Local', 'Big'),
  ('Adult Education', 'Local', 'Small'),
  ('After School Programs', 'Local', 'Small'),
  ('Allied Health Schools', 'National/Local', 'Big'),
  ('Auto Mechanic Schools', 'National/Local', 'Big'),
  ('Aviation Schools', 'National', 'Big'),
  ('Bartending Schools', 'Local', 'Small'),
  ('Beauty Schools', 'National/Local', 'Big'),
  ('Boards Of Education', 'Local', 'Small'),
  ('Business Coaching', 'National/Local', 'Big'),
  ('Business Colleges', 'National', 'Big'),
  ('Business Training', 'National/Local', 'Big'),
  ('CPR Instruction', 'Local', 'Small'),
  ('Career & Vocational Counseling', 'National/Local', 'Big'),
  ('Child Development Centers', 'Local', 'Small'),
  ('College Financial Planning', 'National', 'Big'),
  ('College Prep Schools', 'Local', 'Small'),
  ('Colleges', 'National', 'Big'),
  ('Community Colleges', 'National/Local', 'Big'),
  ('Computer Classes', 'National/Local', 'Big'),
  ('Computer Schools', 'National', 'Big'),
  ('Computer Training', 'National/Local', 'Big'),
  ('Continuing Education', 'National/Local', 'Big'),
  ('Court Reporting Schools', 'National', 'Big'),
  ('Culinary Schools', 'National', 'Big'),
  ('Dance Instruction', 'Local', 'Small'),
  ('Dental Assistant Schools', 'National', 'Big'),
  ('Educational Administration', 'National', 'Big'),
  ('Educational Consultants', 'National/Local', 'Big'),
  ('Educational Equipment & Supplies', 'National', 'Big'),
  ('Educational Loans', 'National', 'Big'),
  ('Educational Services', 'National/Local', 'Big'),
  ('Elementary & Secondary Schools', 'Local', 'Small'),
  ('Elementary Schools', 'Local', 'Small'),
  ('Fashion Schools', 'National', 'Big'),
  ('Graduate Schools', 'National', 'Big'),
  ('Graphic Arts Schools', 'National/Local', 'Big'),
  ('High Schools', 'Local', 'Small'),
  ('Home Schooling', 'National', 'Big'),
  ('Industrial & Technical Schools', 'National/Local', 'Big'),
  ('Interior Design Schools', 'National', 'Big'),
  ('Junior High Schools', 'Local', 'Small'),
  ('Language Schools', 'National/Local', 'Big'),
  ('Law Schools', 'National', 'Big'),
  ('Learning Centers', 'Local', 'Small'),
  ('Management & Leadership Development Training', 'National/Local', 'Big'),
  ('Management Training', 'National', 'Big'),
  ('Medical Assistant Schools', 'National', 'Big'),
  ('Medical Records Training', 'National', 'Big'),
  ('Medical Schools', 'National', 'Big'),
  ('Medical Secretary Schools', 'National', 'Big'),
  ('Military Schools', 'National', 'Big'),
  ('Nursing Schools', 'National', 'Big'),
  ('Online Education', 'National', 'Big'),
  ('Online Colleges', 'National', 'Big'),
  ('Other Schools & Instruction', 'National/Local', 'Big'),
  ('Paralegal Schools', 'National', 'Big'),
  ('Pet Grooming Schools', 'Local', 'Small'),
  ('Preschools', 'Local', 'Small'),
  ('Private Schools', 'Local', 'Small'),
  ('Public Schools', 'Local', 'Small'),
  ('Radiology Schools', 'National', 'Big'),
  ('Religious Schools', 'Local', 'Small'),
  ('Sales Training', 'National/Local', 'Big'),
  ('School Supplies', 'National', 'Big'),
  ('Secretarial Schools', 'National', 'Big'),
  ('Self Defense Instruction', 'Local', 'Small'),
  ('Sports Instruction', 'Local', 'Small'),
  ('Training Consultants', 'National', 'Big'),
  ('Tutoring', 'Local', 'Small'),
  ('Vocational & Technical Schools', 'National/Local', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Education'
ON CONFLICT DO NOTHING;

-- Fitness & Personal Care (58 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Barbers', 'Local', 'Small'),
  ('Barbers Equipment & Supplies', 'National', 'Big'),
  ('Beauticians', 'Local', 'Small'),
  ('Beauty Salon Equipment', 'National', 'Big'),
  ('Beauty Salon Equipment Wholesale', 'National', 'Big'),
  ('Beauty Salons', 'Local', 'Small'),
  ('Beauty Supplies', 'National/Local', 'Big'),
  ('Body Piercing', 'Local', 'Small'),
  ('Body Wraps', 'Local', 'Small'),
  ('Certified Massage Therapists', 'Local', 'Small'),
  ('Cosmetic Tattoos', 'Local', 'Small'),
  ('Cosmetics', 'National/Local', 'Big'),
  ('Dating Services', 'National', 'Big'),
  ('Day Spas', 'Local', 'Small'),
  ('Delivery Services', 'Local', 'Small'),
  ('Diapers & Diaper Service', 'Local', 'Small'),
  ('Ear Piercing', 'Local', 'Small'),
  ('Electrolysis', 'Local', 'Small'),
  ('Escorts', 'Local', 'Small'),
  ('Exercise & Physical Fitness Programs', 'Local', 'Small'),
  ('Facials', 'Local', 'Small'),
  ('Fitness Consultants', 'Local', 'Small'),
  ('Fitness Equipment', 'National/Local', 'Big'),
  ('Gymnastics Instruction', 'Local', 'Small'),
  ('Hair Coloring & Tinting', 'Local', 'Small'),
  ('Hair Care Products', 'National', 'Big'),
  ('Hair Clippers', 'National', 'Big'),
  ('Hair Goods', 'National/Local', 'Big'),
  ('Hair Implants', 'Local', 'Small'),
  ('Hair Removal', 'Local', 'Small'),
  ('Hair Replacement', 'Local', 'Small'),
  ('Hair Weaving', 'Local', 'Small'),
  ('Health & Beauty Aids', 'National', 'Big'),
  ('Health Clubs', 'Local', 'Small'),
  ('Health Resorts', 'Local', 'Small'),
  ('Laser Hair Removal', 'Local', 'Small'),
  ('Licensed Massage Therapists', 'Local', 'Small'),
  ('Manicures', 'Local', 'Small'),
  ('Martial Arts Equipment & Supplies', 'National', 'Big'),
  ('Massage Equipment & Supplies', 'National', 'Big'),
  ('Massage Schools', 'Local', 'Small'),
  ('Nail Salon Equipment Wholesale', 'National', 'Big'),
  ('Perfumes', 'National', 'Big'),
  ('Permanent Makeup', 'Local', 'Small'),
  ('Personal Services', 'Local', 'Small'),
  ('Personal Trainers', 'Local', 'Small'),
  ('Saunas', 'Local', 'Small'),
  ('Skin Care', 'National/Local', 'Big'),
  ('Tanning Beds', 'National', 'Big'),
  ('Tanning Equipment & Supplies', 'National', 'Big'),
  ('Tanning Salons', 'Local', 'Small'),
  ('Tattoo Removal', 'Local', 'Small'),
  ('Tattoos', 'Local', 'Small'),
  ('Waxing', 'Local', 'Small'),
  ('Weight Control Services', 'Local', 'Small'),
  ('Weights', 'National', 'Big'),
  ('Wigs & Hairpieces', 'National/Local', 'Big'),
  ('Yoga Instruction', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Fitness & Personal Care'
ON CONFLICT DO NOTHING;
