-- Part 4: Clothing & Accessories and Community and Government
-- Insert Clothing & Accessories Industry
INSERT INTO industries (id, name, description)
VALUES ('clothing-accessories', 'Clothing & Accessories', 'Fashion, apparel, and accessory businesses');

-- Insert Clothing & Accessories Niches (65 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('clothing-accessories', 'Baby Clothing', 'National', 50000),
('clothing-accessories', 'Boots', 'National', 50000),
('clothing-accessories', 'Bridal Shops', 'Local', 10000),
('clothing-accessories', 'Caps and Hats', 'National', 50000),
('clothing-accessories', 'Children''s Clothing', 'National', 50000),
('clothing-accessories', 'Clothing Alterations and Tailoring', 'Local', 10000),
('clothing-accessories', 'Consignment and Resale Shops', 'Local', 10000),
('clothing-accessories', 'Costumes', 'National', 50000),
('clothing-accessories', 'Custom and Personalized Clothing', 'National', 50000),
('clothing-accessories', 'Dancewear', 'National', 50000),
('clothing-accessories', 'Designer Clothing', 'National', 50000),
('clothing-accessories', 'Dresses', 'National', 50000),
('clothing-accessories', 'Dry Cleaning and Laundry Services', 'Local', 10000),
('clothing-accessories', 'Eyewear and Sunglasses', 'National', 50000),
('clothing-accessories', 'Fabric and Textiles', 'National', 50000),
('clothing-accessories', 'Fashion Accessories', 'National', 50000),
('clothing-accessories', 'Formal Wear', 'National', 50000),
('clothing-accessories', 'Fur and Leather Clothing', 'National', 50000),
('clothing-accessories', 'Handbags and Purses', 'National', 50000),
('clothing-accessories', 'Hosiery and Socks', 'National', 50000),
('clothing-accessories', 'Intimate Apparel and Lingerie', 'National', 50000),
('clothing-accessories', 'Jeans', 'National', 50000),
('clothing-accessories', 'Jewelry', 'National', 50000),
('clothing-accessories', 'Jewelry Repair and Restoration', 'Local', 10000),
('clothing-accessories', 'Maternity Wear', 'National', 50000),
('clothing-accessories', 'Men''s Clothing', 'National', 50000),
('clothing-accessories', 'Military and Tactical Apparel', 'National', 50000),
('clothing-accessories', 'Outdoor and Adventure Clothing', 'National', 50000),
('clothing-accessories', 'Outerwear and Coats', 'National', 50000),
('clothing-accessories', 'Pajamas and Sleepwear', 'National', 50000),
('clothing-accessories', 'Personal Stylists and Image Consultants', 'Local', 10000),
('clothing-accessories', 'Plus-Size Clothing', 'National', 50000),
('clothing-accessories', 'Promotional Products and Apparel', 'National', 50000),
('clothing-accessories', 'Scarves and Wraps', 'National', 50000),
('clothing-accessories', 'Scrubs and Medical Apparel', 'National', 50000),
('clothing-accessories', 'Secondhand and Vintage Clothing', 'Local', 10000),
('clothing-accessories', 'Shoe Repair and Restoration', 'Local', 10000),
('clothing-accessories', 'Shoes', 'National', 50000),
('clothing-accessories', 'Skate and Surf Apparel', 'National', 50000),
('clothing-accessories', 'Specialty and Niche Clothing', 'National', 50000),
('clothing-accessories', 'Sportswear and Activewear', 'National', 50000),
('clothing-accessories', 'Suits', 'National', 50000),
('clothing-accessories', 'Sustainable and Eco-Friendly Fashion', 'National', 50000),
('clothing-accessories', 'Swimwear', 'National', 50000),
('clothing-accessories', 'T-Shirts', 'National', 50000),
('clothing-accessories', 'Ties and Bow Ties', 'National', 50000),
('clothing-accessories', 'Uniform and Workwear', 'National', 50000),
('clothing-accessories', 'Vintage and Retro Clothing', 'National', 50000),
('clothing-accessories', 'Watches', 'National', 50000),
('clothing-accessories', 'Watch Repair and Restoration', 'Local', 10000),
('clothing-accessories', 'Wedding Accessories', 'Local', 10000),
('clothing-accessories', 'Western Wear', 'National', 50000),
('clothing-accessories', 'Women''s Clothing', 'National', 50000),
('clothing-accessories', 'Yoga and Fitness Apparel', 'National', 50000),
('clothing-accessories', 'Youth and Teen Clothing', 'National', 50000),
('clothing-accessories', 'Belts', 'National', 50000),
('clothing-accessories', 'Gloves and Mittens', 'National', 50000),
('clothing-accessories', 'Leather Goods', 'National', 50000),
('clothing-accessories', 'Safety Apparel and Protective Gear', 'National', 50000),
('clothing-accessories', 'Sewing and Alterations Services', 'Local', 10000),
('clothing-accessories', 'Shoe Accessories', 'National', 50000),
('clothing-accessories', 'Specialty Footwear', 'National', 50000),
('clothing-accessories', 'Underwear', 'National', 50000),
('clothing-accessories', 'Wallets', 'National', 50000),
('clothing-accessories', 'Work Boots and Safety Shoes', 'National', 50000);

-- Insert Community and Government Industry
INSERT INTO industries (id, name, description)
VALUES ('community-government', 'Community and Government', 'Public services and community organizations');

-- Insert Community and Government Niches (95 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('community-government', 'Adult Education and Literacy Programs', 'Local', 10000),
('community-government', 'Animal Control and Shelters', 'Local', 10000),
('community-government', 'Arts and Cultural Organizations', 'Local', 10000),
('community-government', 'Building and Zoning Departments', 'Local', 10000),
('community-government', 'Business Development and Economic Development', 'Local', 10000),
('community-government', 'Cemeteries and Funeral Services', 'Local', 10000),
('community-government', 'Chambers of Commerce', 'Local', 10000),
('community-government', 'Child and Family Services', 'Local', 10000),
('community-government', 'City and Town Halls', 'Local', 10000),
('community-government', 'Civic and Community Centers', 'Local', 10000),
('community-government', 'Civil Rights and Advocacy Organizations', 'National', 50000),
('community-government', 'Code Enforcement', 'Local', 10000),
('community-government', 'Community Centers', 'Local', 10000),
('community-government', 'Community Development and Planning', 'Local', 10000),
('community-government', 'Community Health Centers', 'Local', 10000),
('community-government', 'Conservation and Environmental Organizations', 'National', 50000),
('community-government', 'Consumer Protection Agencies', 'Local', 10000),
('community-government', 'Courts and Legal Services', 'Local', 10000),
('community-government', 'Cultural Heritage and Historic Preservation', 'Local', 10000),
('community-government', 'Disability Services and Support', 'Local', 10000),
('community-government', 'Disaster Relief and Emergency Services', 'Local', 10000),
('community-government', 'Economic Development Organizations', 'Local', 10000),
('community-government', 'Educational Foundations and Scholarships', 'Local', 10000),
('community-government', 'Elections and Voter Registration', 'Local', 10000),
('community-government', 'Emergency Management', 'Local', 10000),
('community-government', 'Employment and Job Training Services', 'Local', 10000),
('community-government', 'Environmental Health and Safety', 'Local', 10000),
('community-government', 'Fair Housing and Tenant Rights Organizations', 'Local', 10000),
('community-government', 'Faith-Based Organizations', 'Local', 10000),
('community-government', 'Family Support Services', 'Local', 10000),
('community-government', 'Fire Departments and Fire Safety', 'Local', 10000),
('community-government', 'Food Banks and Pantries', 'Local', 10000),
('community-government', 'Fraternal and Social Organizations', 'Local', 10000),
('community-government', 'Genealogical and Historical Societies', 'Local', 10000),
('community-government', 'Government Grant and Funding Programs', 'Local', 10000),
('community-government', 'Health Departments', 'Local', 10000),
('community-government', 'Homeless Shelters and Services', 'Local', 10000),
('community-government', 'Housing and Community Development', 'Local', 10000),
('community-government', 'Housing Assistance Programs', 'Local', 10000),
('community-government', 'Human Rights Organizations', 'National', 50000),
('community-government', 'Human Services', 'Local', 10000),
('community-government', 'Immigration and Refugee Services', 'Local', 10000),
('community-government', 'Judicial and Court Services', 'Local', 10000),
('community-government', 'Juvenile Justice and Youth Services', 'Local', 10000),
('community-government', 'Law Enforcement and Police Departments', 'Local', 10000),
('community-government', 'Legal Aid and Pro Bono Services', 'Local', 10000),
('community-government', 'Libraries', 'Local', 10000),
('community-government', 'Licensing and Permits', 'Local', 10000),
('community-government', 'Mediation and Dispute Resolution Services', 'Local', 10000),
('community-government', 'Mental Health and Counseling Services', 'Local', 10000),
('community-government', 'Neighborhood Associations', 'Local', 10000),
('community-government', 'Nonprofit Organizations', 'Local', 10000),
('community-government', 'Parks and Recreation Departments', 'Local', 10000),
('community-government', 'Parking Enforcement and Management', 'Local', 10000),
('community-government', 'Performing Arts and Theater Organizations', 'Local', 10000),
('community-government', 'Philanthropy and Charitable Foundations', 'National', 50000),
('community-government', 'Public Art and Sculpture Programs', 'Local', 10000),
('community-government', 'Public Health Services', 'Local', 10000),
('community-government', 'Public Housing Authorities', 'Local', 10000),
('community-government', 'Public Information and Communication', 'Local', 10000),
('community-government', 'Public Safety', 'Local', 10000),
('community-government', 'Public Transportation and Transit', 'Local', 10000),
('community-government', 'Public Utilities', 'Local', 10000),
('community-government', 'Public Works and Infrastructure', 'Local', 10000),
('community-government', 'Recycling and Waste Management', 'Local', 10000),
('community-government', 'Red Cross and Emergency Relief', 'Local', 10000),
('community-government', 'Religious Organizations', 'Local', 10000),
('community-government', 'Road and Highway Maintenance', 'Local', 10000),
('community-government', 'Sanitation and Solid Waste', 'Local', 10000),
('community-government', 'Senior Centers and Services', 'Local', 10000),
('community-government', 'Social Services', 'Local', 10000),
('community-government', 'Special Districts and Authorities', 'Local', 10000),
('community-government', 'Substance Abuse Treatment and Prevention', 'Local', 10000),
('community-government', 'Tax Collection and Assessment', 'Local', 10000),
('community-government', 'Tourism and Visitor Services', 'Local', 10000),
('community-government', 'Trade Associations and Professional Organizations', 'National', 50000),
('community-government', 'Traffic Management and Control', 'Local', 10000),
('community-government', 'Transportation Planning', 'Local', 10000),
('community-government', 'Urban Planning and Development', 'Local', 10000),
('community-government', 'Veterans Services and Support', 'Local', 10000),
('community-government', 'Victim Services and Support', 'Local', 10000),
('community-government', 'Volunteer Organizations', 'Local', 10000),
('community-government', 'Water and Sewer Services', 'Local', 10000),
('community-government', 'Wildlife and Animal Welfare Organizations', 'Local', 10000),
('community-government', 'Youth Programs and Services', 'Local', 10000),
('community-government', 'Zoning and Planning Commissions', 'Local', 10000),
('community-government', 'Affordable Housing Advocacy', 'Local', 10000),
('community-government', 'Community Outreach Programs', 'Local', 10000),
('community-government', 'Forestry and Natural Resources', 'Local', 10000),
('community-government', 'Homelessness Prevention Programs', 'Local', 10000),
('community-government', 'Literacy and Education Programs', 'Local', 10000),
('community-government', 'Neighborhood Watch Programs', 'Local', 10000),
('community-government', 'Public Records and Archives', 'Local', 10000),
('community-government', 'Rural Development Programs', 'Local', 10000),
('community-government', 'Workforce Development', 'Local', 10000);
