-- Hospitality & Food (83 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('American Cuisine Restaurants', 'Local', 'Small'),
  ('Asian Restaurants', 'Local', 'Small'),
  ('BBQ Restaurants', 'Local', 'Small'),
  ('Bagel Shops', 'Local', 'Small'),
  ('Wholesale Baked Goods Manufacturers', 'National', 'Big'),
  ('Retail Bakeries', 'Local', 'Small'),
  ('Banquet Halls and Rooms', 'Local', 'Small'),
  ('Bar and Grill Establishments', 'Local', 'Small'),
  ('Bar Equipment Suppliers', 'National', 'Big'),
  ('Bottled and Bulk Water Retailers', 'Local', 'Small'),
  ('Breakfast and Brunch Cafes', 'Local', 'Small'),
  ('Breweries and Craft Beer Makers', 'National/Loca', 'Big'),
  ('Buffet-Style Restaurants', 'Local', 'Small'),
  ('Burger Joints', 'Local', 'Small'),
  ('Coffeehouses and Cafes', 'Local', 'Small'),
  ('Cajun and Creole Restaurants', 'Local', 'Small'),
  ('Cake and Pastry Shops', 'Local', 'Small'),
  ('Candy and Confectionery Retail', 'Local', 'Small'),
  ('Candy and Cookie Arrangement Services', 'Local', 'Small'),
  ('Catering Services', 'Local', 'Small'),
  ('Fried Chicken Restaurants', 'Local', 'Small'),
  ('Chinese Restaurants', 'Local', 'Small'),
  ('Chinese Grocery and Food Retail', 'Local', 'Small'),
  ('Cigarette and Cigar Accessories Retail', 'Local', 'Small'),
  ('Tobacco and Cigarette Retailers', 'Local', 'Small'),
  ('Coffee and Tea Specialty Shops', 'Local', 'Small'),
  ('Delicatessen Retailers', 'Local', 'Small'),
  ('Diners and Family Cafes', 'Local', 'Small'),
  ('Dinner Theater Venues', 'Local', 'Small'),
  ('Donut Shops', 'Local', 'Small'),
  ('Family-Style Restaurants', 'Local', 'Small'),
  ('Fast Food Chains', 'National', 'Big'),
  ('Quick Service and Takeout Restaurants', 'Local', 'Small'),
  ('Fine Dining Establishments', 'Local', 'Small'),
  ('Seafood Retailers', 'Local', 'Small'),
  ('Food Delivery Services', 'National/Loca', 'Big'),
  ('Beverage and Food Service Providers', 'National/Loca', 'Big'),
  ('Food Product Retailers', 'National/Loca', 'Big'),
  ('Wholesale Food Product Manufacturers', 'National', 'Big'),
  ('French Cuisine Restaurants', 'Local', 'Small'),
  ('German Restaurants', 'Local', 'Small'),
  ('Greek Cuisine Restaurants', 'Local', 'Small'),
  ('Supermarkets and Grocery Chains', 'National/Loca', 'Big'),
  ('Health and Organic Food Stores', 'Local', 'Small'),
  ('Ice Cream and Frozen Yogurt Parlors', 'Local', 'Small'),
  ('Indian Cuisine Restaurants', 'Local', 'Small'),
  ('Irish Pubs and Restaurants', 'Local', 'Small'),
  ('Italian Food Retail', 'Local', 'Small'),
  ('Japanese Cuisine Restaurants', 'Local', 'Small'),
  ('Commercial Kitchen Equipment Suppliers', 'National', 'Big'),
  ('Korean Cuisine Restaurants', 'Local', 'Small'),
  ('Kosher Food and Restaurants', 'Local', 'Small'),
  ('Liquor and Wine Retail Stores', 'Local', 'Small'),
  ('Lunch Cafes and Bistros', 'Local', 'Small'),
  ('Meat and Butcher Shops', 'Local', 'Small'),
  ('Mexican Grocery and Foods Retail', 'Local', 'Small'),
  ('Mexican Restaurants', 'Local', 'Small'),
  ('Middle Eastern Restaurants', 'Local', 'Small'),
  ('Oriental Food and Goods Retailers', 'Local', 'Small'),
  ('Pizza Delivery Services', 'National/Loca', 'Big'),
  ('Pub and Tavern Establishments', 'Local', 'Small'),
  ('Restaurant Equipment Retail', 'National', 'Big'),
  ('Restaurant Equipment and Service Providers', 'National/Loca', 'Big'),
  ('Wholesale Restaurant Supplies', 'National', 'Big'),
  ('General Restaurants', 'Local', 'Small'),
  ('Sandwich Shops', 'Local', 'Small'),
  ('Seafood Restaurants', 'Local', 'Small'),
  ('Soul Food Restaurants', 'Local', 'Small'),
  ('Spanish Cuisine Restaurants', 'Local', 'Small'),
  ('Gourmet and Specialty Food Retailers', 'National', 'Big'),
  ('Sports Bars', 'Local', 'Small'),
  ('Steak and Seafood Grills', 'Local', 'Small'),
  ('Steakhouses', 'Local', 'Small'),
  ('Sushi Bars', 'Local', 'Small'),
  ('Taverns and Breweries', 'Local', 'Small'),
  ('Thai Cuisine Restaurants', 'Local', 'Small'),
  ('Used Restaurant Equipment Stores', 'Local', 'Small'),
  ('Vegetarian and Vegan Restaurants', 'Local', 'Small'),
  ('Vending Machine Suppliers', 'National', 'Big'),
  ('Water Coolers and Fountain Suppliers', 'National', 'Big'),
  ('Wedding Catering Services', 'Local', 'Small'),
  ('Wine and Spirit Retail Stores', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Hospitality & Food'
ON CONFLICT DO NOTHING;

-- Media & Comms (43 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('800 & 900 Phone Lines', 'National', 'Big'),
  ('Answering Services', 'National/Loca', 'Big'),
  ('Book Publishers', 'National', 'Big'),
  ('Business Answering Services', 'National/Loca', 'Big'),
  ('Business Cell Phone Equipment Suppliers', 'National', 'Big'),
  ('Business Phone Systems', 'National', 'Big'),
  ('Cell Phone Retailers', 'National/Loca', 'Big'),
  ('Cell Phone Accessories Dealers', 'National', 'Big'),
  ('Cellular PCS Providers', 'National', 'Big'),
  ('Check Printing Services', 'National/Loca', 'Big'),
  ('Color Printing Services', 'Local', 'Small'),
  ('Commercial Sign Makers', 'Local', 'Small'),
  ('Coupon and Ticket Printing Services', 'Local', 'Small'),
  ('Custom Sign Makers', 'Local', 'Small'),
  ('Data Communications Cabling Services', 'Local', 'Small'),
  ('Etching and Engraving Services', 'Local', 'Small'),
  ('Home Phone Services', 'National', 'Big'),
  ('Legal and Financial Printing Services', 'Local', 'Small'),
  ('Lithographers', 'Local', 'Small'),
  ('Magazine and Journal Publishers', 'National', 'Big'),
  ('Magazine Subscription Services', 'National', 'Big'),
  ('Outdoor Advertising and Billboards', 'National/Loca', 'Big'),
  ('Phone Card Retailers', 'National', 'Big'),
  ('Phone Line Installation Services', 'Local', 'Small'),
  ('Phone Repair Services', 'Local', 'Small'),
  ('Phone Service Providers', 'National', 'Big'),
  ('Business Phone Systems Providers', 'National', 'Big'),
  ('Physician Answering Services', 'Local', 'Small'),
  ('Radio Stations', 'National/Loca', 'Big'),
  ('Ringtones Providers', 'National', 'Big'),
  ('Wholesale Sign Manufacturers', 'National', 'Big'),
  ('Silk Screen Printing Services', 'Local', 'Small'),
  ('Telecommunications Equipment Dealers', 'National', 'Big'),
  ('Telecom Equipment Repair Services', 'Local', 'Small'),
  ('Telecommunications Services', 'National', 'Big'),
  ('Television Stations', 'National', 'Big'),
  ('Voice Mail Systems Providers', 'National', 'Big'),
  ('Voice Mail Services', 'Local', 'Small'),
  ('VOIP (Voice Over Internet Protocol) Providers', 'National', 'Big'),
  ('Wireless Data Services', 'National', 'Big'),
  ('Wireless Internet Providers', 'National', 'Big'),
  ('Yard Sign Makers', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Media & Comms'
ON CONFLICT DO NOTHING;
