-- Part 5: Computer & Tech and Construction & Tradesmen
-- Insert Computer & Tech Industry
INSERT INTO industries (id, name, description)
VALUES ('computer-tech', 'Computer & Tech', 'Technology services and products');

-- Insert Computer & Tech Niches (72 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('computer-tech', 'Computer Repair and Support', 'Local', 10000),
('computer-tech', 'IT Consulting and Services', 'National', 50000),
('computer-tech', 'Network Installation and Support', 'Local', 10000),
('computer-tech', 'Software Development', 'National', 50000),
('computer-tech', 'Web Design and Development', 'National', 50000),
('computer-tech', 'Computer Training and Education', 'Local', 10000),
('computer-tech', 'Data Recovery Services', 'National', 50000),
('computer-tech', 'Computer Hardware Sales', 'National', 50000),
('computer-tech', 'Computer Software Sales', 'National', 50000),
('computer-tech', 'Managed IT Services', 'National', 50000),
('computer-tech', 'Cloud Computing Services', 'National', 50000),
('computer-tech', 'Cybersecurity Services', 'National', 50000),
('computer-tech', 'Mobile App Development', 'National', 50000),
('computer-tech', 'E-commerce Solutions', 'National', 50000),
('computer-tech', 'Database Management', 'National', 50000),
('computer-tech', 'Server Installation and Maintenance', 'Local', 10000),
('computer-tech', 'VoIP and Telecommunications', 'National', 50000),
('computer-tech', 'Computer Accessories and Peripherals', 'National', 50000),
('computer-tech', 'Gaming Computers and Equipment', 'National', 50000),
('computer-tech', 'Point of Sale (POS) Systems', 'National', 50000),
('computer-tech', 'Computer Networking Equipment', 'National', 50000),
('computer-tech', 'Audio and Video Equipment', 'National', 50000),
('computer-tech', 'Home Automation and Smart Home', 'National', 50000),
('computer-tech', 'Computer Upgrade Services', 'Local', 10000),
('computer-tech', 'Backup and Disaster Recovery', 'National', 50000),
('computer-tech', 'Wireless and Mobile Solutions', 'National', 50000),
('computer-tech', 'Virtual and Augmented Reality', 'National', 50000),
('computer-tech', 'Artificial Intelligence and Machine Learning', 'National', 50000),
('computer-tech', 'Blockchain and Cryptocurrency Services', 'National', 50000),
('computer-tech', 'Computer Forensics and Investigation', 'National', 50000),
('computer-tech', 'IT Staffing and Recruitment', 'National', 50000),
('computer-tech', 'Technical Writing and Documentation', 'National', 50000),
('computer-tech', 'Computer Testing and Quality Assurance', 'National', 50000),
('computer-tech', 'SEO and Digital Marketing', 'National', 50000),
('computer-tech', 'Social Media Management', 'National', 50000),
('computer-tech', 'Content Management Systems', 'National', 50000),
('computer-tech', 'Email Marketing Services', 'National', 50000),
('computer-tech', 'Video Production and Editing', 'National', 50000),
('computer-tech', 'Graphic Design Services', 'National', 50000),
('computer-tech', 'Animation and Motion Graphics', 'National', 50000),
('computer-tech', '3D Modeling and Rendering', 'National', 50000),
('computer-tech', 'User Experience (UX) Design', 'National', 50000),
('computer-tech', 'User Interface (UI) Design', 'National', 50000),
('computer-tech', 'Computer Consulting', 'National', 50000),
('computer-tech', 'IT Project Management', 'National', 50000),
('computer-tech', 'DevOps Services', 'National', 50000),
('computer-tech', 'Internet Service Providers', 'Local', 10000),
('computer-tech', 'Web Hosting Services', 'National', 50000),
('computer-tech', 'Domain Registration Services', 'National', 50000),
('computer-tech', 'Computer Resale and Refurbishment', 'Local', 10000),
('computer-tech', 'Electronics Recycling', 'Local', 10000),
('computer-tech', 'Computer Cleaning and Maintenance', 'Local', 10000),
('computer-tech', 'Cable and Wiring Installation', 'Local', 10000),
('computer-tech', 'Printer Repair and Maintenance', 'Local', 10000),
('computer-tech', 'Computer Tutoring and Support', 'Local', 10000),
('computer-tech', 'Technology Integration Services', 'National', 50000),
('computer-tech', 'Digital Signage Solutions', 'National', 50000),
('computer-tech', 'Business Intelligence and Analytics', 'National', 50000),
('computer-tech', 'CRM Software and Services', 'National', 50000),
('computer-tech', 'ERP Systems and Implementation', 'National', 50000),
('computer-tech', 'IT Compliance and Auditing', 'National', 50000),
('computer-tech', 'Penetration Testing and Security Audits', 'National', 50000),
('computer-tech', 'IT Asset Management', 'National', 50000),
('computer-tech', 'Remote IT Support', 'National', 50000),
('computer-tech', 'Software as a Service (SaaS)', 'National', 50000),
('computer-tech', 'Platform as a Service (PaaS)', 'National', 50000),
('computer-tech', 'Infrastructure as a Service (IaaS)', 'National', 50000),
('computer-tech', 'API Development and Integration', 'National', 50000),
('computer-tech', 'Technology Training and Certification', 'National', 50000),
('computer-tech', 'IT Help Desk Services', 'National', 50000),
('computer-tech', 'Computer Maintenance Contracts', 'Local', 10000),
('computer-tech', 'Electronic Surveillance and Monitoring', 'National', 50000);

-- Insert Construction & Tradesmen Industry
INSERT INTO industries (id, name, description)
VALUES ('construction-tradesmen', 'Construction & Tradesmen', 'Construction and skilled trade services');

-- Insert Construction & Tradesmen Niches (90 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('construction-tradesmen', 'General Contractors', 'Local', 10000),
('construction-tradesmen', 'Residential Construction', 'Local', 10000),
('construction-tradesmen', 'Commercial Construction', 'National', 50000),
('construction-tradesmen', 'Remodeling and Renovation', 'Local', 10000),
('construction-tradesmen', 'Kitchen and Bath Remodeling', 'Local', 10000),
('construction-tradesmen', 'Home Additions', 'Local', 10000),
('construction-tradesmen', 'Basement Finishing', 'Local', 10000),
('construction-tradesmen', 'Deck and Patio Construction', 'Local', 10000),
('construction-tradesmen', 'Framing Contractors', 'Local', 10000),
('construction-tradesmen', 'Foundation and Concrete Contractors', 'Local', 10000),
('construction-tradesmen', 'Masonry and Bricklaying', 'Local', 10000),
('construction-tradesmen', 'Carpentry Services', 'Local', 10000),
('construction-tradesmen', 'Drywall Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Painting and Wall Covering', 'Local', 10000),
('construction-tradesmen', 'Flooring Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Tile and Stone Installation', 'Local', 10000),
('construction-tradesmen', 'Roofing Contractors', 'Local', 10000),
('construction-tradesmen', 'Siding Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Window and Door Installation', 'Local', 10000),
('construction-tradesmen', 'Insulation Installation', 'Local', 10000),
('construction-tradesmen', 'Electricians', 'Local', 10000),
('construction-tradesmen', 'Plumbers', 'Local', 10000),
('construction-tradesmen', 'HVAC Contractors', 'Local', 10000),
('construction-tradesmen', 'Demolition Services', 'Local', 10000),
('construction-tradesmen', 'Excavation and Earthwork', 'Local', 10000),
('construction-tradesmen', 'Grading and Leveling', 'Local', 10000),
('construction-tradesmen', 'Paving and Asphalt Services', 'Local', 10000),
('construction-tradesmen', 'Concrete and Cement Work', 'Local', 10000),
('construction-tradesmen', 'Septic System Installation', 'Local', 10000),
('construction-tradesmen', 'Well Drilling and Pump Services', 'Local', 10000),
('construction-tradesmen', 'Landscaping and Hardscaping', 'Local', 10000),
('construction-tradesmen', 'Irrigation System Installation', 'Local', 10000),
('construction-tradesmen', 'Fence Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Garage Door Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Custom Home Builders', 'Local', 10000),
('construction-tradesmen', 'Modular and Prefab Home Construction', 'National', 50000),
('construction-tradesmen', 'Log Home Construction', 'National', 50000),
('construction-tradesmen', 'Green and Sustainable Building', 'National', 50000),
('construction-tradesmen', 'Accessibility and ADA Compliance', 'Local', 10000),
('construction-tradesmen', 'Structural Engineering', 'Local', 10000),
('construction-tradesmen', 'Building Inspection Services', 'Local', 10000),
('construction-tradesmen', 'Architectural Services', 'Local', 10000),
('construction-tradesmen', 'Construction Management', 'National', 50000),
('construction-tradesmen', 'Project Management Services', 'National', 50000),
('construction-tradesmen', 'Construction Equipment Rental', 'Local', 10000),
('construction-tradesmen', 'Scaffolding and Shoring Services', 'Local', 10000),
('construction-tradesmen', 'Crane and Rigging Services', 'Local', 10000),
('construction-tradesmen', 'Sandblasting and Surface Preparation', 'Local', 10000),
('construction-tradesmen', 'Waterproofing and Moisture Control', 'Local', 10000),
('construction-tradesmen', 'Fireproofing Services', 'Local', 10000),
('construction-tradesmen', 'Acoustic and Soundproofing', 'Local', 10000),
('construction-tradesmen', 'Asbestos Abatement', 'Local', 10000),
('construction-tradesmen', 'Lead Paint Removal', 'Local', 10000),
('construction-tradesmen', 'Mold Remediation', 'Local', 10000),
('construction-tradesmen', 'Radon Mitigation', 'Local', 10000),
('construction-tradesmen', 'Site Preparation and Clearing', 'Local', 10000),
('construction-tradesmen', 'Land Surveying', 'Local', 10000),
('construction-tradesmen', 'Soil Testing and Analysis', 'Local', 10000),
('construction-tradesmen', 'Geotechnical Engineering', 'National', 50000),
('construction-tradesmen', 'Environmental Consulting', 'National', 50000),
('construction-tradesmen', 'Traffic Control and Safety Services', 'Local', 10000),
('construction-tradesmen', 'Building Materials Supply', 'Local', 10000),
('construction-tradesmen', 'Lumber and Building Supply', 'Local', 10000),
('construction-tradesmen', 'Hardware and Tools', 'Local', 10000),
('construction-tradesmen', 'Cabinet and Countertop Installation', 'Local', 10000),
('construction-tradesmen', 'Custom Cabinetry and Millwork', 'Local', 10000),
('construction-tradesmen', 'Glass and Glazing Contractors', 'Local', 10000),
('construction-tradesmen', 'Metal Fabrication and Welding', 'Local', 10000),
('construction-tradesmen', 'Steel Erection', 'Local', 10000),
('construction-tradesmen', 'Structural Steel Services', 'National', 50000),
('construction-tradesmen', 'Elevator Installation and Repair', 'National', 50000),
('construction-tradesmen', 'Escalator Services', 'National', 50000),
('construction-tradesmen', 'Fire Protection and Sprinkler Systems', 'Local', 10000),
('construction-tradesmen', 'Security Systems Installation', 'Local', 10000),
('construction-tradesmen', 'Communications and Data Cabling', 'Local', 10000),
('construction-tradesmen', 'Solar Panel Installation', 'Local', 10000),
('construction-tradesmen', 'Generator Installation and Repair', 'Local', 10000),
('construction-tradesmen', 'Swimming Pool Construction', 'Local', 10000),
('construction-tradesmen', 'Hot Tub and Spa Installation', 'Local', 10000),
('construction-tradesmen', 'Outdoor Kitchen Construction', 'Local', 10000),
('construction-tradesmen', 'Gazebo and Pergola Construction', 'Local', 10000),
('construction-tradesmen', 'Shed and Outbuilding Construction', 'Local', 10000),
('construction-tradesmen', 'Barn and Agricultural Building', 'Local', 10000),
('construction-tradesmen', 'Commercial Roofing', 'National', 50000),
('construction-tradesmen', 'Industrial Construction', 'National', 50000),
('construction-tradesmen', 'Tenant Improvement and Build-Out', 'Local', 10000),
('construction-tradesmen', 'Restoration and Historic Preservation', 'National', 50000),
('construction-tradesmen', 'Disaster Recovery and Reconstruction', 'National', 50000),
('construction-tradesmen', 'Weatherization Services', 'Local', 10000);
