-- Corrected all niche names to match document exactly, fixed "National/Loca" to "National/Local"
-- Hospitality & Food (83 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('American Restaurants', 'Local', 'Small'),
  ('Asian Restaurants', 'Local', 'Small'),
  ('BBQ', 'Local', 'Small'),
  ('Bagels', 'Local', 'Small'),
  ('Bakeries Wholesale', 'National', 'Big'),
  ('Bakeries', 'Local', 'Small'),
  ('Banquet Halls', 'Local', 'Small'),
  ('Bars & Grills', 'Local', 'Small'),
  ('Bartending Equipment & Supplies', 'National', 'Big'),
  ('Bottled Water', 'Local', 'Small'),
  ('Breakfast Restaurants', 'Local', 'Small'),
  ('Breweries', 'National/Local', 'Big'),
  ('Buffets', 'Local', 'Small'),
  ('Burgers', 'Local', 'Small'),
  ('Cafes', 'Local', 'Small'),
  ('Cajun', 'Local', 'Small'),
  ('Cakes', 'Local', 'Small'),
  ('Candy', 'Local', 'Small'),
  ('Candy & Cookie Bouquets', 'Local', 'Small'),
  ('Caterers', 'Local', 'Small'),
  ('Chicken', 'Local', 'Small'),
  ('Chinese Restaurants', 'Local', 'Small'),
  ('Chinese Food', 'Local', 'Small'),
  ('Cigar Accessories', 'Local', 'Small'),
  ('Cigarettes', 'Local', 'Small'),
  ('Coffee', 'Local', 'Small'),
  ('Deli', 'Local', 'Small'),
  ('Diners', 'Local', 'Small'),
  ('Dinner Theater', 'Local', 'Small'),
  ('Donuts', 'Local', 'Small'),
  ('Family Style Restaurants', 'Local', 'Small'),
  ('Fast Food', 'National', 'Big'),
  ('Fast Food Take Out', 'Local', 'Small'),
  ('Fine Dining', 'Local', 'Small'),
  ('Fish', 'Local', 'Small'),
  ('Food Delivery', 'National/Local', 'Big'),
  ('Food Service', 'National/Local', 'Big'),
  ('Food Stores', 'National/Local', 'Big'),
  ('Food Wholesale', 'National', 'Big'),
  ('French Restaurants', 'Local', 'Small'),
  ('German Restaurants', 'Local', 'Small'),
  ('Greek Restaurants', 'Local', 'Small'),
  ('Grocery Stores', 'National/Local', 'Big'),
  ('Health Food', 'Local', 'Small'),
  ('Ice Cream', 'Local', 'Small'),
  ('Indian Restaurants', 'Local', 'Small'),
  ('Irish Restaurants', 'Local', 'Small'),
  ('Italian Food', 'Local', 'Small'),
  ('Japanese Restaurants', 'Local', 'Small'),
  ('Kitchen Equipment', 'National', 'Big'),
  ('Korean Restaurants', 'Local', 'Small'),
  ('Kosher', 'Local', 'Small'),
  ('Liquor Stores', 'Local', 'Small'),
  ('Lunch', 'Local', 'Small'),
  ('Meat', 'Local', 'Small'),
  ('Mexican Food Products', 'Local', 'Small'),
  ('Mexican Restaurants', 'Local', 'Small'),
  ('Middle Eastern Restaurants', 'Local', 'Small'),
  ('Oriental Foods', 'Local', 'Small'),
  ('Pizza Delivery', 'National/Local', 'Big'),
  ('Pubs', 'Local', 'Small'),
  ('Restaurant Equipment', 'National', 'Big'),
  ('Restaurant Equipment & Supplies', 'National/Local', 'Big'),
  ('Restaurant Supplies Wholesale', 'National', 'Big'),
  ('Restaurants', 'Local', 'Small'),
  ('Sandwiches', 'Local', 'Small'),
  ('Seafood Restaurants', 'Local', 'Small'),
  ('Soul Food', 'Local', 'Small'),
  ('Spanish Restaurants', 'Local', 'Small'),
  ('Specialty Foods', 'National', 'Big'),
  ('Sports Bars', 'Local', 'Small'),
  ('Steak & Seafood', 'Local', 'Small'),
  ('Steakhouses', 'Local', 'Small'),
  ('Sushi Bars', 'Local', 'Small'),
  ('Taverns', 'Local', 'Small'),
  ('Thai Restaurants', 'Local', 'Small'),
  ('Used Restaurant Equipment', 'Local', 'Small'),
  ('Vegetarian', 'Local', 'Small'),
  ('Vending Machines', 'National', 'Big'),
  ('Water Coolers', 'National', 'Big'),
  ('Wedding Caterers', 'Local', 'Small'),
  ('Wine & Spirits', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Hospitality & Food'
ON CONFLICT DO NOTHING;

-- Media & Comms (43 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('800 & 900 Numbers', 'National', 'Big'),
  ('Answering Services', 'National/Local', 'Big'),
  ('Book Publishers', 'National', 'Big'),
  ('Business Answering Services', 'National/Local', 'Big'),
  ('Business Cell Phones', 'National', 'Big'),
  ('Business Phone Systems', 'National', 'Big'),
  ('Cell Phones', 'National/Local', 'Big'),
  ('Cell Phone Accessories', 'National', 'Big'),
  ('Cellular PCS', 'National', 'Big'),
  ('Check Printing', 'National/Local', 'Big'),
  ('Color Printing', 'Local', 'Small'),
  ('Commercial Signs', 'Local', 'Small'),
  ('Coupons', 'Local', 'Small'),
  ('Custom Signs', 'Local', 'Small'),
  ('Data Communications', 'Local', 'Small'),
  ('Engraving', 'Local', 'Small'),
  ('Home Phone Service', 'National', 'Big'),
  ('Legal & Financial Printing', 'Local', 'Small'),
  ('Lithographers', 'Local', 'Small'),
  ('Magazines', 'National', 'Big'),
  ('Magazine Subscriptions', 'National', 'Big'),
  ('Outdoor Advertising', 'National/Local', 'Big'),
  ('Phone Cards', 'National', 'Big'),
  ('Phone Lines', 'Local', 'Small'),
  ('Phone Repair', 'Local', 'Small'),
  ('Phone Service', 'National', 'Big'),
  ('Phone Systems', 'National', 'Big'),
  ('Physicians Answering Services', 'Local', 'Small'),
  ('Radio Stations', 'National/Local', 'Big'),
  ('Ringtones', 'National', 'Big'),
  ('Signs Wholesale', 'National', 'Big'),
  ('Silk Screen Printing', 'Local', 'Small'),
  ('Telecom Equipment', 'National', 'Big'),
  ('Telecom Equipment Repair', 'Local', 'Small'),
  ('Telecommunications', 'National', 'Big'),
  ('Television Stations', 'National', 'Big'),
  ('Voice Mail Equipment', 'National', 'Big'),
  ('Voice Mail Service', 'Local', 'Small'),
  ('VOIP', 'National', 'Big'),
  ('Wireless Data', 'National', 'Big'),
  ('Wireless Internet', 'National', 'Big'),
  ('Yard Signs', 'Local', 'Small'),
  ('Yellow Pages Advertising', 'National', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Media & Comms'
ON CONFLICT DO NOTHING;
