-- Corrected all niche names to match document exactly, fixed "National/Loca" to "National/Local"
-- Real Estate (66 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Apartment Buildings', 'Local', 'Small'),
  ('Apartment Finding Service', 'Local', 'Small'),
  ('Apartment Rental Agencies', 'National/Local', 'Big'),
  ('Apartments', 'Local', 'Small'),
  ('Architects', 'Local', 'Small'),
  ('Assisted Living', 'Local', 'Small'),
  ('Building & Property Management', 'National/Local', 'Big'),
  ('Condo & Townhouse Management', 'National/Local', 'Big'),
  ('Condo & Townhouse Rental Agencies', 'Local', 'Small'),
  ('Condo Office Space', 'Local', 'Small'),
  ('Condominiums', 'Local', 'Small'),
  ('Custom Home Builders', 'Local', 'Small'),
  ('Executive Suites', 'National/Local', 'Big'),
  ('Extended Stay Hotels', 'National', 'Big'),
  ('Farm & Ranch Real Estate', 'Local', 'Small'),
  ('Furnished Apartments', 'Local', 'Small'),
  ('Golf Course Architects', 'National', 'Big'),
  ('Home Equity Loans', 'National', 'Big'),
  ('Homeowners Insurance', 'National', 'Big'),
  ('Homes', 'Local', 'Small'),
  ('Homes For Rent', 'Local', 'Small'),
  ('Land Development', 'National/Local', 'Big'),
  ('Landscape Planning', 'Local', 'Small'),
  ('Mobile Home Insurance', 'National', 'Big'),
  ('Mobile Home Parks', 'Local', 'Small'),
  ('Mobile Home Repairs', 'Local', 'Small'),
  ('Mobile Home Transporting', 'Local', 'Small'),
  ('Mortgage Amortization', 'National', 'Big'),
  ('Mortgage Brokers', 'National/Local', 'Big'),
  ('Mortgage Companies', 'National', 'Big'),
  ('Mortgage Refinance', 'National', 'Big'),
  ('Mortgages', 'National', 'Big'),
  ('Mortgages Commercial', 'National', 'Big'),
  ('Office Buildings', 'Local', 'Small'),
  ('Office Space', 'Local', 'Small'),
  ('Property Maintenance', 'Local', 'Small'),
  ('Property Management', 'National/Local', 'Big'),
  ('Real Estate', 'Local', 'Small'),
  ('Real Estate Residential', 'Local', 'Small'),
  ('Retirement Communities', 'Local', 'Small'),
  ('Retirement Housing', 'Local', 'Small'),
  ('Reverse Mortgages', 'National', 'Big'),
  ('Short Term Housing', 'National/Local', 'Big'),
  ('Timeshares', 'National', 'Big'),
  ('Title Insurance', 'National', 'Big'),
  ('Unfurnished Apartments', 'Local', 'Small'),
  ('Used Mobile Homes', 'Local', 'Small'),
  ('Real Estate Agencies', 'Local', 'Small'),
  ('Real Estate Agents', 'Local', 'Small'),
  ('Real Estate Appraisers', 'Local', 'Small'),
  ('Real Estate Attorneys', 'Local', 'Small'),
  ('Real Estate Brokers', 'Local', 'Small'),
  ('Real Estate Buyer Brokers', 'Local', 'Small'),
  ('Real Estate Buyer Representatives', 'Local', 'Small'),
  ('Real Estate Commercial & Industrial', 'National/Local', 'Big'),
  ('Real Estate Consultants', 'Local', 'Small'),
  ('Real Estate Developers', 'National/Local', 'Big'),
  ('Real Estate Foreclosures', 'National/Local', 'Big'),
  ('Real Estate Home Inspection', 'Local', 'Small'),
  ('Real Estate Investment', 'National/Local', 'Big'),
  ('Real Estate Loans', 'National', 'Big'),
  ('Real Estate Rental Service', 'Local', 'Small'),
  ('Real Estate Rental Services', 'Local', 'Small'),
  ('Real Estate Schools', 'National/Local', 'Big'),
  ('Real Estate Title Search', 'National/Local', 'Big'),
  ('Residential Real Estate', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Real Estate'
ON CONFLICT DO NOTHING;

-- Shopping & Retail (74 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Artificial Flowers & Trees', 'National', 'Big'),
  ('Baby Products', 'National/Local', 'Big'),
  ('Balloons', 'Local', 'Small'),
  ('Ballrooms', 'Local', 'Small'),
  ('Birthday Parties', 'Local', 'Small'),
  ('Bookstores', 'National/Local', 'Big'),
  ('Bridal Headpieces & Veils', 'Local', 'Small'),
  ('Bridal Registries', 'National', 'Big'),
  ('Candle Supplies', 'Local', 'Small'),
  ('Cards', 'Local', 'Small'),
  ('Children''s Parties', 'Local', 'Small'),
  ('Coins & Stamps', 'Local', 'Small'),
  ('Collectibles', 'Local', 'Small'),
  ('Consignment Service', 'Local', 'Small'),
  ('Consumer Electronics', 'National', 'Big'),
  ('Convenience Stores', 'Local', 'Small'),
  ('Corporate Gift Baskets', 'National/Local', 'Big'),
  ('Corporate Gifts', 'National/Local', 'Big'),
  ('Department Stores', 'National', 'Big'),
  ('Disc Jockeys', 'Local', 'Small'),
  ('Discount Stores', 'National', 'Big'),
  ('Factory Outlets', 'National', 'Big'),
  ('Flags, Banners, & Pennants', 'National', 'Big'),
  ('Flea Markets', 'Local', 'Small'),
  ('Floral Wire Services', 'National', 'Big'),
  ('Florists', 'Local', 'Small'),
  ('Fruit Baskets', 'Local', 'Small'),
  ('Funeral Flowers', 'Local', 'Small'),
  ('Games & Supplies', 'Local', 'Small'),
  ('General Stores', 'Local', 'Small'),
  ('Gift Baskets', 'National/Local', 'Big'),
  ('Gift Shops', 'Local', 'Small'),
  ('Hair Braiding', 'Local', 'Small'),
  ('Hobby & Model Shops', 'Local', 'Small'),
  ('Inflatables', 'Local', 'Small'),
  ('Invitations & Announcements', 'Local', 'Small'),
  ('Leather Goods', 'National/Local', 'Big'),
  ('Luggage', 'National/Local', 'Big'),
  ('Maps', 'Local', 'Small'),
  ('Newsstands', 'Local', 'Small'),
  ('Notary & Corporation Seals', 'Local', 'Small'),
  ('Online Shopping', 'National', 'Big'),
  ('Outlet Malls', 'National', 'Big'),
  ('Party Entertainment', 'Local', 'Small'),
  ('Party Facilities', 'Local', 'Small'),
  ('Party Favors', 'Local', 'Small'),
  ('Party Supplies', 'Local', 'Small'),
  ('Pawn Brokers', 'Local', 'Small'),
  ('Plaques', 'Local', 'Small'),
  ('Postcards', 'Local', 'Small'),
  ('Second Hand Stores', 'Local', 'Small'),
  ('Shopping Centers', 'National/Local', 'Big'),
  ('Shopping Services', 'Local', 'Small'),
  ('Singing Telegrams', 'Local', 'Small'),
  ('Specialty Stores', 'National/Local', 'Big'),
  ('Sports Memorabilia', 'Local', 'Small'),
  ('Thrift Stores', 'Local', 'Small'),
  ('Toy Stores', 'National/Local', 'Big'),
  ('Travel Accessories', 'National/Local', 'Big'),
  ('Trophies', 'Local', 'Small'),
  ('Trophy Shops', 'Local', 'Small'),
  ('Used & Rare Books', 'Local', 'Small'),
  ('Variety Stores', 'National', 'Big'),
  ('Video Games', 'National/Local', 'Big'),
  ('Wedding Chapels', 'Local', 'Small'),
  ('Wedding Facilities', 'Local', 'Small'),
  ('Wedding Flowers', 'Local', 'Small'),
  ('Wedding Gifts', 'Local', 'Small'),
  ('Wedding Invitations', 'Local', 'Small'),
  ('Wedding Planners', 'Local', 'Small'),
  ('Wedding Receptions', 'Local', 'Small'),
  ('Wedding Services', 'Local', 'Small'),
  ('Weddings', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Shopping & Retail'
ON CONFLICT DO NOTHING;
