-- Real Estate (66 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Apartment Building Owners', 'Local', 'Small'),
  ('Apartment Information and Referral Services', 'Local', 'Small'),
  ('Apartment Rental Agencies', 'National/Loca', 'Big'),
  ('Apartment Rentals', 'Local', 'Small'),
  ('Residential Architects', 'Local', 'Small'),
  ('Assisted Living Facilities', 'Local', 'Small'),
  ('Commercial and Industrial Property Leasing', 'National/Loca', 'Big'),
  ('Condominium and Townhouse Management', 'National/Loca', 'Big'),
  ('Condominium and Townhouse Rental Agencies', 'Local', 'Small'),
  ('Condo Office Space Rental', 'Local', 'Small'),
  ('Condominiums and Townhouses', 'Local', 'Small'),
  ('Custom Home Builders', 'Local', 'Small'),
  ('Executive Office Suites', 'National/Loca', 'Big'),
  ('Extended Stay Hotels', 'National', 'Big'),
  ('Farm and Ranch Real Estate', 'Local', 'Small'),
  ('Furnished Apartment Rentals', 'Local', 'Small'),
  ('Golf Course Architects', 'National', 'Big'),
  ('Home Equity Loan Providers', 'National', 'Big'),
  ('Homeowners Insurance Providers', 'National', 'Big'),
  ('Residential Real Estate Agencies', 'Local', 'Small'),
  ('Home Rental Services', 'Local', 'Small'),
  ('Land Development Companies', 'National/Loca', 'Big'),
  ('Landscape Planning Services', 'Local', 'Small'),
  ('Mobile Home Insurance Providers', 'National', 'Big'),
  ('Mobile Home Parks and Communities', 'Local', 'Small'),
  ('Mobile Home Repair Services', 'Local', 'Small'),
  ('Mobile Home Transportation Services', 'Local', 'Small'),
  ('Mortgage Amortization Services', 'National', 'Big'),
  ('Mortgage Brokers', 'National/Loca', 'Big'),
  ('Mortgage Companies', 'National', 'Big'),
  ('Mortgage Refinancing Services', 'National', 'Big'),
  ('Mortgage Providers', 'National', 'Big'),
  ('Commercial Mortgage Providers', 'National', 'Big'),
  ('Office Buildings and Parks', 'Local', 'Small'),
  ('Office Space Rental', 'Local', 'Small'),
  ('Property Maintenance Services', 'Local', 'Small'),
  ('Property Management Companies', 'National/Loca', 'Big'),
  ('Real Estate Agencies', 'Local', 'Small'),
  ('Residential Real Estate', 'Local', 'Small'),
  ('Retirement Communities', 'Local', 'Small'),
  ('Retirement Housing', 'Local', 'Small'),
  ('Reverse Mortgage Providers', 'National', 'Big'),
  ('Temporary Housing Services', 'National/Loca', 'Big'),
  ('Timeshare Sales and Rentals', 'National', 'Big'),
  ('Title Insurance Companies', 'National', 'Big'),
  ('Unfurnished Apartment Rentals', 'Local', 'Small'),
  ('Used Modular and Mobile Home Sales', 'Local', 'Small'),
  ('Real Estate Agencies and Brokerages', 'Local', 'Small'),
  ('Real Estate Agents', 'Local', 'Small'),
  ('Real Estate Appraisers', 'Local', 'Small'),
  ('Real Estate Attorneys', 'Local', 'Small'),
  ('Real Estate Brokers', 'Local', 'Small'),
  ('Buyer Representation Brokers', 'Local', 'Small'),
  ('Real Estate Buyer Consultants', 'Local', 'Small'),
  ('Commercial and Industrial Real Estate', 'National/Loca', 'Big'),
  ('Real Estate Consultants', 'Local', 'Small'),
  ('Real Estate Developers and Subdividers', 'National/Loca', 'Big'),
  ('Foreclosure Assistance Services', 'National/Loca', 'Big'),
  ('Home Inspection Services', 'Local', 'Small'),
  ('Real Estate Investment Services', 'National/Loca', 'Big'),
  ('Real Estate Loan Services', 'National', 'Big'),
  ('Property Rental and Leasing', 'Local', 'Small'),
  ('Rental Information and Referral Services', 'Local', 'Small'),
  ('Real Estate Schools', 'National/Loca', 'Big'),
  ('Title Search and Abstract Services', 'National/Loca', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Real Estate'
ON CONFLICT DO NOTHING;

-- Shopping & Retail (74 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Artificial Flowers & Trees Retail', 'National', 'Big'),
  ('Baby Products & Services', 'National/Loca', 'Big'),
  ('Balloon Retail & Delivery Services', 'Local', 'Small'),
  ('Ballrooms', 'Local', 'Small'),
  ('Birthday Party Services', 'Local', 'Small'),
  ('Bookstores', 'National/Loca', 'Big'),
  ('Bridal Headpieces & Veils Retail', 'Local', 'Small'),
  ('Bridal Registries', 'National', 'Big'),
  ('Candle Supplies Retail', 'Local', 'Small'),
  ('Card Shops', 'Local', 'Small'),
  ('Children''s Party Services', 'Local', 'Small'),
  ('Coin & Stamp Dealers', 'Local', 'Small'),
  ('Collectibles Dealers', 'Local', 'Small'),
  ('Consignment Shops', 'Local', 'Small'),
  ('Consumer Electronics Stores', 'National', 'Big'),
  ('Convenience Stores', 'Local', 'Small'),
  ('Corporate Gift Basket Services', 'National/Loca', 'Big'),
  ('Corporate Gift Retailers', 'National/Loca', 'Big'),
  ('Department Stores', 'National', 'Big'),
  ('Disc Jockey Services', 'Local', 'Small'),
  ('Discount Stores', 'National', 'Big'),
  ('Factory Outlets', 'National', 'Big'),
  ('Flags, Banners, and Pennants Retail', 'National', 'Big'),
  ('Flea Markets', 'Local', 'Small'),
  ('Floral Wire Services', 'National', 'Big'),
  ('Florists', 'Local', 'Small'),
  ('Fruit Basket Retailers', 'Local', 'Small'),
  ('Funeral Flower Services', 'Local', 'Small'),
  ('Game & Supplies Dealers', 'Local', 'Small'),
  ('General Stores', 'Local', 'Small'),
  ('Gift Basket Retailers', 'National/Loca', 'Big'),
  ('Gift Shops', 'Local', 'Small'),
  ('Hair Braiding Services', 'Local', 'Small'),
  ('Hobby & Model Stores', 'Local', 'Small'),
  ('Inflatables Rental & Sales', 'Local', 'Small'),
  ('Invitations & Announcements Retail', 'Local', 'Small'),
  ('Leather Goods Retail', 'National/Loca', 'Big'),
  ('Luggage Stores', 'National/Loca', 'Big'),
  ('Maps & Globes Retail', 'Local', 'Small'),
  ('Newspaper & Magazine Retailers', 'Local', 'Small'),
  ('Notary & Corporation Seals Retail', 'Local', 'Small'),
  ('Online Shopping', 'National', 'Big'),
  ('Outlet Malls', 'National', 'Big'),
  ('Party Entertainment Services', 'Local', 'Small'),
  ('Party Facilities', 'Local', 'Small'),
  ('Party Favors Retail', 'Local', 'Small'),
  ('Party Supplies Retail', 'Local', 'Small'),
  ('Pawn Brokers', 'Local', 'Small'),
  ('Plaques Retail', 'Local', 'Small'),
  ('Postcard Retailers', 'Local', 'Small'),
  ('Second-Hand Merchandise Stores', 'Local', 'Small'),
  ('Shopping Centers & Malls', 'National/Loca', 'Big'),
  ('Shopping Services', 'Local', 'Small'),
  ('Singing Telegrams', 'Local', 'Small'),
  ('Specialty Stores', 'National/Loca', 'Big'),
  ('Sports Cards & Memorabilia Dealers', 'Local', 'Small'),
  ('Thrift Stores', 'Local', 'Small'),
  ('Toy Stores', 'National/Loca', 'Big'),
  ('Travel Accessories Retailers', 'National/Loca', 'Big'),
  ('Trophies, Medals, & Awards Engravers', 'Local', 'Small'),
  ('Trophy Shops', 'Local', 'Small'),
  ('Used, Rare, & Out of Print Book Stores', 'Local', 'Small'),
  ('Variety Stores', 'National', 'Big'),
  ('Video Game Stores', 'National/Loca', 'Big'),
  ('Wedding Chapels', 'Local', 'Small'),
  ('Wedding Facilities', 'Local', 'Small'),
  ('Wedding Flower Services', 'Local', 'Small'),
  ('Wedding Gifts & Favors Retail', 'Local', 'Small'),
  ('Wedding Invitations & Announcements', 'Local', 'Small'),
  ('Wedding Planners', 'Local', 'Small'),
  ('Wedding Receptions & Parties', 'Local', 'Small'),
  ('Wedding Services', 'Local', 'Small'),
  ('Wedding Events', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Shopping & Retail'
ON CONFLICT DO NOTHING;
