-- Part 6: Education and Fitness & Personal Care
-- Insert Education Industry
INSERT INTO industries (id, name, description)
VALUES ('education', 'Education', 'Educational services and institutions');

-- Insert Education Niches (73 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('education', 'Preschools and Daycares', 'Local', 10000),
('education', 'Elementary Schools', 'Local', 10000),
('education', 'Middle Schools', 'Local', 10000),
('education', 'High Schools', 'Local', 10000),
('education', 'Private Schools', 'Local', 10000),
('education', 'Charter Schools', 'Local', 10000),
('education', 'Montessori Schools', 'Local', 10000),
('education', 'Waldorf Schools', 'Local', 10000),
('education', 'Special Education Schools', 'Local', 10000),
('education', 'Alternative Education Programs', 'Local', 10000),
('education', 'Homeschooling Resources and Support', 'National', 50000),
('education', 'After-School Programs', 'Local', 10000),
('education', 'Summer Camps', 'Local', 10000),
('education', 'Tutoring Services', 'Local', 10000),
('education', 'Test Preparation Services', 'National', 50000),
('education', 'College and Career Counseling', 'Local', 10000),
('education', 'Educational Consulting', 'National', 50000),
('education', 'Learning Centers', 'Local', 10000),
('education', 'STEM Education Programs', 'National', 50000),
('education', 'Arts Education Programs', 'Local', 10000),
('education', 'Music Schools and Lessons', 'Local', 10000),
('education', 'Dance Schools and Studios', 'Local', 10000),
('education', 'Drama and Theater Programs', 'Local', 10000),
('education', 'Language Schools and Classes', 'Local', 10000),
('education', 'ESL and English Language Programs', 'Local', 10000),
('education', 'Adult Education Programs', 'Local', 10000),
('education', 'Continuing Education', 'National', 50000),
('education', 'Professional Development Training', 'National', 50000),
('education', 'Corporate Training Services', 'National', 50000),
('education', 'Technical and Vocational Training', 'Local', 10000),
('education', 'Trade Schools', 'Local', 10000),
('education', 'Culinary Schools', 'National', 50000),
('education', 'Beauty and Cosmetology Schools', 'Local', 10000),
('education', 'Driving Schools', 'Local', 10000),
('education', 'Flight Schools', 'Local', 10000),
('education', 'Boating and Maritime Schools', 'Local', 10000),
('education', 'Motorcycle Training', 'Local', 10000),
('education', 'Real Estate Schools', 'National', 50000),
('education', 'Insurance and Financial Training', 'National', 50000),
('education', 'Healthcare Training Programs', 'National', 50000),
('education', 'Medical Assistant Training', 'Local', 10000),
('education', 'Nursing Programs', 'Local', 10000),
('education', 'Pharmacy Technician Training', 'Local', 10000),
('education', 'Dental Assistant Training', 'Local', 10000),
('education', 'Massage Therapy Schools', 'Local', 10000),
('education', 'Fitness Instructor Training', 'National', 50000),
('education', 'Yoga Teacher Training', 'National', 50000),
('education', 'Martial Arts Schools', 'Local', 10000),
('education', 'Sports Training and Coaching', 'Local', 10000),
('education', 'Academic Enrichment Programs', 'Local', 10000),
('education', 'Reading and Literacy Programs', 'Local', 10000),
('education', 'Math and Science Enrichment', 'Local', 10000),
('education', 'Gifted and Talented Programs', 'Local', 10000),
('education', 'Study Skills and Organization', 'Local', 10000),
('education', 'College Prep Programs', 'Local', 10000),
('education', 'SAT and ACT Prep', 'National', 50000),
('education', 'GED Preparation', 'Local', 10000),
('education', 'College Admissions Consulting', 'National', 50000),
('education', 'Educational Therapy', 'Local', 10000),
('education', 'Learning Disability Support', 'Local', 10000),
('education', 'Behavioral Intervention Services', 'Local', 10000),
('education', 'Speech and Language Therapy', 'Local', 10000),
('education', 'Occupational Therapy Services', 'Local', 10000),
('education', 'Educational Assessment and Testing', 'Local', 10000),
('education', 'Online Education Platforms', 'National', 50000),
('education', 'Distance Learning Programs', 'National', 50000),
('education', 'Virtual Schools', 'National', 50000),
('education', 'Educational Technology and Software', 'National', 50000),
('education', 'Curriculum Development', 'National', 50000),
('education', 'Educational Publishing', 'National', 50000),
('education', 'Textbook and Materials Supply', 'National', 50000),
('education', 'School Supply Stores', 'Local', 10000),
('education', 'Educational Toys and Games', 'National', 50000);

-- Insert Fitness & Personal Care Industry
INSERT INTO industries (id, name, description)
VALUES ('fitness-personal-care', 'Fitness & Personal Care', 'Fitness, wellness, and personal care services');

-- Insert Fitness & Personal Care Niches (58 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('fitness-personal-care', 'Gyms and Fitness Centers', 'Local', 10000),
('fitness-personal-care', 'Personal Training Services', 'Local', 10000),
('fitness-personal-care', 'Yoga Studios', 'Local', 10000),
('fitness-personal-care', 'Pilates Studios', 'Local', 10000),
('fitness-personal-care', 'CrossFit Gyms', 'Local', 10000),
('fitness-personal-care', 'Martial Arts Schools', 'Local', 10000),
('fitness-personal-care', 'Boxing and Kickboxing Gyms', 'Local', 10000),
('fitness-personal-care', 'Dance Studios', 'Local', 10000),
('fitness-personal-care', 'Cycling and Spin Studios', 'Local', 10000),
('fitness-personal-care', 'Barre Studios', 'Local', 10000),
('fitness-personal-care', 'Boot Camp Programs', 'Local', 10000),
('fitness-personal-care', 'Sports Performance Training', 'Local', 10000),
('fitness-personal-care', 'Swimming Lessons and Aquatics', 'Local', 10000),
('fitness-personal-care', 'Rock Climbing Gyms', 'Local', 10000),
('fitness-personal-care', 'Trampoline and Parkour Parks', 'Local', 10000),
('fitness-personal-care', 'Nutrition Counseling and Coaching', 'Local', 10000),
('fitness-personal-care', 'Weight Loss Programs', 'National', 50000),
('fitness-personal-care', 'Meal Prep and Planning Services', 'Local', 10000),
('fitness-personal-care', 'Wellness Coaching', 'National', 50000),
('fitness-personal-care', 'Health and Wellness Retreats', 'National', 50000),
('fitness-personal-care', 'Spa and Massage Services', 'Local', 10000),
('fitness-personal-care', 'Massage Therapy', 'Local', 10000),
('fitness-personal-care', 'Chiropractor Services', 'Local', 10000),
('fitness-personal-care', 'Physical Therapy', 'Local', 10000),
('fitness-personal-care', 'Acupuncture Services', 'Local', 10000),
('fitness-personal-care', 'Holistic and Alternative Medicine', 'Local', 10000),
('fitness-personal-care', 'Meditation and Mindfulness Centers', 'Local', 10000),
('fitness-personal-care', 'Mental Health Counseling', 'Local', 10000),
('fitness-personal-care', 'Life Coaching', 'National', 50000),
('fitness-personal-care', 'Beauty Salons and Hairdressers', 'Local', 10000),
('fitness-personal-care', 'Barbershops', 'Local', 10000),
('fitness-personal-care', 'Nail Salons', 'Local', 10000),
('fitness-personal-care', 'Skincare and Facials', 'Local', 10000),
('fitness-personal-care', 'Makeup Artists', 'Local', 10000),
('fitness-personal-care', 'Tanning Salons', 'Local', 10000),
('fitness-personal-care', 'Waxing and Hair Removal', 'Local', 10000),
('fitness-personal-care', 'Tattoo and Piercing Studios', 'Local', 10000),
('fitness-personal-care', 'Medical Spas', 'Local', 10000),
('fitness-personal-care', 'Cosmetic and Plastic Surgery', 'Local', 10000),
('fitness-personal-care', 'Laser Hair Removal', 'Local', 10000),
('fitness-personal-care', 'Botox and Dermal Fillers', 'Local', 10000),
('fitness-personal-care', 'Weight Management Clinics', 'Local', 10000),
('fitness-personal-care', 'IV Therapy and Hydration', 'Local', 10000),
('fitness-personal-care', 'Cryotherapy Services', 'Local', 10000),
('fitness-personal-care', 'Sauna and Steam Room Facilities', 'Local', 10000),
('fitness-personal-care', 'Flotation and Sensory Deprivation', 'Local', 10000),
('fitness-personal-care', 'Oxygen Bars', 'Local', 10000),
('fitness-personal-care', 'Personal Care Products', 'National', 50000),
('fitness-personal-care', 'Health and Wellness Products', 'National', 50000),
('fitness-personal-care', 'Supplements and Vitamins', 'National', 50000),
('fitness-personal-care', 'Fitness Equipment and Apparel', 'National', 50000),
('fitness-personal-care', 'Recovery and Rehabilitation Services', 'Local', 10000),
('fitness-personal-care', 'Sports Medicine Clinics', 'Local', 10000),
('fitness-personal-care', 'Athletic Training Services', 'Local', 10000),
('fitness-personal-care', 'Ergonomics and Posture Correction', 'Local', 10000),
('fitness-personal-care', 'Senior Fitness Programs', 'Local', 10000),
('fitness-personal-care', 'Pre and Postnatal Fitness', 'Local', 10000),
('fitness-personal-care', 'Adaptive and Inclusive Fitness', 'Local', 10000);
