-- Sports (81 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Baseball Clubs & Parks', 'Local', 'Small'),
  ('Baseball Equipment & Supplies', 'National/Loca', 'Big'),
  ('Baseball Instruction', 'Local', 'Small'),
  ('Basketball Clubs & Instruction', 'Local', 'Small'),
  ('Batting Ranges', 'Local', 'Small'),
  ('Bicycle Dealers', 'National/Loca', 'Big'),
  ('Billiard & Pool Halls', 'Local', 'Small'),
  ('Billiard Table Dealers', 'Local', 'Small'),
  ('Billiards Equipment Dealers', 'Local', 'Small'),
  ('Bingo Halls', 'Local', 'Small'),
  ('Boarding Stables', 'Local', 'Small'),
  ('Boat & Yacht Charters', 'Local', 'Small'),
  ('Boat & Yacht Insurance', 'National', 'Big'),
  ('Boat Dealers', 'National/Loca', 'Big'),
  ('Bowling Alleys', 'Local', 'Small'),
  ('Bowling Equipment Dealers', 'National', 'Big'),
  ('Boxing Clubs & Instruction', 'Local', 'Small'),
  ('Campgrounds', 'Local', 'Small'),
  ('Camping Equipment Retail', 'National/Loca', 'Big'),
  ('Recreational Camps', 'Local', 'Small'),
  ('Canoe & Kayak Dealers', 'Local', 'Small'),
  ('Casinos', 'National/Loca', 'Big'),
  ('Chess Instruction', 'Local', 'Small'),
  ('Country Clubs', 'Local', 'Small'),
  ('Diving Equipment Dealers', 'National', 'Big'),
  ('Fitness Equipment Wholesale & Manufacturers', 'National', 'Big'),
  ('Fishing Bait & Tackle Retail', 'Local', 'Small'),
  ('Fishing Equipment Dealers', 'National/Loca', 'Big'),
  ('Fishing Guides & Charters', 'Local', 'Small'),
  ('Golf Facilities', 'Local', 'Small'),
  ('Golf Cart Dealers', 'National/Loca', 'Big'),
  ('Golf Course Consultants', 'National', 'Big'),
  ('Golf Courses', 'Local', 'Small'),
  ('Golf Driving Ranges', 'Local', 'Small'),
  ('Golf Equipment Retail', 'National/Loca', 'Big'),
  ('Gun Safety Instruction', 'Local', 'Small'),
  ('Guns & Ammunition Dealers', 'National/Loca', 'Big'),
  ('Gunsmiths', 'Local', 'Small'),
  ('Hobby Stores', 'Local', 'Small'),
  ('Horse Breeders & Dealers', 'Local', 'Small'),
  ('Horseback Riding Instruction', 'Local', 'Small'),
  ('Hot Air Balloon Rides', 'Local', 'Small'),
  ('Ice Skating Rinks & Instruction', 'Local', 'Small'),
  ('Karate, Judo, & Kung Fu Instruction', 'Local', 'Small'),
  ('Lottery Tickets', 'National', 'Big'),
  ('Martial Arts Instruction', 'Local', 'Small'),
  ('Metal Detector Retail', 'Local', 'Small'),
  ('Miniature Golf Courses', 'Local', 'Small'),
  ('Outdoor Sports & Recreation Retail', 'National/Loca', 'Big'),
  ('Paintball Equipment Retail', 'Local', 'Small'),
  ('Parks & Playgrounds', 'Local', 'Small'),
  ('Personal Watercraft Rentals', 'Local', 'Small'),
  ('Playground Equipment Dealers', 'National/Loca', 'Big'),
  ('Private Golf Courses', 'Local', 'Small'),
  ('Professional & Amateur Sports Teams', 'National/Loca', 'Big'),
  ('Public & Private Swimming Pools', 'Local', 'Small'),
  ('Public Golf Courses', 'Local', 'Small'),
  ('RV Equipment & Supplies Retail', 'National/Loca', 'Big'),
  ('RV Rental Services', 'Local', 'Small'),
  ('RV Dealers', 'National/Loca', 'Big'),
  ('Recreation Centers', 'Local', 'Small'),
  ('Roller Skating Rinks & Instruction', 'Local', 'Small'),
  ('Sailboat Charter & Rental', 'Local', 'Small'),
  ('Scuba & Skin Diving Equipment Dealers', 'National/Loca', 'Big'),
  ('Skate Shops', 'Local', 'Small'),
  ('Skateboard & Inline Skates Rental', 'Local', 'Small'),
  ('Ski Resorts', 'National', 'Big'),
  ('Skiing Equipment Retail', 'National', 'Big'),
  ('Skydiving Centers', 'Local', 'Small'),
  ('Snorkeling Equipment Dealers', 'Local', 'Small'),
  ('Snowmobile Dealers', 'National/Loca', 'Big'),
  ('Snowmobile Rentals & Tours', 'Local', 'Small'),
  ('Sporting Goods Retail', 'National/Loca', 'Big'),
  ('Sporting Goods Wholesale', 'National', 'Big'),
  ('Sports & Recreation Clubs', 'Local', 'Small'),
  ('Sports Facilities', 'Local', 'Small'),
  ('Sports Camps', 'Local', 'Small'),
  ('Tennis Clubs', 'Local', 'Small'),
  ('Tennis Courts', 'Local', 'Small'),
  ('Tennis Equipment Retail', 'National/Loca', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Sports'
ON CONFLICT DO NOTHING;

-- Travel & Transport (87 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Accommodation Reservations', 'National', 'Big'),
  ('Air Cargo & Package Express Services', 'National/Loca', 'Big'),
  ('Air Transportation', 'National', 'Big'),
  ('Aircraft Charter, Rental, & Leasing', 'Local', 'Small'),
  ('Airline Flight Information', 'National', 'Big'),
  ('Airline Tickets', 'National', 'Big'),
  ('Airline Travel Agents', 'National', 'Big'),
  ('Airports', 'National/Loca', 'Big'),
  ('Auto Parts Warehouses', 'National', 'Big'),
  ('Bed & Breakfasts', 'Local', 'Small'),
  ('Bus Charter', 'Local', 'Small'),
  ('Bus Tours', 'Local', 'Small'),
  ('Bus Travel', 'National/Loca', 'Big'),
  ('Cabin, Cottage, & Chalet Rental', 'Local', 'Small'),
  ('Commodity & Merchandise Warehouses', 'National', 'Big'),
  ('Commuter & Public Transportation', 'Local', 'Small'),
  ('Contract Haulers', 'Local', 'Small'),
  ('Corporate Limousine Services', 'Local', 'Small'),
  ('Courier & Delivery Services (Commercial)', 'National/Loca', 'Big'),
  ('Courier & Delivery Services (Residential)', 'Local', 'Small'),
  ('Cruise Lines & Agents', 'National', 'Big'),
  ('Cruise Travel Agents', 'National', 'Big'),
  ('Customs Brokers & Consultants', 'National', 'Big'),
  ('Delivery Services', 'Local', 'Small'),
  ('Distribution Services', 'National', 'Big'),
  ('Docks', 'Local', 'Small'),
  ('Fishing Boat Charters', 'Local', 'Small'),
  ('Freight & Cargo Containers', 'National', 'Big'),
  ('Freight & Cargo Transport', 'National', 'Big'),
  ('Freight Agents & Brokers', 'National', 'Big'),
  ('Freight Forwarding Services', 'National', 'Big'),
  ('Freight Trucking', 'National', 'Big'),
  ('Full Service Moving & Storage', 'National/Loca', 'Big'),
  ('Furniture Movers', 'Local', 'Small'),
  ('Heavy Duty Trucking', 'National', 'Big'),
  ('Helicopter Charter, Rental, & Leasing', 'Local', 'Small'),
  ('Honeymoon Resorts', 'National/Loca', 'Big'),
  ('Hotel Reservations', 'National', 'Big'),
  ('Hotels', 'National', 'Big'),
  ('Household Goods & Furniture Storage', 'Local', 'Small'),
  ('Household Movers', 'Local', 'Small'),
  ('Inns', 'Local', 'Small'),
  ('International Movers', 'National', 'Big'),
  ('Limousine Services', 'Local', 'Small'),
  ('Local Bus Charters', 'Local', 'Small'),
  ('Local Trucking', 'Local', 'Small'),
  ('Lodging', 'Local', 'Small'),
  ('Logistics', 'National', 'Big'),
  ('Mail Box Rental', 'Local', 'Small'),
  ('Mail Services & Package Shipping', 'National', 'Big'),
  ('Mailing Services', 'National/Loca', 'Big'),
  ('Marinas', 'Local', 'Small'),
  ('Marine Equipment Retail', 'National', 'Big'),
  ('Mini & Self Storage Warehouses', 'Local', 'Small'),
  ('Motels', 'Local', 'Small'),
  ('Movers', 'Local', 'Small'),
  ('Moving & Storage (Commercial)', 'National/Loca', 'Big'),
  ('Moving Equipment Rental', 'Local', 'Small'),
  ('Moving Labor Services', 'Local', 'Small'),
  ('Packaging Services', 'National/Loca', 'Big'),
  ('Passport & Visa Services', 'National', 'Big'),
  ('Piano & Organ Movers', 'Local', 'Small'),
  ('Portable Storage Rental', 'Local', 'Small'),
  ('Railroads', 'National', 'Big'),
  ('Resorts & Vacation Cottages', 'Local', 'Small'),
  ('Self Service Moving & Storage', 'Local', 'Small'),
  ('Self Storage', 'Local', 'Small'),
  ('Shuttle Transportation Services', 'Local', 'Small'),
  ('Snow Removal Services', 'Local', 'Small'),
  ('Specialty Warehousing & Storage', 'National', 'Big'),
  ('Storage Racks', 'National', 'Big'),
  ('Taxi Services', 'Local', 'Small'),
  ('Taxis', 'Local', 'Small'),
  ('Tourist Information & Attractions', 'Local', 'Small'),
  ('Tours & Charters', 'Local', 'Small'),
  ('Transportation Equipment Dealers', 'National', 'Big'),
  ('Transportation Services', 'National/Loca', 'Big'),
  ('Travel Agents', 'National', 'Big'),
  ('Travel Clubs & Services', 'National', 'Big'),
  ('Travel Consultants', 'National/Loca', 'Big'),
  ('Travel Industry Services', 'National', 'Big'),
  ('Trucking Companies', 'National', 'Big'),
  ('Vacation Home Rentals', 'Local', 'Small'),
  ('Vacation Packages', 'National', 'Big'),
  ('Warehouses & Warehousing', 'National', 'Big'),
  ('Water Taxis', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Travel & Transport'
ON CONFLICT DO NOTHING;
