-- Part 7: Home Improvements and Hospitality & Food
-- Insert Home Improvements Industry
INSERT INTO industries (id, name, description)
VALUES ('home-improvements', 'Home Improvements', 'Home repair, maintenance, and improvement services');

-- Insert Home Improvements Niches (78 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('home-improvements', 'Handyman Services', 'Local', 10000),
('home-improvements', 'Home Repair and Maintenance', 'Local', 10000),
('home-improvements', 'Appliance Repair and Installation', 'Local', 10000),
('home-improvements', 'Carpet Cleaning and Repair', 'Local', 10000),
('home-improvements', 'Upholstery Cleaning and Repair', 'Local', 10000),
('home-improvements', 'Window Cleaning Services', 'Local', 10000),
('home-improvements', 'Pressure Washing and Power Cleaning', 'Local', 10000),
('home-improvements', 'Gutter Cleaning and Repair', 'Local', 10000),
('home-improvements', 'Chimney Sweeping and Repair', 'Local', 10000),
('home-improvements', 'Locksmith Services', 'Local', 10000),
('home-improvements', 'Security System Installation', 'Local', 10000),
('home-improvements', 'Home Theater Installation', 'Local', 10000),
('home-improvements', 'Smart Home Installation', 'Local', 10000),
('home-improvements', 'Lighting Installation and Repair', 'Local', 10000),
('home-improvements', 'Ceiling Fan Installation', 'Local', 10000),
('home-improvements', 'Crown Molding Installation', 'Local', 10000),
('home-improvements', 'Cabinet Refacing and Refinishing', 'Local', 10000),
('home-improvements', 'Countertop Installation', 'Local', 10000),
('home-improvements', 'Backsplash Installation', 'Local', 10000),
('home-improvements', 'Bathroom Remodeling', 'Local', 10000),
('home-improvements', 'Shower and Tub Installation', 'Local', 10000),
('home-improvements', 'Toilet Repair and Installation', 'Local', 10000),
('home-improvements', 'Faucet and Fixture Installation', 'Local', 10000),
('home-improvements', 'Water Heater Installation and Repair', 'Local', 10000),
('home-improvements', 'Drain Cleaning and Repair', 'Local', 10000),
('home-improvements', 'Sewer Line Repair', 'Local', 10000),
('home-improvements', 'Leak Detection and Repair', 'Local', 10000),
('home-improvements', 'Basement Waterproofing', 'Local', 10000),
('home-improvements', 'Foundation Repair', 'Local', 10000),
('home-improvements', 'Crawl Space Encapsulation', 'Local', 10000),
('home-improvements', 'Attic Insulation and Ventilation', 'Local', 10000),
('home-improvements', 'Mold Inspection and Remediation', 'Local', 10000),
('home-improvements', 'Pest Control and Extermination', 'Local', 10000),
('home-improvements', 'Termite Inspection and Treatment', 'Local', 10000),
('home-improvements', 'Wildlife Removal', 'Local', 10000),
('home-improvements', 'Tree Trimming and Removal', 'Local', 10000),
('home-improvements', 'Stump Grinding and Removal', 'Local', 10000),
('home-improvements', 'Lawn Care and Maintenance', 'Local', 10000),
('home-improvements', 'Lawn Mowing Services', 'Local', 10000),
('home-improvements', 'Landscape Design and Installation', 'Local', 10000),
('home-improvements', 'Landscape Lighting', 'Local', 10000),
('home-improvements', 'Sprinkler System Installation', 'Local', 10000),
('home-improvements', 'Sod Installation', 'Local', 10000),
('home-improvements', 'Mulch and Soil Delivery', 'Local', 10000),
('home-improvements', 'Retaining Wall Construction', 'Local', 10000),
('home-improvements', 'Patio and Paver Installation', 'Local', 10000),
('home-improvements', 'Outdoor Kitchen Installation', 'Local', 10000),
('home-improvements', 'Pool Maintenance and Repair', 'Local', 10000),
('home-improvements', 'Pool Cleaning Services', 'Local', 10000),
('home-improvements', 'Hot Tub Repair and Maintenance', 'Local', 10000),
('home-improvements', 'Fence Installation and Repair', 'Local', 10000),
('home-improvements', 'Gate Installation and Repair', 'Local', 10000),
('home-improvements', 'Deck Building and Repair', 'Local', 10000),
('home-improvements', 'Deck Staining and Sealing', 'Local', 10000),
('home-improvements', 'Pergola and Gazebo Installation', 'Local', 10000),
('home-improvements', 'Shed Installation and Repair', 'Local', 10000),
('home-improvements', 'Garage Organization Systems', 'Local', 10000),
('home-improvements', 'Closet Organization and Design', 'Local', 10000),
('home-improvements', 'Shelving and Storage Solutions', 'Local', 10000),
('home-improvements', 'Murphy Bed Installation', 'Local', 10000),
('home-improvements', 'Home Office Design and Setup', 'Local', 10000),
('home-improvements', 'Wallpaper Installation and Removal', 'Local', 10000),
('home-improvements', 'Popcorn Ceiling Removal', 'Local', 10000),
('home-improvements', 'Texture and Faux Finishing', 'Local', 10000),
('home-improvements', 'Hardwood Floor Refinishing', 'Local', 10000),
('home-improvements', 'Floor Leveling Services', 'Local', 10000),
('home-improvements', 'Carpet Installation', 'Local', 10000),
('home-improvements', 'Tile and Grout Cleaning', 'Local', 10000),
('home-improvements', 'Door Installation and Repair', 'Local', 10000),
('home-improvements', 'Window Replacement', 'Local', 10000),
('home-improvements', 'Screen Door and Window Repair', 'Local', 10000),
('home-improvements', 'Skylight Installation', 'Local', 10000),
('home-improvements', 'Attic Ladder Installation', 'Local', 10000),
('home-improvements', 'Exhaust Fan Installation', 'Local', 10000),
('home-improvements', 'Driveway Sealing and Repair', 'Local', 10000),
('home-improvements', 'Garage Door Repair', 'Local', 10000),
('home-improvements', 'Home Energy Audits', 'Local', 10000),
('home-improvements', 'Solar Panel Installation', 'Local', 10000);

-- Insert Hospitality & Food Industry
INSERT INTO industries (id, name, description)
VALUES ('hospitality-food', 'Hospitality & Food', 'Restaurants, food services, and hospitality businesses');

-- Insert Hospitality & Food Niches (83 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('hospitality-food', 'Restaurants', 'Local', 10000),
('hospitality-food', 'Fast Food and Quick Service', 'National', 50000),
('hospitality-food', 'Fast Casual Dining', 'National', 50000),
('hospitality-food', 'Casual Dining Restaurants', 'Local', 10000),
('hospitality-food', 'Fine Dining Restaurants', 'Local', 10000),
('hospitality-food', 'Steakhouses', 'Local', 10000),
('hospitality-food', 'Seafood Restaurants', 'Local', 10000),
('hospitality-food', 'Italian Restaurants', 'Local', 10000),
('hospitality-food', 'Mexican Restaurants', 'Local', 10000),
('hospitality-food', 'Chinese Restaurants', 'Local', 10000),
('hospitality-food', 'Japanese and Sushi Restaurants', 'Local', 10000),
('hospitality-food', 'Thai Restaurants', 'Local', 10000),
('hospitality-food', 'Indian Restaurants', 'Local', 10000),
('hospitality-food', 'Mediterranean Restaurants', 'Local', 10000),
('hospitality-food', 'Greek Restaurants', 'Local', 10000),
('hospitality-food', 'French Restaurants', 'Local', 10000),
('hospitality-food', 'American Restaurants', 'Local', 10000),
('hospitality-food', 'Southern and Soul Food', 'Local', 10000),
('hospitality-food', 'BBQ and Grill Restaurants', 'Local', 10000),
('hospitality-food', 'Pizza Restaurants', 'Local', 10000),
('hospitality-food', 'Burger Restaurants', 'Local', 10000),
('hospitality-food', 'Sandwich Shops and Delis', 'Local', 10000),
('hospitality-food', 'Breakfast and Brunch Cafes', 'Local', 10000),
('hospitality-food', 'Coffee Shops and Cafes', 'Local', 10000),
('hospitality-food', 'Bakeries and Pastry Shops', 'Local', 10000),
('hospitality-food', 'Dessert and Ice Cream Shops', 'Local', 10000),
('hospitality-food', 'Donut Shops', 'Local', 10000),
('hospitality-food', 'Juice Bars and Smoothie Shops', 'Local', 10000),
('hospitality-food', 'Vegetarian and Vegan Restaurants', 'Local', 10000),
('hospitality-food', 'Organic and Farm-to-Table Dining', 'Local', 10000),
('hospitality-food', 'Gluten-Free Restaurants', 'Local', 10000),
('hospitality-food', 'Food Trucks and Mobile Vendors', 'Local', 10000),
('hospitality-food', 'Catering Services', 'Local', 10000),
('hospitality-food', 'Event Catering', 'Local', 10000),
('hospitality-food', 'Corporate Catering', 'Local', 10000),
('hospitality-food', 'Wedding Catering', 'Local', 10000),
('hospitality-food', 'Personal Chef Services', 'Local', 10000),
('hospitality-food', 'Meal Delivery Services', 'National', 50000),
('hospitality-food', 'Meal Kit Services', 'National', 50000),
('hospitality-food', 'Grocery Delivery Services', 'Local', 10000),
('hospitality-food', 'Food and Beverage Wholesalers', 'National', 50000),
('hospitality-food', 'Restaurant Supply and Equipment', 'National', 50000),
('hospitality-food', 'Commercial Kitchen Rentals', 'Local', 10000),
('hospitality-food', 'Bars and Nightclubs', 'Local', 10000),
('hospitality-food', 'Wine Bars', 'Local', 10000),
('hospitality-food', 'Sports Bars', 'Local', 10000),
('hospitality-food', 'Brewpubs and Microbreweries', 'Local', 10000),
('hospitality-food', 'Distilleries and Tasting Rooms', 'Local', 10000),
('hospitality-food', 'Wineries and Vineyards', 'Local', 10000),
('hospitality-food', 'Cigar Lounges', 'Local', 10000),
('hospitality-food', 'Tea Houses', 'Local', 10000),
('hospitality-food', 'Hotels and Resorts', 'National', 50000),
('hospitality-food', 'Motels and Motor Lodges', 'Local', 10000),
('hospitality-food', 'Bed and Breakfasts', 'Local', 10000),
('hospitality-food', 'Vacation Rentals', 'Local', 10000),
('hospitality-food', 'Hostels', 'Local', 10000),
('hospitality-food', 'Extended Stay Hotels', 'National', 50000),
('hospitality-food', 'Boutique Hotels', 'Local', 10000),
('hospitality-food', 'Luxury Hotels and Spas', 'National', 50000),
('hospitality-food', 'Casino Hotels', 'National', 50000),
('hospitality-food', 'Golf Resorts', 'National', 50000),
('hospitality-food', 'Ski Resorts and Lodges', 'National', 50000),
('hospitality-food', 'Beach Resorts', 'National', 50000),
('hospitality-food', 'Conference and Convention Centers', 'Local', 10000),
('hospitality-food', 'Event Venues and Banquet Halls', 'Local', 10000),
('hospitality-food', 'Wedding Venues', 'Local', 10000),
('hospitality-food', 'Country Clubs and Private Clubs', 'Local', 10000),
('hospitality-food', 'RV Parks and Campgrounds', 'Local', 10000),
('hospitality-food', 'Marinas and Boat Rentals', 'Local', 10000),
('hospitality-food', 'Tour Operators and Guides', 'Local', 10000),
('hospitality-food', 'Travel Agencies', 'Local', 10000),
('hospitality-food', 'Concierge Services', 'Local', 10000),
('hospitality-food', 'Hotel Management Services', 'National', 50000),
('hospitality-food', 'Hospitality Consulting', 'National', 50000),
('hospitality-food', 'Restaurant Consulting', 'National', 50000),
('hospitality-food', 'Food Safety and Compliance', 'National', 50000),
('hospitality-food', 'Menu Design and Development', 'National', 50000),
('hospitality-food', 'Restaurant POS Systems', 'National', 50000),
('hospitality-food', 'Online Ordering Platforms', 'National', 50000),
('hospitality-food', 'Reservation Management Systems', 'National', 50000),
('hospitality-food', 'Food Photography and Styling', 'National', 50000),
('hospitality-food', 'Culinary Schools and Training', 'National', 50000);
