-- Corrected all niche names to match document exactly, fixed "National/Loca" to "National/Local"
-- Sports (81 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Baseball Clubs & Parks', 'Local', 'Small'),
  ('Baseball Equipment & Supplies', 'National/Local', 'Big'),
  ('Baseball Instruction', 'Local', 'Small'),
  ('Basketball Clubs', 'Local', 'Small'),
  ('Batting Ranges', 'Local', 'Small'),
  ('Bicycles', 'National/Local', 'Big'),
  ('Billiard Parlors', 'Local', 'Small'),
  ('Billiard Tables', 'Local', 'Small'),
  ('Billiards', 'Local', 'Small'),
  ('Bingo', 'Local', 'Small'),
  ('Boarding Stables', 'Local', 'Small'),
  ('Boat Charters', 'Local', 'Small'),
  ('Boat Insurance', 'National', 'Big'),
  ('Boats', 'National/Local', 'Big'),
  ('Bowling', 'Local', 'Small'),
  ('Bowling Equipment', 'National', 'Big'),
  ('Boxing Instruction', 'Local', 'Small'),
  ('Campgrounds', 'Local', 'Small'),
  ('Camping Equipment', 'National/Local', 'Big'),
  ('Camps', 'Local', 'Small'),
  ('Canoes', 'Local', 'Small'),
  ('Casinos', 'National/Local', 'Big'),
  ('Chess Instruction', 'Local', 'Small'),
  ('Country Clubs', 'Local', 'Small'),
  ('Diving Equipment', 'National', 'Big'),
  ('Exercise Equipment Wholesale', 'National', 'Big'),
  ('Fishing Bait & Tackle', 'Local', 'Small'),
  ('Fishing Equipment', 'National/Local', 'Big'),
  ('Fishing Guides', 'Local', 'Small'),
  ('Golf', 'Local', 'Small'),
  ('Golf Carts', 'National/Local', 'Big'),
  ('Golf Course Architects', 'National', 'Big'),
  ('Golf Courses', 'Local', 'Small'),
  ('Golf Driving Ranges', 'Local', 'Small'),
  ('Golf Equipment', 'National/Local', 'Big'),
  ('Gun Safety Instruction', 'Local', 'Small'),
  ('Guns & Gunsmiths', 'National/Local', 'Big'),
  ('Gunsmiths', 'Local', 'Small'),
  ('Hobby Shops', 'Local', 'Small'),
  ('Horses', 'Local', 'Small'),
  ('Horseback Riding', 'Local', 'Small'),
  ('Hot Air Balloons', 'Local', 'Small'),
  ('Ice Skating', 'Local', 'Small'),
  ('Karate & Other Martial Arts', 'Local', 'Small'),
  ('Lottery', 'National', 'Big'),
  ('Martial Arts', 'Local', 'Small'),
  ('Metal Detectors', 'Local', 'Small'),
  ('Miniature Golf', 'Local', 'Small'),
  ('Outdoor Sports', 'National/Local', 'Big'),
  ('Paintball', 'Local', 'Small'),
  ('Parks', 'Local', 'Small'),
  ('Personal Watercraft', 'Local', 'Small'),
  ('Playground Equipment', 'National/Local', 'Big'),
  ('Private Golf Courses', 'Local', 'Small'),
  ('Professional Sports Teams', 'National/Local', 'Big'),
  ('Public & Private Swimming Pools', 'Local', 'Small'),
  ('Public Golf Courses', 'Local', 'Small'),
  ('RV Equipment & Supplies', 'National/Local', 'Big'),
  ('RV Rental', 'Local', 'Small'),
  ('RVs', 'National/Local', 'Big'),
  ('Recreation Centers', 'Local', 'Small'),
  ('Roller Skating', 'Local', 'Small'),
  ('Sailboats', 'Local', 'Small'),
  ('Scuba Diving', 'National/Local', 'Big'),
  ('Skateboards', 'Local', 'Small'),
  ('Skateboard Parks', 'Local', 'Small'),
  ('Ski Resorts', 'National', 'Big'),
  ('Skiing Equipment', 'National', 'Big'),
  ('Sky Diving', 'Local', 'Small'),
  ('Snorkeling', 'Local', 'Small'),
  ('Snowmobiles', 'National/Local', 'Big'),
  ('Snowmobiles Rental', 'Local', 'Small'),
  ('Sporting Goods', 'National/Local', 'Big'),
  ('Sporting Goods Wholesale', 'National', 'Big'),
  ('Sports & Recreation', 'Local', 'Small'),
  ('Sports Facilities', 'Local', 'Small'),
  ('Sports Instruction', 'Local', 'Small'),
  ('Tennis Courts', 'Local', 'Small'),
  ('Tennis Courts Private', 'Local', 'Small'),
  ('Tennis Equipment', 'National/Local', 'Big')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Sports'
ON CONFLICT DO NOTHING;

-- Travel & Transport (87 niches)
INSERT INTO niches (industry_id, niche_name, scale, database_size)
SELECT id, niche_name, scale, database_size FROM industries, (VALUES
  ('Accommodations', 'National', 'Big'),
  ('Air Cargo', 'National/Local', 'Big'),
  ('Air Transportation', 'National', 'Big'),
  ('Aircraft Charter', 'Local', 'Small'),
  ('Airline Information', 'National', 'Big'),
  ('Airline Tickets', 'National', 'Big'),
  ('Airlines', 'National', 'Big'),
  ('Airports', 'National/Local', 'Big'),
  ('Auto Parts Stores', 'National', 'Big'),
  ('Bed & Breakfast', 'Local', 'Small'),
  ('Bus Charter', 'Local', 'Small'),
  ('Bus Tours', 'Local', 'Small'),
  ('Buses', 'National/Local', 'Big'),
  ('Cabins', 'Local', 'Small'),
  ('Commodity Warehouses', 'National', 'Big'),
  ('Commuter Transportation', 'Local', 'Small'),
  ('Contract Haulers', 'Local', 'Small'),
  ('Corporate Limousines', 'Local', 'Small'),
  ('Courier Service Commercial', 'National/Local', 'Big'),
  ('Courier Service Residential', 'Local', 'Small'),
  ('Cruise Lines', 'National', 'Big'),
  ('Cruises', 'National', 'Big'),
  ('Customs Brokers', 'National', 'Big'),
  ('Delivery Service', 'Local', 'Small'),
  ('Distribution', 'National', 'Big'),
  ('Docks', 'Local', 'Small'),
  ('Fishing Charters', 'Local', 'Small'),
  ('Freight & Cargo Containers', 'National', 'Big'),
  ('Freight & Cargo', 'National', 'Big'),
  ('Freight Agents', 'National', 'Big'),
  ('Freight Forwarding', 'National', 'Big'),
  ('Freight Trucking', 'National', 'Big'),
  ('Full Service Moving', 'National/Local', 'Big'),
  ('Furniture Movers', 'Local', 'Small'),
  ('Heavy Hauling', 'National', 'Big'),
  ('Helicopter Charter', 'Local', 'Small'),
  ('Honeymoon Resorts', 'National/Local', 'Big'),
  ('Hotel Reservations', 'National', 'Big'),
  ('Hotels', 'National', 'Big'),
  ('Household Storage', 'Local', 'Small'),
  ('Household Moving', 'Local', 'Small'),
  ('Inns', 'Local', 'Small'),
  ('International Moving', 'National', 'Big'),
  ('Limousines', 'Local', 'Small'),
  ('Local Bus Lines', 'Local', 'Small'),
  ('Local Trucking', 'Local', 'Small'),
  ('Lodging', 'Local', 'Small'),
  ('Logistics', 'National', 'Big'),
  ('Mail Box Rental', 'Local', 'Small'),
  ('Mail Services', 'National', 'Big'),
  ('Mailing Services', 'National/Local', 'Big'),
  ('Marinas', 'Local', 'Small'),
  ('Marine Equipment', 'National', 'Big'),
  ('Mini Storage', 'Local', 'Small'),
  ('Motels', 'Local', 'Small'),
  ('Movers', 'Local', 'Small'),
  ('Moving & Storage Commercial', 'National/Local', 'Big'),
  ('Moving Equipment Rental', 'Local', 'Small'),
  ('Moving Labor', 'Local', 'Small'),
  ('Packing & Crating', 'National/Local', 'Big'),
  ('Passports & Visas', 'National', 'Big'),
  ('Piano Movers', 'Local', 'Small'),
  ('Portable Storage', 'Local', 'Small'),
  ('Railroads', 'National', 'Big'),
  ('Resorts', 'Local', 'Small'),
  ('Self Service Moving', 'Local', 'Small'),
  ('Self Storage', 'Local', 'Small'),
  ('Shuttle Services', 'Local', 'Small'),
  ('Snow Removal', 'Local', 'Small'),
  ('Specialty Warehousing', 'National', 'Big'),
  ('Storage Racks', 'National', 'Big'),
  ('Taxi & Limousine', 'Local', 'Small'),
  ('Taxis', 'Local', 'Small'),
  ('Tourist Information', 'Local', 'Small'),
  ('Tours', 'Local', 'Small'),
  ('Transportation Equipment', 'National', 'Big'),
  ('Transportation Services', 'National/Local', 'Big'),
  ('Travel Agencies', 'National', 'Big'),
  ('Travel Clubs', 'National', 'Big'),
  ('Travel Consultants', 'National/Local', 'Big'),
  ('Travel Services', 'National', 'Big'),
  ('Trucking', 'National', 'Big'),
  ('Vacation Homes', 'Local', 'Small'),
  ('Vacation Packages', 'National', 'Big'),
  ('Warehouses', 'National', 'Big'),
  ('Water Taxis', 'Local', 'Small')
) AS t(niche_name, scale, database_size)
WHERE industries.name = 'Travel & Transport'
ON CONFLICT DO NOTHING;
