-- Part 8: Legal & Financial and Media & Comms
-- Insert Legal & Financial Industry
INSERT INTO industries (id, name, description)
VALUES ('legal-financial', 'Legal & Financial', 'Legal, financial, and professional services');

-- Insert Legal & Financial Niches (122 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('legal-financial', 'General Practice Attorneys', 'Local', 10000),
('legal-financial', 'Personal Injury Lawyers', 'Local', 10000),
('legal-financial', 'Car Accident Lawyers', 'Local', 10000),
('legal-financial', 'Medical Malpractice Lawyers', 'Local', 10000),
('legal-financial', 'Workers Compensation Attorneys', 'Local', 10000),
('legal-financial', 'Criminal Defense Lawyers', 'Local', 10000),
('legal-financial', 'DUI and DWI Attorneys', 'Local', 10000),
('legal-financial', 'Family Law Attorneys', 'Local', 10000),
('legal-financial', 'Divorce Lawyers', 'Local', 10000),
('legal-financial', 'Child Custody Attorneys', 'Local', 10000),
('legal-financial', 'Adoption Lawyers', 'Local', 10000),
('legal-financial', 'Estate Planning Attorneys', 'Local', 10000),
('legal-financial', 'Probate Lawyers', 'Local', 10000),
('legal-financial', 'Trust Administration', 'Local', 10000),
('legal-financial', 'Elder Law Attorneys', 'Local', 10000),
('legal-financial', 'Real Estate Attorneys', 'Local', 10000),
('legal-financial', 'Property Law Lawyers', 'Local', 10000),
('legal-financial', 'Landlord Tenant Attorneys', 'Local', 10000),
('legal-financial', 'Business Lawyers', 'Local', 10000),
('legal-financial', 'Corporate Attorneys', 'National', 50000),
('legal-financial', 'Contract Lawyers', 'National', 50000),
('legal-financial', 'Employment Lawyers', 'Local', 10000),
('legal-financial', 'Labor Law Attorneys', 'Local', 10000),
('legal-financial', 'Civil Rights Lawyers', 'Local', 10000),
('legal-financial', 'Immigration Lawyers', 'Local', 10000),
('legal-financial', 'Bankruptcy Attorneys', 'Local', 10000),
('legal-financial', 'Tax Lawyers', 'Local', 10000),
('legal-financial', 'Intellectual Property Lawyers', 'National', 50000),
('legal-financial', 'Patent Attorneys', 'National', 50000),
('legal-financial', 'Trademark Attorneys', 'National', 50000),
('legal-financial', 'Copyright Lawyers', 'National', 50000),
('legal-financial', 'Entertainment Lawyers', 'National', 50000),
('legal-financial', 'Sports Law Attorneys', 'National', 50000),
('legal-financial', 'Healthcare Lawyers', 'National', 50000),
('legal-financial', 'Environmental Lawyers', 'National', 50000),
('legal-financial', 'Securities Lawyers', 'National', 50000),
('legal-financial', 'Mergers and Acquisitions Attorneys', 'National', 50000),
('legal-financial', 'Litigation Lawyers', 'Local', 10000),
('legal-financial', 'Trial Attorneys', 'Local', 10000),
('legal-financial', 'Appellate Lawyers', 'National', 50000),
('legal-financial', 'Class Action Attorneys', 'National', 50000),
('legal-financial', 'Consumer Rights Lawyers', 'Local', 10000),
('legal-financial', 'Debt Collection Defense', 'Local', 10000),
('legal-financial', 'Social Security Disability Lawyers', 'Local', 10000),
('legal-financial', 'Veterans Benefits Attorneys', 'Local', 10000),
('legal-financial', 'Notary Public Services', 'Local', 10000),
('legal-financial', 'Process Servers', 'Local', 10000),
('legal-financial', 'Court Reporting Services', 'Local', 10000),
('legal-financial', 'Legal Document Preparation', 'Local', 10000),
('legal-financial', 'Paralegal Services', 'Local', 10000),
('legal-financial', 'Legal Research Services', 'National', 50000),
('legal-financial', 'Mediation Services', 'Local', 10000),
('legal-financial', 'Arbitration Services', 'National', 50000),
('legal-financial', 'Expert Witness Services', 'National', 50000),
('legal-financial', 'Legal Translation Services', 'National', 50000),
('legal-financial', 'Banks and Credit Unions', 'Local', 10000),
('legal-financial', 'Mortgage Lenders', 'National', 50000),
('legal-financial', 'Mortgage Brokers', 'Local', 10000),
('legal-financial', 'Home Equity Loans', 'National', 50000),
('legal-financial', 'Refinancing Services', 'National', 50000),
('legal-financial', 'Commercial Lending', 'National', 50000),
('legal-financial', 'Small Business Loans', 'National', 50000),
('legal-financial', 'Auto Loans and Financing', 'National', 50000),
('legal-financial', 'Personal Loans', 'National', 50000),
('legal-financial', 'Student Loans', 'National', 50000),
('legal-financial', 'Payday Loans and Cash Advances', 'Local', 10000),
('legal-financial', 'Credit Repair Services', 'National', 50000),
('legal-financial', 'Debt Consolidation Services', 'National', 50000),
('legal-financial', 'Financial Planning Services', 'Local', 10000),
('legal-financial', 'Investment Advisory Services', 'National', 50000),
('legal-financial', 'Wealth Management', 'National', 50000),
('legal-financial', 'Retirement Planning', 'Local', 10000),
('legal-financial', 'Tax Preparation Services', 'Local', 10000),
('legal-financial', 'Accounting Services', 'Local', 10000),
('legal-financial', 'Bookkeeping Services', 'Local', 10000),
('legal-financial', 'Payroll Services', 'National', 50000),
('legal-financial', 'Audit Services', 'National', 50000),
('legal-financial', 'Forensic Accounting', 'National', 50000),
('legal-financial', 'Business Valuation Services', 'National', 50000),
('legal-financial', 'CFO and Controller Services', 'National', 50000),
('legal-financial', 'Financial Consulting', 'National', 50000),
('legal-financial', 'Business Consulting', 'National', 50000),
('legal-financial', 'Management Consulting', 'National', 50000),
('legal-financial', 'Insurance Agents and Brokers', 'Local', 10000),
('legal-financial', 'Life Insurance', 'National', 50000),
('legal-financial', 'Health Insurance', 'National', 50000),
('legal-financial', 'Auto Insurance', 'National', 50000),
('legal-financial', 'Home Insurance', 'National', 50000),
('legal-financial', 'Renters Insurance', 'National', 50000),
('legal-financial', 'Business Insurance', 'National', 50000),
('legal-financial', 'Liability Insurance', 'National', 50000),
('legal-financial', 'Workers Compensation Insurance', 'National', 50000),
('legal-financial', 'Disability Insurance', 'National', 50000),
('legal-financial', 'Long-Term Care Insurance', 'National', 50000),
('legal-financial', 'Umbrella Insurance', 'National', 50000),
('legal-financial', 'Pet Insurance', 'National', 50000),
('legal-financial', 'Travel Insurance', 'National', 50000),
('legal-financial', 'Insurance Claims Adjusters', 'Local', 10000),
('legal-financial', 'Public Adjusters', 'Local', 10000),
('legal-financial', 'Real Estate Agents and Brokers', 'Local', 10000),
('legal-financial', 'Residential Real Estate', 'Local', 10000),
('legal-financial', 'Commercial Real Estate', 'National', 50000),
('legal-financial', 'Property Management', 'Local', 10000),
('legal-financial', 'Real Estate Appraisers', 'Local', 10000),
('legal-financial', 'Real Estate Investors', 'National', 50000),
('legal-financial', 'Title Companies', 'Local', 10000),
('legal-financial', 'Escrow Services', 'Local', 10000),
('legal-financial', 'Home Inspectors', 'Local', 10000),
('legal-financial', 'Real Estate Photography', 'Local', 10000),
('legal-financial', 'Real Estate Staging', 'Local', 10000),
('legal-financial', 'Investment Properties', 'National', 50000),
('legal-financial', 'Real Estate Development', 'National', 50000),
('legal-financial', 'Commercial Leasing', 'National', 50000),
('legal-financial', 'Stock Brokers and Trading', 'National', 50000),
('legal-financial', 'Cryptocurrency and Blockchain', 'National', 50000),
('legal-financial', '401k and Retirement Plans', 'National', 50000),
('legal-financial', 'Annuities', 'National', 50000),
('legal-financial', 'Mutual Funds', 'National', 50000),
('legal-financial', 'Private Equity and Venture Capital', 'National', 50000);

-- Insert Media & Comms Industry
INSERT INTO industries (id, name, description)
VALUES ('media-comms', 'Media & Comms', 'Media, communications, and publishing businesses');

-- Insert Media & Comms Niches (43 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('media-comms', 'Newspapers and Print Media', 'Local', 10000),
('media-comms', 'Magazines and Periodicals', 'National', 50000),
('media-comms', 'Book Publishers', 'National', 50000),
('media-comms', 'Self-Publishing Services', 'National', 50000),
('media-comms', 'Radio Stations', 'Local', 10000),
('media-comms', 'Television Stations', 'Local', 10000),
('media-comms', 'Cable and Satellite Providers', 'National', 50000),
('media-comms', 'Streaming Services', 'National', 50000),
('media-comms', 'Podcast Production', 'National', 50000),
('media-comms', 'Video Production Services', 'Local', 10000),
('media-comms', 'Film and Movie Production', 'National', 50000),
('media-comms', 'Animation Studios', 'National', 50000),
('media-comms', 'Recording Studios', 'Local', 10000),
('media-comms', 'Music Production', 'National', 50000),
('media-comms', 'Photography Services', 'Local', 10000),
('media-comms', 'Wedding Photography', 'Local', 10000),
('media-comms', 'Portrait Photography', 'Local', 10000),
('media-comms', 'Commercial Photography', 'National', 50000),
('media-comms', 'Event Photography', 'Local', 10000),
('media-comms', 'Stock Photography', 'National', 50000),
('media-comms', 'Photo Editing Services', 'National', 50000),
('media-comms', 'Videography Services', 'Local', 10000),
('media-comms', 'Advertising Agencies', 'National', 50000),
('media-comms', 'Marketing Agencies', 'National', 50000),
('media-comms', 'Public Relations Firms', 'National', 50000),
('media-comms', 'Social Media Marketing', 'National', 50000),
('media-comms', 'Digital Marketing Services', 'National', 50000),
('media-comms', 'Content Marketing', 'National', 50000),
('media-comms', 'Copywriting Services', 'National', 50000),
('media-comms', 'Graphic Design Services', 'National', 50000),
('media-comms', 'Branding and Logo Design', 'National', 50000),
('media-comms', 'Web Design and Development', 'National', 50000),
('media-comms', 'SEO Services', 'National', 50000),
('media-comms', 'Email Marketing', 'National', 50000),
('media-comms', 'Influencer Marketing', 'National', 50000),
('media-comms', 'Market Research', 'National', 50000),
('media-comms', 'Translation and Interpretation', 'National', 50000),
('media-comms', 'Transcription Services', 'National', 50000),
('media-comms', 'Voiceover and Narration', 'National', 50000),
('media-comms', 'Telecommunications Services', 'National', 50000),
('media-comms', 'Phone and Internet Providers', 'National', 50000),
('media-comms', 'Business Phone Systems', 'National', 50000),
('media-comms', 'Call Center Services', 'National', 50000);
