-- Part 9: Medicine & Health and Real Estate
-- Insert Medicine & Health Industry
INSERT INTO industries (id, name, description)
VALUES ('medicine-health', 'Medicine & Health', 'Healthcare and medical services');

-- Insert Medicine & Health Niches (97 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('medicine-health', 'Primary Care Physicians', 'Local', 10000),
('medicine-health', 'Family Medicine', 'Local', 10000),
('medicine-health', 'Internal Medicine', 'Local', 10000),
('medicine-health', 'Pediatricians', 'Local', 10000),
('medicine-health', 'Geriatric Medicine', 'Local', 10000),
('medicine-health', 'Urgent Care Centers', 'Local', 10000),
('medicine-health', 'Walk-In Clinics', 'Local', 10000),
('medicine-health', 'Emergency Medicine', 'Local', 10000),
('medicine-health', 'Hospitals', 'Local', 10000),
('medicine-health', 'Medical Centers', 'Local', 10000),
('medicine-health', 'Specialty Clinics', 'Local', 10000),
('medicine-health', 'Cardiology', 'Local', 10000),
('medicine-health', 'Dermatology', 'Local', 10000),
('medicine-health', 'Endocrinology', 'Local', 10000),
('medicine-health', 'Gastroenterology', 'Local', 10000),
('medicine-health', 'Nephrology', 'Local', 10000),
('medicine-health', 'Neurology', 'Local', 10000),
('medicine-health', 'Oncology', 'Local', 10000),
('medicine-health', 'Orthopedics', 'Local', 10000),
('medicine-health', 'Otolaryngology (ENT)', 'Local', 10000),
('medicine-health', 'Ophthalmology', 'Local', 10000),
('medicine-health', 'Optometry', 'Local', 10000),
('medicine-health', 'Podiatry', 'Local', 10000),
('medicine-health', 'Psychiatry', 'Local', 10000),
('medicine-health', 'Psychology and Counseling', 'Local', 10000),
('medicine-health', 'Pulmonology', 'Local', 10000),
('medicine-health', 'Rheumatology', 'Local', 10000),
('medicine-health', 'Urology', 'Local', 10000),
('medicine-health', 'Obstetrics and Gynecology', 'Local', 10000),
('medicine-health', 'Fertility Clinics', 'Local', 10000),
('medicine-health', 'Midwifery Services', 'Local', 10000),
('medicine-health', 'Allergy and Immunology', 'Local', 10000),
('medicine-health', 'Infectious Disease', 'Local', 10000),
('medicine-health', 'Pain Management', 'Local', 10000),
('medicine-health', 'Sports Medicine', 'Local', 10000),
('medicine-health', 'Physical Medicine and Rehabilitation', 'Local', 10000),
('medicine-health', 'Anesthesiology', 'Local', 10000),
('medicine-health', 'Radiology', 'Local', 10000),
('medicine-health', 'Pathology', 'Local', 10000),
('medicine-health', 'Surgery Centers', 'Local', 10000),
('medicine-health', 'General Surgery', 'Local', 10000),
('medicine-health', 'Plastic and Cosmetic Surgery', 'Local', 10000),
('medicine-health', 'Bariatric Surgery', 'Local', 10000),
('medicine-health', 'Cardiovascular Surgery', 'Local', 10000),
('medicine-health', 'Neurosurgery', 'Local', 10000),
('medicine-health', 'Oral and Maxillofacial Surgery', 'Local', 10000),
('medicine-health', 'Dental Clinics', 'Local', 10000),
('medicine-health', 'General Dentistry', 'Local', 10000),
('medicine-health', 'Orthodontics', 'Local', 10000),
('medicine-health', 'Periodontics', 'Local', 10000),
('medicine-health', 'Endodontics', 'Local', 10000),
('medicine-health', 'Prosthodontics', 'Local', 10000),
('medicine-health', 'Pediatric Dentistry', 'Local', 10000),
('medicine-health', 'Cosmetic Dentistry', 'Local', 10000),
('medicine-health', 'Dental Implants', 'Local', 10000),
('medicine-health', 'Teeth Whitening Services', 'Local', 10000),
('medicine-health', 'Oral Surgery', 'Local', 10000),
('medicine-health', 'Pharmacies', 'Local', 10000),
('medicine-health', 'Compounding Pharmacies', 'Local', 10000),
('medicine-health', 'Medical Supply Stores', 'Local', 10000),
('medicine-health', 'Durable Medical Equipment', 'Local', 10000),
('medicine-health', 'Home Health Care', 'Local', 10000),
('medicine-health', 'Hospice Care', 'Local', 10000),
('medicine-health', 'Nursing Homes', 'Local', 10000),
('medicine-health', 'Assisted Living Facilities', 'Local', 10000),
('medicine-health', 'Memory Care Facilities', 'Local', 10000),
('medicine-health', 'Rehabilitation Centers', 'Local', 10000),
('medicine-health', 'Physical Therapy', 'Local', 10000),
('medicine-health', 'Occupational Therapy', 'Local', 10000),
('medicine-health', 'Speech Therapy', 'Local', 10000),
('medicine-health', 'Mental Health Counseling', 'Local', 10000),
('medicine-health', 'Substance Abuse Treatment', 'Local', 10000),
('medicine-health', 'Addiction Recovery Centers', 'Local', 10000),
('medicine-health', 'Behavioral Health Services', 'Local', 10000),
('medicine-health', 'Eating Disorder Treatment', 'Local', 10000),
('medicine-health', 'Sleep Medicine', 'Local', 10000),
('medicine-health', 'Sleep Disorder Centers', 'Local', 10000),
('medicine-health', 'Diagnostic Imaging Centers', 'Local', 10000),
('medicine-health', 'MRI and CT Scan Facilities', 'Local', 10000),
('medicine-health', 'Ultrasound Services', 'Local', 10000),
('medicine-health', 'X-Ray Facilities', 'Local', 10000),
('medicine-health', 'Laboratory Services', 'Local', 10000),
('medicine-health', 'Blood Testing Services', 'Local', 10000),
('medicine-health', 'Genetic Testing', 'National', 50000),
('medicine-health', 'Medical Testing and Screening', 'Local', 10000),
('medicine-health', 'Dialysis Centers', 'Local', 10000),
('medicine-health', 'Infusion Centers', 'Local', 10000),
('medicine-health', 'Wound Care Centers', 'Local', 10000),
('medicine-health', 'Medical Spas', 'Local', 10000),
('medicine-health', 'Weight Loss Clinics', 'Local', 10000),
('medicine-health', 'Wellness Centers', 'Local', 10000),
('medicine-health', 'Alternative and Integrative Medicine', 'Local', 10000),
('medicine-health', 'Acupuncture and Acupressure', 'Local', 10000),
('medicine-health', 'Chiropractic Care', 'Local', 10000),
('medicine-health', 'Naturopathic Medicine', 'Local', 10000),
('medicine-health', 'Homeopathy', 'Local', 10000);

-- Insert Real Estate Industry
INSERT INTO industries (id, name, description)
VALUES ('real-estate', 'Real Estate', 'Real estate services and property businesses');

-- Insert Real Estate Niches (66 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('real-estate', 'Residential Real Estate', 'Local', 10000),
('real-estate', 'Single-Family Homes', 'Local', 10000),
('real-estate', 'Condominiums', 'Local', 10000),
('real-estate', 'Townhouses', 'Local', 10000),
('real-estate', 'Multi-Family Properties', 'Local', 10000),
('real-estate', 'Luxury Real Estate', 'Local', 10000),
('real-estate', 'New Construction Homes', 'Local', 10000),
('real-estate', 'First-Time Home Buyers', 'Local', 10000),
('real-estate', 'Real Estate Agents', 'Local', 10000),
('real-estate', 'Real Estate Brokers', 'Local', 10000),
('real-estate', 'Buyer''s Agents', 'Local', 10000),
('real-estate', 'Seller''s Agents', 'Local', 10000),
('real-estate', 'Commercial Real Estate', 'National', 50000),
('real-estate', 'Office Buildings', 'National', 50000),
('real-estate', 'Retail Properties', 'National', 50000),
('real-estate', 'Industrial Properties', 'National', 50000),
('real-estate', 'Warehouse and Distribution Centers', 'National', 50000),
('real-estate', 'Shopping Centers and Malls', 'National', 50000),
('real-estate', 'Mixed-Use Developments', 'National', 50000),
('real-estate', 'Investment Properties', 'National', 50000),
('real-estate', 'Rental Properties', 'Local', 10000),
('real-estate', 'Property Management', 'Local', 10000),
('real-estate', 'HOA Management', 'Local', 10000),
('real-estate', 'Vacation Rentals', 'Local', 10000),
('real-estate', 'Short-Term Rentals', 'Local', 10000),
('real-estate', 'Student Housing', 'Local', 10000),
('real-estate', 'Senior Housing', 'Local', 10000),
('real-estate', 'Affordable Housing', 'Local', 10000),
('real-estate', 'Real Estate Investment Trusts (REITs)', 'National', 50000),
('real-estate', 'Real Estate Investors', 'National', 50000),
('real-estate', 'House Flipping', 'Local', 10000),
('real-estate', 'Real Estate Wholesaling', 'National', 50000),
('real-estate', 'Land Sales', 'Local', 10000),
('real-estate', 'Farm and Ranch Land', 'Local', 10000),
('real-estate', 'Waterfront Properties', 'Local', 10000),
('real-estate', 'Mountain Properties', 'Local', 10000),
('real-estate', 'Foreclosures and Short Sales', 'Local', 10000),
('real-estate', 'Estate Sales', 'Local', 10000),
('real-estate', 'Real Estate Auctions', 'Local', 10000),
('real-estate', 'Title and Escrow Services', 'Local', 10000),
('real-estate', 'Real Estate Attorneys', 'Local', 10000),
('real-estate', 'Real Estate Appraisers', 'Local', 10000),
('real-estate', 'Home Inspectors', 'Local', 10000),
('real-estate', 'Termite Inspectors', 'Local', 10000),
('real-estate', 'Property Surveyors', 'Local', 10000),
('real-estate', 'Real Estate Photography', 'Local', 10000),
('real-estate', 'Virtual Tour Services', 'National', 50000),
('real-estate', 'Drone Photography for Real Estate', 'Local', 10000),
('real-estate', 'Home Staging Services', 'Local', 10000),
('real-estate', 'Interior Design for Real Estate', 'Local', 10000),
('real-estate', 'Real Estate Marketing', 'National', 50000),
('real-estate', 'Real Estate Websites and Portals', 'National', 50000),
('real-estate', 'MLS Services', 'Local', 10000),
('real-estate', 'Real Estate CRM Software', 'National', 50000),
('real-estate', 'Property Listing Services', 'National', 50000),
('real-estate', 'Relocation Services', 'National', 50000),
('real-estate', 'Corporate Relocation', 'National', 50000),
('real-estate', 'International Real Estate', 'National', 50000),
('real-estate', 'Real Estate Developers', 'National', 50000),
('real-estate', 'Land Development', 'National', 50000),
('real-estate', 'Real Estate Consulting', 'National', 50000),
('real-estate', 'Real Estate Coaching', 'National', 50000),
('real-estate', 'Real Estate Education and Training', 'National', 50000),
('real-estate', 'Real Estate Franchises', 'National', 50000),
('real-estate', 'Co-Working Spaces', 'Local', 10000),
('real-estate', 'Self-Storage Facilities', 'Local', 10000);
