-- Part 10: Shopping & Retail, Sports, and Travel & Transport
-- Insert Shopping & Retail Industry
INSERT INTO industries (id, name, description)
VALUES ('shopping-retail', 'Shopping & Retail', 'Retail stores and shopping businesses');

-- Insert Shopping & Retail Niches (74 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('shopping-retail', 'Department Stores', 'National', 50000),
('shopping-retail', 'Discount and Dollar Stores', 'National', 50000),
('shopping-retail', 'Warehouse Clubs', 'National', 50000),
('shopping-retail', 'Convenience Stores', 'Local', 10000),
('shopping-retail', 'Grocery Stores', 'Local', 10000),
('shopping-retail', 'Supermarkets', 'Local', 10000),
('shopping-retail', 'Organic and Natural Food Stores', 'Local', 10000),
('shopping-retail', 'Specialty Food Stores', 'Local', 10000),
('shopping-retail', 'Butcher Shops', 'Local', 10000),
('shopping-retail', 'Seafood Markets', 'Local', 10000),
('shopping-retail', 'Farmers Markets', 'Local', 10000),
('shopping-retail', 'Bakeries', 'Local', 10000),
('shopping-retail', 'Candy and Confectionery Stores', 'Local', 10000),
('shopping-retail', 'Liquor Stores', 'Local', 10000),
('shopping-retail', 'Wine and Spirits Shops', 'Local', 10000),
('shopping-retail', 'Tobacco Shops', 'Local', 10000),
('shopping-retail', 'Vape Shops', 'Local', 10000),
('shopping-retail', 'Drugstores and Pharmacies', 'Local', 10000),
('shopping-retail', 'Health and Wellness Stores', 'Local', 10000),
('shopping-retail', 'Vitamin and Supplement Stores', 'Local', 10000),
('shopping-retail', 'Beauty Supply Stores', 'Local', 10000),
('shopping-retail', 'Cosmetics Stores', 'Local', 10000),
('shopping-retail', 'Perfume and Fragrance Stores', 'Local', 10000),
('shopping-retail', 'Sporting Goods Stores', 'Local', 10000),
('shopping-retail', 'Outdoor and Camping Gear', 'National', 50000),
('shopping-retail', 'Fishing and Hunting Supplies', 'Local', 10000),
('shopping-retail', 'Bicycle Shops', 'Local', 10000),
('shopping-retail', 'Golf Stores', 'Local', 10000),
('shopping-retail', 'Ski and Snowboard Shops', 'Local', 10000),
('shopping-retail', 'Fitness Equipment Stores', 'Local', 10000),
('shopping-retail', 'Toy Stores', 'Local', 10000),
('shopping-retail', 'Hobby and Craft Stores', 'Local', 10000),
('shopping-retail', 'Art Supply Stores', 'Local', 10000),
('shopping-retail', 'Music Stores', 'Local', 10000),
('shopping-retail', 'Bookstores', 'Local', 10000),
('shopping-retail', 'Comic Book Shops', 'Local', 10000),
('shopping-retail', 'Game Stores', 'Local', 10000),
('shopping-retail', 'Video Game Stores', 'Local', 10000),
('shopping-retail', 'Electronics Stores', 'National', 50000),
('shopping-retail', 'Computer and Software Stores', 'Local', 10000),
('shopping-retail', 'Cell Phone Stores', 'Local', 10000),
('shopping-retail', 'Camera and Photography Stores', 'Local', 10000),
('shopping-retail', 'Home Improvement Stores', 'National', 50000),
('shopping-retail', 'Hardware Stores', 'Local', 10000),
('shopping-retail', 'Paint and Wallpaper Stores', 'Local', 10000),
('shopping-retail', 'Flooring Stores', 'Local', 10000),
('shopping-retail', 'Tile and Stone Stores', 'Local', 10000),
('shopping-retail', 'Kitchen and Bath Showrooms', 'Local', 10000),
('shopping-retail', 'Appliance Stores', 'Local', 10000),
('shopping-retail', 'Furniture Stores', 'Local', 10000),
('shopping-retail', 'Home Decor Stores', 'Local', 10000),
('shopping-retail', 'Lighting Stores', 'Local', 10000),
('shopping-retail', 'Mattress Stores', 'Local', 10000),
('shopping-retail', 'Bedding and Linens', 'Local', 10000),
('shopping-retail', 'Housewares and Kitchenware', 'Local', 10000),
('shopping-retail', 'Garden Centers and Nurseries', 'Local', 10000),
('shopping-retail', 'Pet Stores', 'Local', 10000),
('shopping-retail', 'Aquarium and Fish Stores', 'Local', 10000),
('shopping-retail', 'Feed and Farm Supply', 'Local', 10000),
('shopping-retail', 'Jewelry Stores', 'Local', 10000),
('shopping-retail', 'Watch Stores', 'Local', 10000),
('shopping-retail', 'Pawn Shops', 'Local', 10000),
('shopping-retail', 'Antique Stores', 'Local', 10000),
('shopping-retail', 'Thrift Stores', 'Local', 10000),
('shopping-retail', 'Consignment Shops', 'Local', 10000),
('shopping-retail', 'Gift Shops', 'Local', 10000),
('shopping-retail', 'Souvenir Shops', 'Local', 10000),
('shopping-retail', 'Party Supply Stores', 'Local', 10000),
('shopping-retail', 'Balloon and Party Decorations', 'Local', 10000),
('shopping-retail', 'Greeting Card Stores', 'Local', 10000),
('shopping-retail', 'Stationery Stores', 'Local', 10000),
('shopping-retail', 'Office Supply Stores', 'Local', 10000),
('shopping-retail', 'Print and Copy Shops', 'Local', 10000),
('shopping-retail', 'Luggage and Travel Accessories', 'Local', 10000);

-- Insert Sports Industry
INSERT INTO industries (id, name, description)
VALUES ('sports', 'Sports', 'Sports facilities, equipment, and services');

-- Insert Sports Niches (81 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('sports', 'Professional Sports Teams', 'National', 50000),
('sports', 'Sports Arenas and Stadiums', 'Local', 10000),
('sports', 'Sports Bars and Restaurants', 'Local', 10000),
('sports', 'Sports Broadcasting and Media', 'National', 50000),
('sports', 'Sports Marketing and Management', 'National', 50000),
('sports', 'Sports Photography and Videography', 'Local', 10000),
('sports', 'Youth Sports Leagues', 'Local', 10000),
('sports', 'Adult Sports Leagues', 'Local', 10000),
('sports', 'Baseball Facilities', 'Local', 10000),
('sports', 'Basketball Courts', 'Local', 10000),
('sports', 'Soccer Fields and Complexes', 'Local', 10000),
('sports', 'Football Fields', 'Local', 10000),
('sports', 'Tennis Courts and Clubs', 'Local', 10000),
('sports', 'Racquetball and Squash Courts', 'Local', 10000),
('sports', 'Volleyball Courts', 'Local', 10000),
('sports', 'Ice Skating Rinks', 'Local', 10000),
('sports', 'Hockey Rinks', 'Local', 10000),
('sports', 'Roller Skating Rinks', 'Local', 10000),
('sports', 'Bowling Alleys', 'Local', 10000),
('sports', 'Golf Courses', 'Local', 10000),
('sports', 'Mini Golf and Putt-Putt', 'Local', 10000),
('sports', 'Driving Ranges', 'Local', 10000),
('sports', 'Golf Instruction and Lessons', 'Local', 10000),
('sports', 'Swimming Pools and Aquatic Centers', 'Local', 10000),
('sports', 'Gymnastics Centers', 'Local', 10000),
('sports', 'Cheerleading Programs', 'Local', 10000),
('sports', 'Martial Arts Dojos', 'Local', 10000),
('sports', 'Karate Schools', 'Local', 10000),
('sports', 'Taekwondo Schools', 'Local', 10000),
('sports', 'Jiu-Jitsu Academies', 'Local', 10000),
('sports', 'Boxing Gyms', 'Local', 10000),
('sports', 'MMA Training Centers', 'Local', 10000),
('sports', 'Wrestling Programs', 'Local', 10000),
('sports', 'Track and Field Facilities', 'Local', 10000),
('sports', 'CrossCountry Running', 'Local', 10000),
('sports', 'Marathon and Race Events', 'Local', 10000),
('sports', 'Triathlon Training', 'Local', 10000),
('sports', 'Cycling Clubs and Teams', 'Local', 10000),
('sports', 'Mountain Biking Trails', 'Local', 10000),
('sports', 'Rock Climbing Gyms', 'Local', 10000),
('sports', 'Bouldering Gyms', 'Local', 10000),
('sports', 'Archery Ranges', 'Local', 10000),
('sports', 'Shooting Ranges', 'Local', 10000),
('sports', 'Paintball and Airsoft Fields', 'Local', 10000),
('sports', 'Laser Tag Arenas', 'Local', 10000),
('sports', 'Go-Kart Racing', 'Local', 10000),
('sports', 'Motorsports and Racing', 'National', 50000),
('sports', 'Skateboarding Parks', 'Local', 10000),
('sports', 'BMX Tracks', 'Local', 10000),
('sports', 'Parkour and Freerunning', 'Local', 10000),
('sports', 'Dance and Aerobics Studios', 'Local', 10000),
('sports', 'Pilates Studios', 'Local', 10000),
('sports', 'Yoga Studios', 'Local', 10000),
('sports', 'Zumba and Dance Fitness', 'Local', 10000),
('sports', 'Spin and Cycling Classes', 'Local', 10000),
('sports', 'Barre Classes', 'Local', 10000),
('sports', 'Boot Camp Fitness', 'Local', 10000),
('sports', 'Personal Training Services', 'Local', 10000),
('sports', 'Sports Coaching and Instruction', 'Local', 10000),
('sports', 'Athletic Training Services', 'Local', 10000),
('sports', 'Sports Performance Training', 'Local', 10000),
('sports', 'Speed and Agility Training', 'Local', 10000),
('sports', 'Strength and Conditioning', 'Local', 10000),
('sports', 'Sports Nutrition Coaching', 'Local', 10000),
('sports', 'Sports Medicine Clinics', 'Local', 10000),
('sports', 'Sports Physical Therapy', 'Local', 10000),
('sports', 'Sports Chiropractic', 'Local', 10000),
('sports', 'Sports Massage Therapy', 'Local', 10000),
('sports', 'Athletic Injury Prevention', 'Local', 10000),
('sports', 'Sports Rehabilitation', 'Local', 10000),
('sports', 'Sporting Goods Stores', 'Local', 10000),
('sports', 'Team Uniforms and Apparel', 'National', 50000),
('sports', 'Custom Sports Jerseys', 'National', 50000),
('sports', 'Athletic Shoes and Footwear', 'National', 50000),
('sports', 'Sports Equipment Rental', 'Local', 10000),
('sports', 'Bicycle Sales and Repair', 'Local', 10000),
('sports', 'Ski and Snowboard Equipment', 'Local', 10000),
('sports', 'Water Sports Equipment', 'Local', 10000),
('sports', 'Fishing Gear and Tackle', 'Local', 10000),
('sports', 'Hunting Equipment', 'Local', 10000),
('sports', 'Camping and Outdoor Gear', 'National', 50000);

-- Insert Travel & Transport Industry
INSERT INTO industries (id, name, description)
VALUES ('travel-transport', 'Travel & Transport', 'Transportation and travel services');

-- Insert Travel & Transport Niches (87 niches)
INSERT INTO niches (industry_id, name, scale, typical_db_size) VALUES
('travel-transport', 'Airlines', 'National', 50000),
('travel-transport', 'Private Jet Charter', 'National', 50000),
('travel-transport', 'Helicopter Tours and Services', 'Local', 10000),
('travel-transport', 'Hot Air Balloon Rides', 'Local', 10000),
('travel-transport', 'Airports and Airport Services', 'National', 50000),
('travel-transport', 'Airport Shuttles', 'Local', 10000),
('travel-transport', 'Airport Parking', 'Local', 10000),
('travel-transport', 'Taxi Services', 'Local', 10000),
('travel-transport', 'Rideshare Services', 'National', 50000),
('travel-transport', 'Limousine Services', 'Local', 10000),
('travel-transport', 'Black Car Services', 'Local', 10000),
('travel-transport', 'Car Rental Services', 'National', 50000),
('travel-transport', 'Truck Rental Services', 'National', 50000),
('travel-transport', 'RV Rentals', 'National', 50000),
('travel-transport', 'Motorcycle Rentals', 'Local', 10000),
('travel-transport', 'Bicycle Rentals', 'Local', 10000),
('travel-transport', 'Scooter and Moped Rentals', 'Local', 10000),
('travel-transport', 'Bus Services', 'Local', 10000),
('travel-transport', 'Charter Bus Services', 'National', 50000),
('travel-transport', 'School Bus Services', 'Local', 10000),
('travel-transport', 'Shuttle Services', 'Local', 10000),
('travel-transport', 'Public Transportation', 'Local', 10000),
('travel-transport', 'Train and Rail Services', 'National', 50000),
('travel-transport', 'Subway and Metro Systems', 'Local', 10000),
('travel-transport', 'Light Rail and Trams', 'Local', 10000),
('travel-transport', 'Cruise Lines', 'National', 50000),
('travel-transport', 'Ferry Services', 'Local', 10000),
('travel-transport', 'Water Taxis', 'Local', 10000),
('travel-transport', 'Boat Charters', 'Local', 10000),
('travel-transport', 'Yacht Charters', 'National', 50000),
('travel-transport', 'Boat Tours', 'Local', 10000),
('travel-transport', 'Whale Watching Tours', 'Local', 10000),
('travel-transport', 'Fishing Charters', 'Local', 10000),
('travel-transport', 'Moving and Relocation Services', 'Local', 10000),
('travel-transport', 'Long-Distance Moving', 'National', 50000),
('travel-transport', 'Local Moving Services', 'Local', 10000),
('travel-transport', 'International Moving', 'National', 50000),
('travel-transport', 'Packing and Unpacking Services', 'Local', 10000),
('travel-transport', 'Storage Facilities', 'Local', 10000),
('travel-transport', 'Furniture Delivery Services', 'Local', 10000),
('travel-transport', 'Courier and Delivery Services', 'Local', 10000),
('travel-transport', 'Parcel Delivery Services', 'National', 50000),
('travel-transport', 'Freight and Cargo Services', 'National', 50000),
('travel-transport', 'Trucking and Logistics', 'National', 50000),
('travel-transport', 'LTL and FTL Shipping', 'National', 50000),
('travel-transport', 'Freight Forwarding', 'National', 50000),
('travel-transport', 'Warehousing and Distribution', 'National', 50000),
('travel-transport', 'Third-Party Logistics (3PL)', 'National', 50000),
('travel-transport', 'Supply Chain Management', 'National', 50000),
('travel-transport', 'Customs Brokerage', 'National', 50000),
('travel-transport', 'International Shipping', 'National', 50000),
('travel-transport', 'Ocean Freight', 'National', 50000),
('travel-transport', 'Air Freight', 'National', 50000),
('travel-transport', 'Auto Transport Services', 'National', 50000),
('travel-transport', 'Motorcycle Transport', 'National', 50000),
('travel-transport', 'Boat Transport and Hauling', 'National', 50000),
('travel-transport', 'RV Transport', 'National', 50000),
('travel-transport', 'Heavy Equipment Transport', 'National', 50000),
('travel-transport', 'Travel Agencies', 'Local', 10000),
('travel-transport', 'Online Travel Booking', 'National', 50000),
('travel-transport', 'Corporate Travel Management', 'National', 50000),
('travel-transport', 'Vacation Packages', 'National', 50000),
('travel-transport', 'Honeymoon Travel Planning', 'National', 50000),
('travel-transport', 'Destination Weddings', 'National', 50000),
('travel-transport', 'Adventure Travel', 'National', 50000),
('travel-transport', 'Eco-Tourism', 'National', 50000),
('travel-transport', 'Luxury Travel Services', 'National', 50000),
('travel-transport', 'Group Travel Planning', 'National', 50000),
('travel-transport', 'Study Abroad Programs', 'National', 50000),
('travel-transport', 'Travel Insurance', 'National', 50000),
('travel-transport', 'Visa and Passport Services', 'National', 50000),
('travel-transport', 'Currency Exchange Services', 'Local', 10000),
('travel-transport', 'Travel Gear and Accessories', 'National', 50000),
('travel-transport', 'Luggage and Travel Bags', 'National', 50000),
('travel-transport', 'Travel Guides and Maps', 'National', 50000),
('travel-transport', 'Language Translation Services', 'National', 50000),
('travel-transport', 'Tour Operators', 'Local', 10000),
('travel-transport', 'Sightseeing Tours', 'Local', 10000),
('travel-transport', 'City Tours', 'Local', 10000),
('travel-transport', 'Walking Tours', 'Local', 10000),
('travel-transport', 'Bus Tours', 'Local', 10000),
('travel-transport', 'Bike Tours', 'Local', 10000),
('travel-transport', 'Food and Culinary Tours', 'Local', 10000),
('travel-transport', 'Wine and Brewery Tours', 'Local', 10000),
('travel-transport', 'Historic Tours', 'Local', 10000),
('travel-transport', 'Ghost Tours', 'Local', 10000),
('travel-transport', 'Wildlife Tours', 'Local', 10000);
