-- Insert all remaining niches for RE:VIVE database
-- This script completes the niche import to match the PDF exactly

-- Hospitality & Food (83 niches)
INSERT INTO niches (niche_name, industry_id, scale, database_size) 
SELECT niche_name, (SELECT id FROM industries WHERE name = 'Hospitality & Food'), scale, database_size
FROM (VALUES
  ('American Cuisine Restaurants', 'Local', 'Small'),
  ('Asian Restaurants', 'Local', 'Small'),
  ('BBQ Restaurants', 'Local', 'Small'),
  ('Bagel Shops', 'Local', 'Small'),
  ('Wholesale Baked Goods Manufacturers', 'National', 'Big'),
  ('Retail Bakeries', 'Local', 'Small'),
  ('Banquet Halls and Rooms', 'Local', 'Small'),
  ('Bar and Grill Establishments', 'Local', 'Small'),
  ('Bar Equipment Suppliers', 'National', 'Big'),
  ('Bottled and Bulk Water Retailers', 'Local', 'Small'),
  ('Breakfast and Brunch Cafes', 'Local', 'Small'),
  ('Breweries and Craft Beer Makers', 'National', 'Big'),
  ('Buffet-Style Restaurants', 'Local', 'Small'),
  ('Burger Joints', 'Local', 'Small'),
  ('Coffeehouses and Cafes', 'Local', 'Small'),
  ('Cajun and Creole Restaurants', 'Local', 'Small'),
  ('Cake and Pastry Shops', 'Local', 'Small'),
  ('Candy and Confectionery Retail', 'Local', 'Small'),
  ('Candy and Cookie Arrangement Services', 'Local', 'Small'),
  ('Catering Services', 'Local', 'Small'),
  ('Fried Chicken Restaurants', 'Local', 'Small'),
  ('Chinese Restaurants', 'Local', 'Small'),
  ('Chinese Grocery and Food Retail', 'Local', 'Small'),
  ('Cigarette and Cigar Accessories Retail', 'Local', 'Small'),
  ('Tobacco and Cigarette Retailers', 'Local', 'Small'),
  ('Coffee and Tea Specialty Shops', 'Local', 'Small'),
  ('Delicatessen Retailers', 'Local', 'Small'),
  ('Diners and Family Cafes', 'Local', 'Small'),
  ('Dinner Theater Venues', 'Local', 'Small'),
  ('Donut Shops', 'Local', 'Small'),
  ('Family-Style Restaurants', 'Local', 'Small'),
  ('Fast Food Chains', 'National', 'Big'),
  ('Quick Service and Takeout Restaurants', 'Local', 'Small'),
  ('Fine Dining Establishments', 'Local', 'Small'),
  ('Seafood Retailers', 'Local', 'Small'),
  ('Food Delivery Services', 'National', 'Big'),
  ('Beverage and Food Service Providers', 'National', 'Big'),
  ('Food Product Retailers', 'National', 'Big'),
  ('Wholesale Food Product Manufacturers', 'National', 'Big'),
  ('French Cuisine Restaurants', 'Local', 'Small'),
  ('German Restaurants', 'Local', 'Small'),
  ('Greek Cuisine Restaurants', 'Local', 'Small'),
  ('Supermarkets and Grocery Chains', 'National', 'Big'),
  ('Health and Organic Food Stores', 'Local', 'Small'),
  ('Ice Cream and Frozen Yogurt Parlors', 'Local', 'Small'),
  ('Indian Cuisine Restaurants', 'Local', 'Small'),
  ('Irish Pubs and Restaurants', 'Local', 'Small'),
  ('Italian Food Retail', 'Local', 'Small'),
  ('Japanese Cuisine Restaurants', 'Local', 'Small'),
  ('Commercial Kitchen Equipment Suppliers', 'National', 'Big'),
  ('Korean Cuisine Restaurants', 'Local', 'Small'),
  ('Kosher Food and Restaurants', 'Local', 'Small'),
  ('Liquor and Wine Retail Stores', 'Local', 'Small'),
  ('Lunch Cafes and Bistros', 'Local', 'Small'),
  ('Meat and Butcher Shops', 'Local', 'Small'),
  ('Mexican Grocery and Foods Retail', 'Local', 'Small'),
  ('Mexican Restaurants', 'Local', 'Small'),
  ('Middle Eastern Restaurants', 'Local', 'Small'),
  ('Oriental Food and Goods Retailers', 'Local', 'Small'),
  ('Pizza Delivery Services', 'National', 'Big'),
  ('Pub and Tavern Establishments', 'Local', 'Small'),
  ('Restaurant Equipment Retail', 'National', 'Big'),
  ('Restaurant Equipment and Service Providers', 'National', 'Big'),
  ('Wholesale Restaurant Supplies', 'National', 'Big'),
  ('General Restaurants', 'Local', 'Small'),
  ('Sandwich Shops', 'Local', 'Small'),
  ('Seafood Restaurants', 'Local', 'Small'),
  ('Soul Food Restaurants', 'Local', 'Small'),
  ('Spanish Cuisine Restaurants', 'Local', 'Small'),
  ('Gourmet and Specialty Food Retailers', 'National', 'Big'),
  ('Sports Bars', 'Local', 'Small'),
  ('Steak and Seafood Grills', 'Local', 'Small'),
  ('Steakhouses', 'Local', 'Small'),
  ('Sushi Bars', 'Local', 'Small'),
  ('Taverns and Breweries', 'Local', 'Small'),
  ('Thai Cuisine Restaurants', 'Local', 'Small'),
  ('Used Restaurant Equipment Stores', 'Local', 'Small'),
  ('Vegetarian and Vegan Restaurants', 'Local', 'Small'),
  ('Vending Machine Suppliers', 'National', 'Big'),
  ('Water Coolers and Fountain Suppliers', 'National', 'Big'),
  ('Wedding Catering Services', 'Local', 'Small'),
  ('Wine and Spirit Retail Stores', 'Local', 'Small')
) AS t(niche_name, scale, database_size);

-- Continue with remaining industries in additional SQL statements...
